In [3]:
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd
import plotly
import plotly.express as px
import plotly.graph_objects as go

print("Notebook environment is ready.")
print("Pandas version:", pd.__version__)
print("Plotly version:", plotly.__version__)
print("DuckDB version:", duckdb.__version__)

Notebook environment is ready.
Pandas version: 3.0.5
Plotly version: 6.9.0
DuckDB version: 1.5.5

In [4]:
from pathlib import Path

# Works whether Jupyter starts from the project root or notebooks folder
current_path = Path.cwd()

if current_path.name == "notebooks":
    PROJECT_ROOT = current_path.parent
else:
    PROJECT_ROOT = current_path

INKAR_FOLDER = PROJECT_ROOT / "data" / "raw" / "inkar" / "extracted"

CSV_PATH = INKAR_FOLDER / "inkar_2025.csv"
INDICATOR_PATH = INKAR_FOLDER / "Indikatorenübersicht (INKAR 2025).xlsx"
REFERENCE_PATH = INKAR_FOLDER / "BBSR_Raumgliederungen_Referenz_2023.xlsx"

print("Project root:", PROJECT_ROOT)
print("CSV exists:", CSV_PATH.exists())
print("Indicator file exists:", INDICATOR_PATH.exists())
print("Reference file exists:", REFERENCE_PATH.exists())

Project root: c:\Users\maazm\Desktop\Projects\datacareer-germany
CSV exists: True
Indicator file exists: True
Reference file exists: True

In [5]:
indicator_excel = pd.ExcelFile(INDICATOR_PATH)

print("Indicator workbook sheets:")
for sheet in indicator_excel.sheet_names:
    print("-", sheet)

Indicator workbook sheets:
- Nutzungshinweise
- Raumbeobachtung DE
- ZOM
- SDG
- Raumbeobachtung EU

c:\Users\maazm\Desktop\Projects\datacareer-germany\.venv\Lib\site-packages\openpyxl\reader\workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Raumbeobachtung DE'!$A:$I.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [6]:
indicator_raw = pd.read_excel(
    INDICATOR_PATH,
    sheet_name="Raumbeobachtung DE",
    header=None
)

print("Shape:", indicator_raw.shape)
display(indicator_raw.head(20))

Shape: (459, 9)

,0,1,2,3,4,5,6,7,8
0,INKAR 2025 – Indikatorenübersicht: Raumbeoba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kurzname,Name,Algorithmus,M_ID,Kürzel,Anmerkungen,Statistische Grundlagen,Gemeinden,Kreise
2,Absolutzahlen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bodenfläche gesamt qkm,Katasterfläche in km²,NaN,1,TN23-kataster_qkm,Als Katasterfläche bezeichnet man den vermessu...,Laufende Raumbeobachtung des BBSR; Flächenerhe...,2016-2023,2016-2023
4,Bevölkerung gesamt,Zahl der Einwohner insgesamt,NaN,2,xbev,Es handelt sich um die Zahl der Einwohner zum ...,Laufende Raumbeobachtung des BBSR; Fortschreib...,1995-2023,1995-2023
5,Bevölkerung männlich,Zahl der männlichen Einwohner,NaN,3,xbevm,Es handelt sich um die Zahl der männlichen Ein...,Laufende Raumbeobachtung des BBSR; Fortschreib...,1995-2023,1995-2023
6,Bevölkerung weiblich,Zahl der weiblichen Einwohner,NaN,4,xbevf,Es handelt sich um die Zahl der weiblichen Ein...,Laufende Raumbeobachtung des BBSR; Fortschreib...,1995-2023,1995-2023
7,Bevölkerung (mit BBSR-Zensuskorrekturen),Zensuskorrigierte Zahl der Einwohner insgesamt,NaN,5,bev_korr,Zwischen der Zahl der Bevölkerung am 31.12. ei...,Laufende Raumbeobachtung des BBSR,1995-2023,1995-2023
8,Erwerbsfähige Bevölkerung (15 bis unter 65 Jahre),Zahl der Einwohner im Alter von 15 bis unter 6...,NaN,6,ewf_1565_ges,Es handelt sich um die Zahl der Einwohner und ...,Laufende Raumbeobachtung des BBSR; Fortschreib...,2001-2023,1995-2023
9,Erwerbstätige,Zahl der Erwerbstätigen in 1000 Personen,NaN,7,et1000,Es handelt sich um die Zahl der Erwerbstätigen...,Laufende Raumbeobachtung des BBSR; Arbeitskrei...,NaN,2000-2022
10,Sozialversicherungspflichtig Beschäftigte am A...,Zahl der sozialversicherungspflichtig Beschäft...,NaN,8,sva,Es handelt sich um die Zahl der sozialversiche...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,1997-2023,1997-2023
11,Sozialversicherungspflichtig Beschäftigte am W...,Zahl der sozialversicherungspflichtig Beschäft...,NaN,9,svw,Es handelt sich um die Zahl der sozialversiche...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,1997-2023,1997-2023
12,Arbeitslose,Zahl der Arbeitslosen insgesamt,NaN,10,alo,Es handelt sich um die Zahl der Arbeitslosen i...,Laufende Raumbeobachtung des BBSR; Arbeitsmark...,1998-2023,1995-2023
13,Bruttoinlandsprodukt in 1000 Euro,Bruttoinlandsprodukt (BIP) absolut in Millione...,NaN,11,bip,Das Bruttoinlandsprodukt (BIP) misst die Produ...,Laufende Raumbeobachtung des BBSR; Arbeitskrei...,NaN,2000-2022
14,Arbeitslosigkeit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Arbeitslosigkeit - Allgemein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Arbeitslosenquote,Anteil der Arbeitslosen an den zivilen Erwerbs...,Arbeitslose <Zeitpunkt> / alle zivile Erwerbsp...,1101,q_alo,Die Arbeitslosenquote zeigt die relative Unter...,Laufende Raumbeobachtung des BBSR; Arbeitsmark...,NaN,1998-2023
17,Arbeitslosenquote Frauen,Anteil der arbeitslosen Frauen an den weiblich...,Arbeitslose Frauen <Zeitpunkt> / weibliche ziv...,1102,q_alo_f,Die Arbeitslosenquote der Frauen zeigt die rel...,Laufende Raumbeobachtung des BBSR; Arbeitsmark...,NaN,2008-2023
18,Arbeitslosenquote Männer,Anteil der arbeitslosen Männer an den männlich...,Arbeitslose Männer <Zeitpunkt> / männliche ziv...,1103,q_alo_m,Die Arbeitslosenquote der Männer zeigt die rel...,Laufende Raumbeobachtung des BBSR; Arbeitsmark...,NaN,2008-2023
19,Arbeitslose Frauen,Anteil der arbeitslosen Frauen an den Arbeitsl...,Arbeitslose Frauen <Zeitpunkt> / Arbeitslose i...,1104,a_alo_f,Anteil der von Arbeitslosigkeit betroffenen Fr...,Laufende Raumbeobachtung des BBSR; Arbeitsmark...,1998-2023,1995-2023

In [7]:
indicator_df = pd.read_excel(
    INDICATOR_PATH,
    sheet_name="Raumbeobachtung DE",
    header=1
)

print("Shape:", indicator_df.shape)
print("Columns:")
print(indicator_df.columns.tolist())

display(indicator_df.head(10))

Shape: (457, 9)
Columns:
['Kurzname', 'Name', 'Algorithmus', 'M_ID', 'Kürzel', 'Anmerkungen', 'Statistische Grundlagen', 'Gemeinden', 'Kreise']

c:\Users\maazm\Desktop\Projects\datacareer-germany\.venv\Lib\site-packages\openpyxl\reader\workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Raumbeobachtung DE'!$A:$I.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

,Kurzname,Name,Algorithmus,M_ID,Kürzel,Anmerkungen,Statistische Grundlagen,Gemeinden,Kreise
0,Absolutzahlen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bodenfläche gesamt qkm,Katasterfläche in km²,NaN,1.0,TN23-kataster_qkm,Als Katasterfläche bezeichnet man den vermessu...,Laufende Raumbeobachtung des BBSR; Flächenerhe...,2016-2023,2016-2023
2,Bevölkerung gesamt,Zahl der Einwohner insgesamt,NaN,2.0,xbev,Es handelt sich um die Zahl der Einwohner zum ...,Laufende Raumbeobachtung des BBSR; Fortschreib...,1995-2023,1995-2023
3,Bevölkerung männlich,Zahl der männlichen Einwohner,NaN,3.0,xbevm,Es handelt sich um die Zahl der männlichen Ein...,Laufende Raumbeobachtung des BBSR; Fortschreib...,1995-2023,1995-2023
4,Bevölkerung weiblich,Zahl der weiblichen Einwohner,NaN,4.0,xbevf,Es handelt sich um die Zahl der weiblichen Ein...,Laufende Raumbeobachtung des BBSR; Fortschreib...,1995-2023,1995-2023
5,Bevölkerung (mit BBSR-Zensuskorrekturen),Zensuskorrigierte Zahl der Einwohner insgesamt,NaN,5.0,bev_korr,Zwischen der Zahl der Bevölkerung am 31.12. ei...,Laufende Raumbeobachtung des BBSR,1995-2023,1995-2023
6,Erwerbsfähige Bevölkerung (15 bis unter 65 Jahre),Zahl der Einwohner im Alter von 15 bis unter 6...,NaN,6.0,ewf_1565_ges,Es handelt sich um die Zahl der Einwohner und ...,Laufende Raumbeobachtung des BBSR; Fortschreib...,2001-2023,1995-2023
7,Erwerbstätige,Zahl der Erwerbstätigen in 1000 Personen,NaN,7.0,et1000,Es handelt sich um die Zahl der Erwerbstätigen...,Laufende Raumbeobachtung des BBSR; Arbeitskrei...,NaN,2000-2022
8,Sozialversicherungspflichtig Beschäftigte am A...,Zahl der sozialversicherungspflichtig Beschäft...,NaN,8.0,sva,Es handelt sich um die Zahl der sozialversiche...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,1997-2023,1997-2023
9,Sozialversicherungspflichtig Beschäftigte am W...,Zahl der sozialversicherungspflichtig Beschäft...,NaN,9.0,svw,Es handelt sich um die Zahl der sozialversiche...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,1997-2023,1997-2023

In [8]:
valid_indicators = indicator_df[
    indicator_df["M_ID"].notna()
    & indicator_df["Kürzel"].notna()
].copy()

valid_indicators["M_ID"] = (
    pd.to_numeric(valid_indicators["M_ID"], errors="coerce")
    .astype("Int64")
)

valid_indicators = valid_indicators[
    [
        "Kurzname",
        "Name",
        "M_ID",
        "Kürzel",
        "Anmerkungen",
        "Gemeinden",
        "Kreise"
    ]
].reset_index(drop=True)

print("Number of valid indicators:", len(valid_indicators))

display(valid_indicators.head(10))

Number of valid indicators: 413

,Kurzname,Name,M_ID,Kürzel,Anmerkungen,Gemeinden,Kreise
0,Bodenfläche gesamt qkm,Katasterfläche in km²,1,TN23-kataster_qkm,Als Katasterfläche bezeichnet man den vermessu...,2016-2023,2016-2023
1,Bevölkerung gesamt,Zahl der Einwohner insgesamt,2,xbev,Es handelt sich um die Zahl der Einwohner zum ...,1995-2023,1995-2023
2,Bevölkerung männlich,Zahl der männlichen Einwohner,3,xbevm,Es handelt sich um die Zahl der männlichen Ein...,1995-2023,1995-2023
3,Bevölkerung weiblich,Zahl der weiblichen Einwohner,4,xbevf,Es handelt sich um die Zahl der weiblichen Ein...,1995-2023,1995-2023
4,Bevölkerung (mit BBSR-Zensuskorrekturen),Zensuskorrigierte Zahl der Einwohner insgesamt,5,bev_korr,Zwischen der Zahl der Bevölkerung am 31.12. ei...,1995-2023,1995-2023
5,Erwerbsfähige Bevölkerung (15 bis unter 65 Jahre),Zahl der Einwohner im Alter von 15 bis unter 6...,6,ewf_1565_ges,Es handelt sich um die Zahl der Einwohner und ...,2001-2023,1995-2023
6,Erwerbstätige,Zahl der Erwerbstätigen in 1000 Personen,7,et1000,Es handelt sich um die Zahl der Erwerbstätigen...,NaN,2000-2022
7,Sozialversicherungspflichtig Beschäftigte am A...,Zahl der sozialversicherungspflichtig Beschäft...,8,sva,Es handelt sich um die Zahl der sozialversiche...,1997-2023,1997-2023
8,Sozialversicherungspflichtig Beschäftigte am W...,Zahl der sozialversicherungspflichtig Beschäft...,9,svw,Es handelt sich um die Zahl der sozialversiche...,1997-2023,1997-2023
9,Arbeitslose,Zahl der Arbeitslosen insgesamt,10,alo,Es handelt sich um die Zahl der Arbeitslosen i...,1998-2023,1995-2023

In [9]:
search_terms = [
    "Arbeitslosenquote",
    "Bevölkerung",
    "Beschäftigte",
    "Erwerbstätige",
    "Bruttoinlandsprodukt",
    "Breitband",
    "Miete",
    "Wanderung",
    "wissensintensiv"
]

pattern = "|".join(search_terms)

indicator_candidates = valid_indicators[
    valid_indicators["Kurzname"].str.contains(
        pattern,
        case=False,
        na=False
    )
].copy()

print("Matching indicators:", len(indicator_candidates))

display(
    indicator_candidates[
        [
            "Kurzname",
            "M_ID",
            "Kürzel",
            "Gemeinden",
            "Kreise"
        ]
    ].head(100)
)

Matching indicators: 76

,Kurzname,M_ID,Kürzel,Gemeinden,Kreise
1,Bevölkerung gesamt,2,xbev,1995-2023,1995-2023
2,Bevölkerung männlich,3,xbevm,1995-2023,1995-2023
3,Bevölkerung weiblich,4,xbevf,1995-2023,1995-2023
4,Bevölkerung (mit BBSR-Zensuskorrekturen),5,bev_korr,1995-2023,1995-2023
5,Erwerbsfähige Bevölkerung (15 bis unter 65 Jahre),6,ewf_1565_ges,2001-2023,1995-2023
...,...,...,...,...,...
398,Bruttoinlandsprodukt je Erwerbstätigen,14206,q_bip_et,NaN,1992-2022
399,Bruttowertschöpfung je Erwerbstätigen,14207,q_bws_et,NaN,2000-2022
400,Bruttowertschöpfung je Erwerbstätigen Primärer...,14208,q_bws_1sektor,NaN,2000-2022
401,Bruttowertschöpfung je Erwerbstätigen Sekundär...,14209,q_bws_2sektor,NaN,2000-2022
402,Bruttowertschöpfung je Erwerbstätigen Tertiäre...,14210,q_bws_3sektor,NaN,2000-2022

In [10]:
def find_indicators(*terms):
    """
    Search INKAR indicators across the short name,
    full name, and notes columns.
    """
    searchable_columns = [
        "Kurzname",
        "Name",
        "Anmerkungen"
    ]

    pattern = "|".join(terms)

    mask = False

    for column in searchable_columns:
        mask = mask | valid_indicators[column].astype(str).str.contains(
            pattern,
            case=False,
            na=False,
            regex=True
        )

    results = valid_indicators.loc[
        mask,
        [
            "Kurzname",
            "Name",
            "M_ID",
            "Kürzel",
            "Gemeinden",
            "Kreise"
        ]
    ].drop_duplicates()

    return results.reset_index(drop=True)

In [11]:
required_candidates = find_indicators(
    "Arbeitslosenquote",
    "Beschäftigtenentwicklung",
    "Beschäftigte",
    "Erwerbstätige",
    "Bruttoinlandsprodukt",
    "Wanderungssaldo",
    "Breitband",
    "Miete",
    "Mietpreis",
    "wissensintensiv",
    "hochqualifiziert",
    "Bevölkerungsentwicklung"
)

print(
    required_candidates.to_string(
        index=False,
        columns=[
            "Kurzname",
            "M_ID",
            "Kürzel",
            "Gemeinden",
            "Kreise"
        ]
    )
)

                                                              Kurzname  M_ID                       Kürzel Gemeinden    Kreise
                                                         Erwerbstätige     7                       et1000       NaN 2000-2022
               Sozialversicherungspflichtig Beschäftigte am Arbeitsort     8                          sva 1997-2023 1997-2023
                  Sozialversicherungspflichtig Beschäftigte am Wohnort     9                          svw 1997-2023 1997-2023
                                     Bruttoinlandsprodukt in 1000 Euro    11                          bip       NaN 2000-2022
                                                     Arbeitslosenquote  1101                        q_alo       NaN 1998-2023
                                              Arbeitslosenquote Frauen  1102                      q_alo_f       NaN 2008-2023
                                              Arbeitslosenquote Männer  1103                      q_alo_m       NaN 2008-2023
                                           Arbeitslose ohne Ausbildung  1207                  a_alo_oAusb       NaN 2009-2023
                                              Arbeitslosenquote Ältere  1301                    q_alo_ü55       NaN 2008-2023
                                             Arbeitslosenquote Jüngere  1302                    q_alo_u25       NaN 2008-2023
                                             Anteil ältere Arbeitslose  1303                    a_alo_ü55 1998-2023 1998-2023
                                   Anteil weibliche ältere Arbeitslose  1304                  a_alo_ü55_f 1998-2023 1998-2023
                                   Anteil männliche ältere Arbeitslose  1305                  a_alo_ü55_m 1998-2023 1998-2023
                                            Anteil jüngere Arbeitslose  1306                    a_alo_u25 1998-2023 1995-2023
                                  Anteil weibliche jüngere Arbeitslose  1307                  a_alo_u25_f 1998-2023 1998-2023
                                  Anteil männliche jüngere Arbeitslose  1308                  a_alo_u25_m 1998-2023 1998-2023
                                                    Angebotsmietpreise  2113                     m_mietpr       NaN 2010-2024
                                                    Mehrfamilienhäuser  2202                   a_wg_wo3um 2011-2023 2011-2023
                                                    Beschäftigtenquote  3101                        q_svw 2001-2023 1997-2023
                                             Beschäftigtenquote Frauen  3102                      q_svw_f 2001-2023 1997-2023
                                             Beschäftigtenquote Männer  3103                      q_svw_m 2001-2023 1997-2023
                                          Beschäftigtenquote Ausländer  3104                   q_svw_ausl       NaN 2011-2023
                                            Quote jüngere Beschäftigte  3106                  q_svw_15u30       NaN 2010-2023
                                             Quote ältere Beschäftigte  3107                    q_svw_ü55       NaN 2005-2023
                                                  Teilzeitbeschäftigte  3108                     a_sva_tz       NaN 2012-2023
                                            Teilzeitbeschäftige Frauen  3109                   a_sva_tz_f       NaN 2012-2023
                                                          Erwerbsquote  3110                        q_ewp       NaN 1998-2023
                                                   Erwerbsquote Frauen  3111                      q_ewp_f       NaN 2008-2023
                                                   Erwerbsquote Männer  3112                      q_ewp_m       NaN 2008-2023
                                                  Selbstständigenquote  3113                     q_selbst       NaN 2000-2022
                   Beschäftigte am AO mit akademischem Berufsabschluss  3201                 a_sva_akadem       NaN 2012-2023
                                Beschäftigte am AO mit Berufsabschluss  3202             a_sva_mAbschluss       NaN 2012-2023
                               Beschäftigte am AO ohne Berufsabschluss  3203             a_sva_oAbschluss       NaN 2012-2023
                         Beschäftigte am WO mit akademischen Abschluss  3204                 a_svw_akadem       NaN 2012-2023
                                Beschäftigte am WO mit Berufsabschluss  3205             a_svw_mAbschluss       NaN 2012-2023
                               Beschäftigte am WO ohne Berufsabschluss  3206             a_svw_oAbschluss       NaN 2012-2023
                           Beschäftigte mit Anforderungsniveau Experte  3207                    a_sva_exp       NaN 2013-2023
                        Beschäftigte mit Anforderungsniveau Spezialist  3208                   a_sva_spez       NaN 2013-2023
                         Beschäftigte mit Anforderungsniveau Fachkraft  3209                   a_sva_fach       NaN 2013-2023
                            Beschäftigte mit Anforderungsniveau Helfer  3210                   a_sva_helf       NaN 2013-2023
                    Anteil Minijobs an den Beschäftigungsverhältnissen  3301                   a_Minijobs       NaN 2003-2023
   Anteil Minijobs (ausschließlich) an den Beschäftigungsverhältnissen  3302                a_gb_knj_prBv       NaN 2003-2023
   Anteil Minijobs (Nebenverdienst) an den Beschäftigungsverhältnissen  3303                 a_gb_nj_prBv       NaN 2003-2023
         Anteil Minijobs (ausschließlich) an geringfügig Beschäftigten  3304                     a_gb_knj       NaN 2003-2023
                                      Anteil Minijobs (Nebenverdienst)  3305                      a_gb_nj       NaN 2003-2023
                                              Anteil Minijobs (Frauen)  3306                  a_gb_Frauen       NaN 2003-2023
                                              Anteil Minijobs (Männer)  3307                  a_gb_Männer       NaN 2003-2023
                                                            Aufstocker  3308                a_Aufstockern       NaN 2007-2020
                                                          Kurzarbeiter  3309                        a_KuA       NaN 2007-2023
                           Geringfügig Beschäftigte 65 Jahre und älter  3310                     a_gb_ü65       NaN 2007-2023
                  Geringfügig Beschäftigte 65 Jahre und älter männlich  3311              a_gb_ü65_Männer       NaN 2007-2023
                  Geringfügig Beschäftigte 65 Jahre und älter weiblich  3312              a_gb_ü65_Frauen       NaN 2007-2023
                                              Unterbeschäftigungsquote  3313                         q_ub       NaN 2011-2023
                                           Beschäftigte Pimärer Sektor  3401                 a_svb_primär       NaN 2008-2023
                                        Beschäftigte Sekundärer Sektor  3402               a_svb_sekundär       NaN 2008-2023
                                         Beschäftigte Tertiärer Sektor  3403                a_svb_tertiär       NaN 2008-2023
                                                        Industriequote  3404                  q_industrie       NaN 2008-2023
                                                  Dienstleistungsquote  3405             q_dienstleistung       NaN 2008-2023
                                            Beschäftigte im Baugewerbe  3416                    a_svb_Bau       NaN 2008-2023
                Beschäftigte in unternehmensbezogenen Dienstleistungen  3406 a_svb_unternehmensdienstlstg       NaN 2009-2023
                                       Beschäftigte in Kreativbranchen  3407                a_svb_kreativ       NaN 2008-2023
                          Beschäftigte in wissensintensiven Industrien  3408                 a_svb_wissen       NaN 2009-2023
Beschäftigte in IT- und naturwissenschaftlichen Dienstleistungsberufen  3409                     a_svb_IT       NaN 2013-2023
                                              Beschäftigte im Handwerk  3410               a_svb_Handwerk       NaN 2010-2022
                                         Erwerbstätige Primärer Sektor  3411                 a_ewt_primär       NaN 2000-2022
                                       Erwerbstätige Sekundärer Sektor  3412               a_ewt_sekundär       NaN 2000-2022
                                        Erwerbstätige Tertiärer Sektor  3413                a_ewt_tertiär       NaN 2000-2022
              Anteil Erwerbstätige Verarbeitendes Gewerbe an Industrie  3414              a_WZC_Industrie       NaN 2000-2022
         Anteil Erwerbstätige Finanz- und Unternehmensdienstleistungen  3415        a_WZKN_Dienstleistung       NaN 2000-2022
                                    Bevölkerungsentwicklung (10 Jahre)  4217                      e10_bev       NaN 2005-2023
                                     Bevölkerungsentwicklung (5 Jahre)  4218                       e5_bev       NaN 2000-2023
                   Prognostizierte Bevölkerungsentwicklung (2022-2030)  4219              e_bev2230_rop45       NaN      2022
                   Prognostizierte Bevölkerungsentwicklung (2022-2035)  4220              e_bev2235_rop45       NaN      2022
                   Prognostizierte Bevölkerungsentwicklung (2022-2040)  4221              e_bev2240_rop45       NaN      2022
                   Prognostizierte Bevölkerungsentwicklung (2022-2045)  4222              e_bev2245_rop45       NaN      2022
                                                 Gesamtwanderungssaldo  4301                       i_wans 1995-2023 1995-2023
                                                  Außenwanderungssaldo  4302                     i_wans_a       NaN 1995-2023
                                           Außenwanderungssaldo Frauen  4303                   i_wans_a_f       NaN 2003-2023
                                           Außenwanderungssaldo Männer  4304                   i_wans_a_m       NaN 2003-2023
                                                 Binnenwanderungssaldo  4305                     i_wans_b       NaN 1995-2023
                                          Binnenwanderungssaldo Frauen  4306                   i_wans_b_f       NaN 2003-2023
                                          Binnenwanderungssaldo Männer  4307                   i_wans_b_m       NaN 2003-2023
                                                      Bildungswanderer  4308                i_wans_b_1825       NaN 1995-2023
                                            Weibliche Bildungswanderer  4309              i_wans_b_1825_f       NaN 2003-2023
                                            Männliche Bildungswanderer  4310              i_wans_b_1825_m       NaN 1995-2023
                                               Berufseinstiegswanderer  4311                i_wans_b_2530       NaN 1995-2023
                                     Weibliche Berufseinstiegswanderer  4312              i_wans_b_2530_f       NaN 2003-2023
                                     Männliche Berufseinstiegswanderer  4313              i_wans_b_2530_m       NaN 2003-2023
                                                    Ruhestandswanderer  4314                i_wans_b_65um       NaN 1995-2023
                                                      Familienwanderer  4315            i_wans_b_00183050       NaN 1995-2023
                                                       Erwerbswanderer  4316                i_wans_b_3050       NaN 1995-2023
                                                         Auszubildende  5105                      a_azubi       NaN 1995-2023
                                               Weibliche Auszubildende  5106                    a_azubi_w       NaN 1995-2023
                                               Männliche Auszubildende  5107                    a_azubi_m       NaN 1995-2023
                        Auszubildende je 100 Einwohner 15 bis 25 Jahre  5108                 q_azubi_1525       NaN 2010-2023
                                                           Studierende  5109                       q_stud       NaN 1995-2023
                                                     Studierende an FH  5110                    q_stud_fh       NaN 2006-2023
                                                 Weibliche Studierende  5111                     a_stud_w       NaN 1995-2023
                                                 Männliche Studierende  5112                     a_stud_m       NaN 1995-2023
                                              Ausländische Studierende  5113                     a_stud_a       NaN 1998-2023
                                            Studierende im 1. Semester  5114                     a_stud_1       NaN 1995-2023
                          Studierende je 100 Einwohner 18 bis 25 Jahre  5115                  q_stud_1825       NaN 1995-2023
                                                       Bruttoverdienst  6001            d_Bruttoverdienst       NaN 2000-2022
                             Bruttoverdienst im Produzierenden Gewerbe  6002       d_Bruttoverdienst_Prod       NaN 2000-2022
                                                       Medianeinkommen  6003                         m_ek       NaN 2014-2023
                                                Medianeinkommen Frauen  6004                       m_ek_f       NaN 2014-2023
                                                Medianeinkommen Männer  6005                       m_ek_m       NaN 2014-2023
                               Medianeinkommen 25 bis unter 55-Jährige  6006                    m_ek_2555       NaN 2014-2023
                               Medianeinkommen 55 bis unter 65-Jährige  6007                    m_ek_5565       NaN 2014-2023
                           Medianeinkommen anerkannter Berufsabschluss  6008                   m_ek_oakad       NaN 2014-2023
                          Medianeinkommen akademischer Berufsabschluss  6009                    m_ek_akad       NaN 2014-2023
                          Verdienstabstand zwischen Frauen und Männern  6010                      m_ek_fm       NaN 2014-2023
                                                        Arbeitsvolumen  6021                     d_ArbStd       NaN 2000-2022
                                                          Umsatzsteuer  9004                      q_umsst 1995-2021 1998-2023
                                                 Personal der Kommunen  9008                     q_gvvzaq       NaN 2006-2023
                                         Einwohner-Arbeitsplatz-Dichte 11005                 q_bevsva_qkm 1996-2023 1996-2023
                                                     Wohngeldhaushalte 12103                       a_HHwg       NaN 2013-2023
                                      Wohngeldhaushalte (Mietzuschuss) 12104                   a_WGmietzu       NaN 1995-2023
                                               Leistungen für Wohngeld 12309              d_Wohngeld_Lstg       NaN 2016-2023
                         Bandbreitenverfügbarkeit mindestens 50 Mbit/s 13116                 a_bb_50Mbits 2017-2023 2017-2023
                        Bandbreitenverfügbarkeit mindestens 100 Mbit/s 13117                a_bb_100Mbits 2017-2023 2017-2023
                      Bandbreitenverfügbarkeit mindestens 1.000 Mbit/s 13118               a_bb_1000Mbits 2020-2023 2020-2023
                                                            Einpendler 13301                   a_einp_sva 1997-2023 1997-2023
                                                            Auspendler 13302                   a_ausp_svw 1997-2023 1997-2023
                                                          Pendlersaldo 13303               q_pendlersaldo 1997-2023 1997-2023
                                 Pendler mit Arbeitsweg 50 km und mehr 13304                     a_pend50 2013-2023 2013-2023
                                Pendler mit Arbeitsweg 150 km und mehr 13305                    a_pend150 2013-2023 2013-2023
                                Pendler mit Arbeitsweg 300 km und mehr 13306                    a_pend300 2013-2023 2013-2023
                                                       Kleinstbetriebe 14201               a_betr_kleinst       NaN 2006-2023
                                                         Kleinbetriebe 14202                 a_betr_klein       NaN 2006-2023
                                                  Mittlere Unternehmen 14203                a_betr_mittel       NaN 2006-2023
                                                       Großunternehmen 14204                  a_betr_groß       NaN 2006-2023
                                     Bruttoinlandsprodukt je Einwohner 14205                     q_bip_ew       NaN 1992-2022
                                Bruttoinlandsprodukt je Erwerbstätigen 14206                     q_bip_et       NaN 1992-2022
                                 Bruttowertschöpfung je Erwerbstätigen 14207                     q_bws_et       NaN 2000-2022
                 Bruttowertschöpfung je Erwerbstätigen Primärer Sektor 14208                q_bws_1sektor       NaN 2000-2022
               Bruttowertschöpfung je Erwerbstätigen Sekundärer Sektor 14209                q_bws_2sektor       NaN 2000-2022
                Bruttowertschöpfung je Erwerbstätigen Tertiärer Sektor 14210                q_bws_3sektor       NaN 2000-2022
                            Anteil Bruttowertschöpfung Primärer Sektor 14211                a_bws_1sektor       NaN 2000-2022
                          Anteil Bruttowertschöpfung Sekundärer Sektor 14212                a_bws_2sektor       NaN 2000-2022
                           Anteil Bruttowertschöpfung Tertiärer Sektor 14213                a_bws_3sektor       NaN 2000-2022
                                                    Umsatz im Handwerk 14220               q_handw_umsatz       NaN 2010-2022

In [12]:
candidate_output_path = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "indicator_candidates.csv"
)

required_candidates.to_csv(
    candidate_output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved to:", candidate_output_path)
print("File exists:", candidate_output_path.exists())

Saved to: c:\Users\maazm\Desktop\Projects\datacareer-germany\data\processed\indicator_candidates.csv
File exists: True

In [13]:
SELECTED_CODES = {
    "xbev": "population",
    "q_alo": "unemployment_rate",
    "m_mietpr": "asking_rent",
    "q_svw": "employment_rate",
    "a_sva_exp": "expert_level_employment",
    "a_svb_wissen": "knowledge_intensive_industry",
    "a_svb_IT": "it_science_service_employment",
    "e10_bev": "population_change_10_years",
    "i_wans": "total_migration_balance",
    "m_ek_akad": "median_income_academic",
    "a_bb_100Mbits": "broadband_100mbit",
    "q_bip_ew": "gdp_per_capita"
}

selected_indicators = valid_indicators[
    valid_indicators["Kürzel"].isin(SELECTED_CODES.keys())
].copy()

selected_indicators["project_column"] = selected_indicators[
    "Kürzel"
].map(SELECTED_CODES)

selected_indicators = selected_indicators[
    [
        "project_column",
        "Kurzname",
        "M_ID",
        "Kürzel",
        "Gemeinden",
        "Kreise"
    ]
].sort_values("project_column").reset_index(drop=True)

display(selected_indicators)

,project_column,Kurzname,M_ID,Kürzel,Gemeinden,Kreise
0,asking_rent,Angebotsmietpreise,2113,m_mietpr,NaN,2010-2024
1,broadband_100mbit,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,13117,a_bb_100Mbits,2017-2023,2017-2023
2,employment_rate,Beschäftigtenquote,3101,q_svw,2001-2023,1997-2023
3,expert_level_employment,Beschäftigte mit Anforderungsniveau Experte,3207,a_sva_exp,NaN,2013-2023
4,gdp_per_capita,Bruttoinlandsprodukt je Einwohner,14205,q_bip_ew,NaN,1992-2022
5,it_science_service_employment,Beschäftigte in IT- und naturwissenschaftliche...,3409,a_svb_IT,NaN,2013-2023
6,knowledge_intensive_industry,Beschäftigte in wissensintensiven Industrien,3408,a_svb_wissen,NaN,2009-2023
7,median_income_academic,Medianeinkommen akademischer Berufsabschluss,6009,m_ek_akad,NaN,2014-2023
8,population,Bevölkerung gesamt,2,xbev,1995-2023,1995-2023
9,population_change_10_years,Bevölkerungsentwicklung (10 Jahre),4217,e10_bev,NaN,2005-2023
10,total_migration_balance,Gesamtwanderungssaldo,4301,i_wans,1995-2023,1995-2023
11,unemployment_rate,Arbeitslosenquote,1101,q_alo,NaN,1998-2023

In [14]:
found_codes = set(selected_indicators["Kürzel"])
missing_codes = set(SELECTED_CODES) - found_codes

print("Indicators selected:", len(selected_indicators))
print("Missing codes:", missing_codes)

Indicators selected: 12
Missing codes: set()

In [15]:
selected_indicator_path = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "selected_inkar_indicators.csv"
)

selected_indicators.to_csv(
    selected_indicator_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", selected_indicator_path)

Saved: c:\Users\maazm\Desktop\Projects\datacareer-germany\data\processed\selected_inkar_indicators.csv

In [16]:
import csv

with open(
    CSV_PATH,
    "r",
    encoding="utf-8-sig",
    errors="replace",
    newline=""
) as file:
    csv_sample_text = file.read(100_000)

dialect = csv.Sniffer().sniff(
    csv_sample_text,
    delimiters=";,\t|"
)

CSV_DELIMITER = dialect.delimiter

print("Detected delimiter:", repr(CSV_DELIMITER))

Detected delimiter: ';'

In [17]:
csv_preview = pd.read_csv(
    CSV_PATH,
    sep=CSV_DELIMITER,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig",
    encoding_errors="replace"
)

print("Number of columns:", len(csv_preview.columns))

print("\nColumn names:")
for column in csv_preview.columns:
    print("-", column)

display(csv_preview)

Number of columns: 9

Column names:
- Bereich
- ID
- Kuerzel
- Indikator
- Raumbezug
- Kennziffer
- Name
- Zeitbezug
- Wert

,Bereich,ID,Kuerzel,Indikator,Raumbezug,Kennziffer,Name,Zeitbezug,Wert
0,EU,18668,q_alo,Arbeitslosenquote,EU27,EU27,Europäische Union - 27 Länder (ab 2020),2021,"7,00"
1,EU,18668,q_alo,Arbeitslosenquote,NUTS0,AT,Österreich,2021,"6,20"
2,EU,18668,q_alo,Arbeitslosenquote,NUTS0,BE,Belgien,2021,"6,30"
3,EU,18668,q_alo,Arbeitslosenquote,NUTS0,BG,Bulgarien,2021,"5,30"
4,EU,18668,q_alo,Arbeitslosenquote,NUTS0,CY,Zypern,2021,"7,50"

In [18]:
DUCKDB_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "datacareer_germany.duckdb"
)

connection = duckdb.connect(str(DUCKDB_PATH))

print("DuckDB database:", DUCKDB_PATH)

DuckDB database: c:\Users\maazm\Desktop\Projects\datacareer-germany\data\processed\datacareer_germany.duckdb

In [19]:
# Convert the Windows path into a format DuckDB can read
csv_sql_path = CSV_PATH.as_posix().replace("'", "''")

connection.execute(f"""
    CREATE OR REPLACE VIEW inkar_raw AS
    SELECT *
    FROM read_csv_auto(
        '{csv_sql_path}',
        delim=';',
        header=True,
        all_varchar=True
    )
""")

print("INKAR CSV view created successfully.")

INKAR CSV view created successfully.

In [20]:
test_rows = connection.execute("""
    SELECT *
    FROM inkar_raw
    LIMIT 5
""").df()

display(test_rows)

,Bereich,ID,Kuerzel,Indikator,Raumbezug,Kennziffer,Name,Zeitbezug,Wert
0,EU,18668,q_alo,Arbeitslosenquote,EU27,EU27,Europäische Union - 27 Länder (ab 2020),2021,"7,00"
1,EU,18668,q_alo,Arbeitslosenquote,NUTS0,AT,Österreich,2021,"6,20"
2,EU,18668,q_alo,Arbeitslosenquote,NUTS0,BE,Belgien,2021,"6,30"
3,EU,18668,q_alo,Arbeitslosenquote,NUTS0,BG,Bulgarien,2021,"5,30"
4,EU,18668,q_alo,Arbeitslosenquote,NUTS0,CY,Zypern,2021,"7,50"

In [21]:
selected_codes_sql = ", ".join(
    f"'{code}'"
    for code in SELECTED_CODES.keys()
)

geo_summary_query = f"""
    SELECT
        Bereich,
        Raumbezug,
        COUNT(*) AS row_count,
        COUNT(DISTINCT Kennziffer) AS number_of_regions,
        MIN(TRY_CAST(Zeitbezug AS INTEGER)) AS earliest_year,
        MAX(TRY_CAST(Zeitbezug AS INTEGER)) AS latest_year
    FROM inkar_raw
    WHERE Kuerzel IN ({selected_codes_sql})
    GROUP BY
        Bereich,
        Raumbezug
    ORDER BY
        Bereich,
        Raumbezug
"""

geo_summary = connection.execute(
    geo_summary_query
).df()

display(geo_summary)

,Bereich,Raumbezug,row_count,number_of_regions,earliest_year,latest_year
0,EU,EU27,2,1,2021,2021
1,EU,NUTS0,54,27,2021,2021
2,EU,NUTS1,183,92,2021,2021
3,EU,NUTS2,480,242,2021,2021
4,LRB,Arbeitsmarktregionen,49042,223,1995,2023
...,...,...,...,...,...,...
79,ZOM,Zentralörtliche Einstufung (zusammengefasst),48,4,2017,2023
80,ZOM,Zentralörtliche Funktion - Grundzentrum,30168,2514,2017,2023
81,ZOM,Zentralörtliche Funktion - Mittelzentrum,11532,961,2017,2023
82,ZOM,Zentralörtliche Funktion - Oberzentrum,1836,153,2017,2023
83,ZOM,Zentralörtliche Funktion - keine,87586,7354,2017,2023

In [22]:
state_level_candidates = geo_summary[
    geo_summary["number_of_regions"].between(15, 17)
].copy()

display(state_level_candidates)

,Bereich,Raumbezug,row_count,number_of_regions,earliest_year,latest_year
8,LRB,Bundesländer,3760,16,1995,2024
16,LRB,Metropolregionen,3300,15,1995,2023
21,LRB,Regionalstatistischer Raumtyp 17 (RegioStaR17),1785,17,1995,2023
43,SDG,Bundesländer,1200,16,1995,2024
51,SDG,Metropolregionen,900,15,1995,2023
56,SDG,Regionalstatistischer Raumtyp 17 (RegioStaR17),476,17,2001,2023
75,ZOM,Bundesländer,192,16,2017,2023

In [23]:
state_raw_query = f"""
    SELECT
        Bereich,
        ID,
        Kuerzel,
        Indikator,
        Raumbezug,
        Kennziffer,
        Name,
        Zeitbezug,
        Wert
    FROM inkar_raw
    WHERE Bereich = 'LRB'
      AND Raumbezug = 'Bundesländer'
      AND Kuerzel IN ({selected_codes_sql})
    ORDER BY
        Kennziffer,
        Kuerzel,
        TRY_CAST(Zeitbezug AS INTEGER)
"""

state_raw = connection.execute(state_raw_query).df()

print("Shape:", state_raw.shape)
print("Number of states:", state_raw["Kennziffer"].nunique())
print("Number of indicators:", state_raw["Kuerzel"].nunique())

display(state_raw.head(20))

Shape: (3760, 9)
Number of states: 16
Number of indicators: 12

,Bereich,ID,Kuerzel,Indikator,Raumbezug,Kennziffer,Name,Zeitbezug,Wert
0,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2017,"75,61"
1,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2020,"89,94"
2,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2021,"90,31"
3,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2022,"92,83"
4,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2023,"95,32"
5,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2013,"9,58"
6,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2014,"9,66"
7,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2015,"9,81"
8,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2016,"10,07"
9,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2017,"10,20"
10,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2018,"10,32"
11,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2019,"10,50"
12,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2020,"10,71"
13,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2021,"10,90"
14,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2022,"11,13"
15,LRB,17524,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,Bundesländer,01,Schleswig-Holstein,2023,"10,86"
16,LRB,17806,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,Bundesländer,01,Schleswig-Holstein,2013,"2,53"
17,LRB,17806,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,Bundesländer,01,Schleswig-Holstein,2014,"2,58"
18,LRB,17806,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,Bundesländer,01,Schleswig-Holstein,2015,"2,61"
19,LRB,17806,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,Bundesländer,01,Schleswig-Holstein,2016,"2,67"

In [24]:
state_names = (
    state_raw[
        ["Kennziffer", "Name"]
    ]
    .drop_duplicates()
    .sort_values("Kennziffer")
    .reset_index(drop=True)
)

print(state_names.to_string(index=False))

Kennziffer                   Name
        01     Schleswig-Holstein
        02                Hamburg
        03          Niedersachsen
        04                 Bremen
        05    Nordrhein-Westfalen
        06                 Hessen
        07        Rheinland-Pfalz
        08      Baden-Württemberg
        09                 Bayern
        10               Saarland
        11                 Berlin
        12            Brandenburg
        13 Mecklenburg-Vorpommern
        14                Sachsen
        15         Sachsen-Anhalt
        16              Thüringen

In [25]:
extracted_indicator_check = (
    state_raw[
        ["Kuerzel", "Indikator"]
    ]
    .drop_duplicates()
    .sort_values("Kuerzel")
    .reset_index(drop=True)
)

print(extracted_indicator_check.to_string(index=False))

      Kuerzel                                                              Indikator
a_bb_100Mbits                         Bandbreitenverfügbarkeit mindestens 100 Mbit/s
    a_sva_exp                            Beschäftigte mit Anforderungsniveau Experte
     a_svb_IT Beschäftigte in IT- und naturwissenschaftlichen Dienstleistungsberufen
 a_svb_wissen                           Beschäftigte in wissensintensiven Industrien
      e10_bev                                     Bevölkerungsentwicklung (10 Jahre)
       i_wans                                                  Gesamtwanderungssaldo
    m_ek_akad                           Medianeinkommen akademischer Berufsabschluss
     m_mietpr                                                     Angebotsmietpreise
        q_alo                                                      Arbeitslosenquote
     q_bip_ew                                      Bruttoinlandsprodukt je Einwohner
        q_svw                                                     Beschäftigtenquote
         xbev                                                     Bevölkerung gesamt

In [26]:
missing_after_extraction = (
    set(SELECTED_CODES)
    - set(state_raw["Kuerzel"].unique())
)

print("Missing indicators:", missing_after_extraction)

Missing indicators: set()

In [27]:
RAW_STATE_CSV_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inkar_bundeslaender_raw.csv"
)

RAW_STATE_PARQUET_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inkar_bundeslaender_raw.parquet"
)

state_raw.to_csv(
    RAW_STATE_CSV_PATH,
    index=False,
    encoding="utf-8-sig"
)

state_raw.to_parquet(
    RAW_STATE_PARQUET_PATH,
    index=False
)

print("CSV saved:", RAW_STATE_CSV_PATH)
print("Parquet saved:", RAW_STATE_PARQUET_PATH)
print("CSV exists:", RAW_STATE_CSV_PATH.exists())
print("Parquet exists:", RAW_STATE_PARQUET_PATH.exists())

CSV saved: c:\Users\maazm\Desktop\Projects\datacareer-germany\data\processed\inkar_bundeslaender_raw.csv
Parquet saved: c:\Users\maazm\Desktop\Projects\datacareer-germany\data\processed\inkar_bundeslaender_raw.parquet
CSV exists: True
Parquet exists: True

In [28]:
print("Sample values:")
print(state_raw["Wert"].dropna().drop_duplicates().head(30).tolist())

Sample values:
['75,61', '89,94', '90,31', '92,83', '95,32', '9,58', '9,66', '9,81', '10,07', '10,20', '10,32', '10,50', '10,71', '10,90', '11,13', '10,86', '2,53', '2,58', '2,61', '2,67', '2,70', '2,73', '2,82', '2,91', '3,00', '3,09', '3,23', '7,40', '7,28', '7,06']

In [29]:
non_numeric_values = state_raw[
    ~state_raw["Wert"]
    .fillna("")
    .str.strip()
    .str.match(r"^-?\d+([,.]\d+)?$")
]["Wert"].value_counts(dropna=False)

display(non_numeric_values.head(20))

Series([], Name: count, dtype: int64)

In [30]:
state_clean = state_raw.copy()

state_clean = state_clean.rename(
    columns={
        "Kennziffer": "state_code",
        "Name": "state_name",
        "Zeitbezug": "year",
        "Wert": "value",
        "Kuerzel": "indicator_code",
        "Indikator": "indicator_name"
    }
)

# Preserve leading zeros in German state codes
state_clean["state_code"] = (
    state_clean["state_code"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

# Convert year to an integer
state_clean["year"] = pd.to_numeric(
    state_clean["year"],
    errors="coerce"
).astype("Int64")

# Convert German numeric format: 7,50 -> 7.50
state_clean["value"] = (
    state_clean["value"]
    .astype(str)
    .str.strip()
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
)

state_clean["value"] = pd.to_numeric(
    state_clean["value"],
    errors="coerce"
)

# Add our professional English metric names
state_clean["metric"] = state_clean[
    "indicator_code"
].map(SELECTED_CODES)

state_clean = state_clean[
    [
        "state_code",
        "state_name",
        "year",
        "indicator_code",
        "indicator_name",
        "metric",
        "value"
    ]
].copy()

display(state_clean.head(20))

,state_code,state_name,year,indicator_code,indicator_name,metric,value
0,01,Schleswig-Holstein,2017,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,broadband_100mbit,75.61
1,01,Schleswig-Holstein,2020,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,broadband_100mbit,89.94
2,01,Schleswig-Holstein,2021,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,broadband_100mbit,90.31
3,01,Schleswig-Holstein,2022,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,broadband_100mbit,92.83
4,01,Schleswig-Holstein,2023,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,broadband_100mbit,95.32
5,01,Schleswig-Holstein,2013,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,9.58
6,01,Schleswig-Holstein,2014,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,9.66
7,01,Schleswig-Holstein,2015,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,9.81
8,01,Schleswig-Holstein,2016,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,10.07
9,01,Schleswig-Holstein,2017,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,10.20
10,01,Schleswig-Holstein,2018,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,10.32
11,01,Schleswig-Holstein,2019,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,10.50
12,01,Schleswig-Holstein,2020,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,10.71
13,01,Schleswig-Holstein,2021,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,10.90
14,01,Schleswig-Holstein,2022,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,11.13
15,01,Schleswig-Holstein,2023,a_sva_exp,Beschäftigte mit Anforderungsniveau Experte,expert_level_employment,10.86
16,01,Schleswig-Holstein,2013,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,it_science_service_employment,2.53
17,01,Schleswig-Holstein,2014,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,it_science_service_employment,2.58
18,01,Schleswig-Holstein,2015,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,it_science_service_employment,2.61
19,01,Schleswig-Holstein,2016,a_svb_IT,Beschäftigte in IT- und naturwissenschaftliche...,it_science_service_employment,2.67

In [31]:
print("Cleaned shape:", state_clean.shape)
print("Number of states:", state_clean["state_code"].nunique())
print("Number of metrics:", state_clean["metric"].nunique())
print("Earliest year:", state_clean["year"].min())
print("Latest year:", state_clean["year"].max())

print("\nMissing values:")
print(
    state_clean[
        [
            "state_code",
            "state_name",
            "year",
            "metric",
            "value"
        ]
    ].isna().sum()
)

print("\nData types:")
print(state_clean.dtypes)

Cleaned shape: (3760, 7)
Number of states: 16
Number of metrics: 12
Earliest year: 1995
Latest year: 2024

Missing values:
state_code    0
state_name    0
year          0
metric        0
value         0
dtype: int64

Data types:
state_code            str
state_name            str
year                Int64
indicator_code        str
indicator_name        str
metric                str
value             float64
dtype: object

In [32]:
duplicate_mask = state_clean.duplicated(
    subset=[
        "state_code",
        "year",
        "metric"
    ],
    keep=False
)

duplicate_rows = state_clean[
    duplicate_mask
].sort_values(
    [
        "state_code",
        "year",
        "metric"
    ]
)

print("Number of duplicate rows:", len(duplicate_rows))

display(duplicate_rows.head(20))

Number of duplicate rows: 0

Empty DataFrame
Columns: [state_code, state_name, year, indicator_code, indicator_name, metric, value]
Index: []

In [33]:
if len(duplicate_rows) > 0:
    raise ValueError(
        "Duplicate state-year-metric observations found. "
        "Inspect duplicate_rows before continuing."
    )

print("Duplicate check passed.")

Duplicate check passed.

In [34]:
state_year = (
    state_clean
    .pivot(
        index=[
            "state_code",
            "state_name",
            "year"
        ],
        columns="metric",
        values="value"
    )
    .reset_index()
)

state_year.columns.name = None

metric_columns = list(SELECTED_CODES.values())

state_year = state_year[
    [
        "state_code",
        "state_name",
        "year",
        *metric_columns
    ]
].sort_values(
    [
        "state_code",
        "year"
    ]
).reset_index(drop=True)

print("Wide dataset shape:", state_year.shape)
print("Number of states:", state_year["state_code"].nunique())
print("Years:", state_year["year"].min(), "to", state_year["year"].max())

display(state_year.head(20))

Wide dataset shape: (480, 15)
Number of states: 16
Years: 1995 to 2024

,state_code,state_name,year,population,unemployment_rate,asking_rent,employment_rate,expert_level_employment,knowledge_intensive_industry,it_science_service_employment,population_change_10_years,total_migration_balance,median_income_academic,broadband_100mbit,gdp_per_capita
0,01,Schleswig-Holstein,1995,2725461.0,NaN,NaN,NaN,NaN,NaN,NaN,4.26,7.68,NaN,NaN,21.18
1,01,Schleswig-Holstein,1996,2742293.0,NaN,NaN,NaN,NaN,NaN,NaN,4.96,7.07,NaN,NaN,21.42
2,01,Schleswig-Holstein,1997,2756473.0,NaN,NaN,47.20,NaN,NaN,NaN,5.49,5.58,NaN,NaN,21.80
3,01,Schleswig-Holstein,1998,2766057.0,9.97,NaN,46.76,NaN,NaN,NaN,7.86,4.30,NaN,NaN,22.03
4,01,Schleswig-Holstein,1999,2777275.0,9.39,NaN,47.51,NaN,NaN,NaN,7.04,5.03,NaN,NaN,22.18
5,01,Schleswig-Holstein,2000,2789761.0,8.51,NaN,48.03,NaN,NaN,NaN,6.23,5.52,NaN,NaN,22.85
6,01,Schleswig-Holstein,2001,2804249.0,8.45,NaN,47.91,NaN,NaN,NaN,5.88,6.59,NaN,NaN,23.41
7,01,Schleswig-Holstein,2002,2816507.0,8.71,NaN,47.63,NaN,NaN,NaN,5.11,6.12,NaN,NaN,23.00
8,01,Schleswig-Holstein,2003,2823171.0,9.71,NaN,46.63,NaN,NaN,NaN,4.76,4.60,NaN,NaN,23.19
9,01,Schleswig-Holstein,2004,2828760.0,9.84,NaN,46.06,NaN,NaN,NaN,4.44,3.94,NaN,NaN,23.65
10,01,Schleswig-Holstein,2005,2832950.0,11.56,NaN,45.83,NaN,NaN,NaN,3.94,3.79,NaN,NaN,23.75
11,01,Schleswig-Holstein,2006,2834254.0,9.97,NaN,46.62,NaN,NaN,NaN,3.35,2.96,NaN,NaN,24.47
12,01,Schleswig-Holstein,2007,2837373.0,8.45,NaN,47.53,NaN,NaN,NaN,2.93,3.61,NaN,NaN,25.04
13,01,Schleswig-Holstein,2008,2834260.0,7.59,NaN,48.73,NaN,NaN,NaN,2.47,1.78,NaN,NaN,25.86
14,01,Schleswig-Holstein,2009,2832027.0,7.79,NaN,49.23,NaN,7.40,NaN,1.97,2.43,NaN,NaN,25.17
15,01,Schleswig-Holstein,2010,2834259.0,7.51,6.0,49.70,NaN,7.28,NaN,1.60,3.82,NaN,NaN,25.73
16,01,Schleswig-Holstein,2011,2802266.0,7.24,6.0,51.41,NaN,7.06,NaN,-0.07,4.64,NaN,NaN,27.10
17,01,Schleswig-Holstein,2012,2806531.0,6.92,6.0,52.38,NaN,7.07,NaN,-0.35,4.68,NaN,NaN,28.07
18,01,Schleswig-Holstein,2013,2815955.0,6.92,6.0,53.67,9.58,6.10,2.53,-0.26,6.42,NaN,NaN,28.41
19,01,Schleswig-Holstein,2014,2830864.0,6.78,7.0,54.47,9.66,6.05,2.58,0.07,8.05,4642.69,NaN,29.27

In [35]:
metric_coverage = pd.DataFrame(
    {
        "non_missing_rows": state_year[
            metric_columns
        ].notna().sum(),

        "missing_rows": state_year[
            metric_columns
        ].isna().sum(),

        "first_year": [
            state_year.loc[
                state_year[column].notna(),
                "year"
            ].min()
            for column in metric_columns
        ],

        "latest_year": [
            state_year.loc[
                state_year[column].notna(),
                "year"
            ].max()
            for column in metric_columns
        ]
    }
).reset_index(
    names="metric"
)

display(metric_coverage)

,metric,non_missing_rows,missing_rows,first_year,latest_year
0,population,464,16,1995,2023
1,unemployment_rate,416,64,1998,2023
2,asking_rent,240,240,2010,2024
3,employment_rate,432,48,1997,2023
4,expert_level_employment,176,304,2013,2023
5,knowledge_intensive_industry,240,240,2009,2023
6,it_science_service_employment,176,304,2013,2023
7,population_change_10_years,464,16,1995,2023
8,total_migration_balance,464,16,1995,2023
9,median_income_academic,160,320,2014,2023
10,broadband_100mbit,80,400,2017,2023
11,gdp_per_capita,448,32,1995,2022

In [36]:
CLEAN_LONG_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inkar_bundeslaender_clean_long.parquet"
)

STATE_YEAR_CSV_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "germany_state_year.csv"
)

STATE_YEAR_PARQUET_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "germany_state_year.parquet"
)

state_clean.to_parquet(
    CLEAN_LONG_PATH,
    index=False
)

state_year.to_csv(
    STATE_YEAR_CSV_PATH,
    index=False,
    encoding="utf-8-sig"
)

state_year.to_parquet(
    STATE_YEAR_PARQUET_PATH,
    index=False
)

print("Long dataset saved:", CLEAN_LONG_PATH.exists())
print("Wide CSV saved:", STATE_YEAR_CSV_PATH.exists())
print("Wide Parquet saved:", STATE_YEAR_PARQUET_PATH.exists())

Long dataset saved: True
Wide CSV saved: True
Wide Parquet saved: True

In [37]:
connection.close()
print("DuckDB connection closed.")

DuckDB connection closed.

In [38]:
from pathlib import Path

import pandas as pd

# Detect the project root
CURRENT_PATH = Path.cwd()

if CURRENT_PATH.name == "notebooks":
    PROJECT_ROOT = CURRENT_PATH.parent
else:
    PROJECT_ROOT = CURRENT_PATH

RAW_STATE_PARQUET_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inkar_bundeslaender_raw.parquet"
)

RAW_STATE_CSV_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inkar_bundeslaender_raw.csv"
)

# Load the smaller extract rather than scanning the 6.7 GB CSV again
if RAW_STATE_PARQUET_PATH.exists():
    state_raw = pd.read_parquet(RAW_STATE_PARQUET_PATH)
    loaded_from = RAW_STATE_PARQUET_PATH

elif RAW_STATE_CSV_PATH.exists():
    state_raw = pd.read_csv(
        RAW_STATE_CSV_PATH,
        dtype=str,
        encoding="utf-8-sig"
    )
    loaded_from = RAW_STATE_CSV_PATH

else:
    raise FileNotFoundError(
        "The Bundesländer extract was not found. "
        "Check the data/processed folder."
    )

print("Loaded from:", loaded_from)
print("Shape:", state_raw.shape)
print("States:", state_raw["Kennziffer"].nunique())
print("Indicators:", state_raw["Kuerzel"].nunique())

display(state_raw.head())

Loaded from: c:\Users\maazm\Desktop\Projects\datacareer-germany\data\processed\inkar_bundeslaender_raw.parquet
Shape: (3760, 9)
States: 16
Indicators: 12

,Bereich,ID,Kuerzel,Indikator,Raumbezug,Kennziffer,Name,Zeitbezug,Wert
0,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2017,"75,61"
1,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2020,"89,94"
2,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2021,"90,31"
3,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2022,"92,83"
4,LRB,17274,a_bb_100Mbits,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Bundesländer,01,Schleswig-Holstein,2023,"95,32"

In [39]:
SELECTED_CODES = {
    "xbev": "population",
    "q_alo": "unemployment_rate",
    "m_mietpr": "asking_rent",
    "q_svw": "employment_rate",
    "a_sva_exp": "expert_level_employment",
    "a_svb_wissen": "knowledge_intensive_industry",
    "a_svb_IT": "it_science_service_employment",
    "e10_bev": "population_change_10_years",
    "i_wans": "total_migration_balance",
    "m_ek_akad": "median_income_academic",
    "a_bb_100Mbits": "broadband_100mbit",
    "q_bip_ew": "gdp_per_capita"
}

print("Selected metrics:", len(SELECTED_CODES))

Selected metrics: 12

In [40]:
print("Cleaned shape:", state_clean.shape)
print("Number of states:", state_clean["state_code"].nunique())
print("Number of metrics:", state_clean["metric"].nunique())
print("Year range:", state_clean["year"].min(), "to", state_clean["year"].max())

print("\nMissing values:")
print(
    state_clean[
        [
            "state_code",
            "state_name",
            "year",
            "indicator_code",
            "metric",
            "value"
        ]
    ].isna().sum()
)

print("\nData types:")
print(state_clean.dtypes)

Cleaned shape: (3760, 7)
Number of states: 16
Number of metrics: 12
Year range: 1995 to 2024

Missing values:
state_code        0
state_name        0
year              0
indicator_code    0
metric            0
value             0
dtype: int64

Data types:
state_code            str
state_name            str
year                Int64
indicator_code        str
indicator_name        str
metric                str
value             float64
dtype: object

In [41]:
duplicate_rows = state_clean[
    state_clean.duplicated(
        subset=[
            "state_code",
            "year",
            "metric"
        ],
        keep=False
    )
].sort_values(
    [
        "state_code",
        "year",
        "metric"
    ]
)

print("Number of duplicate rows:", len(duplicate_rows))

display(duplicate_rows.head(20))

Number of duplicate rows: 0

Empty DataFrame
Columns: [state_code, state_name, year, indicator_code, indicator_name, metric, value]
Index: []

In [42]:
if not duplicate_rows.empty:
    raise ValueError(
        "Duplicate state-year-metric observations were found."
    )

print("Duplicate validation passed.")

Duplicate validation passed.

In [43]:
metric_columns = list(SELECTED_CODES.values())

state_year = (
    state_clean
    .pivot(
        index=[
            "state_code",
            "state_name",
            "year"
        ],
        columns="metric",
        values="value"
    )
    .reset_index()
)

# Remove the label attached to the columns after pivoting
state_year.columns.name = None

# Arrange columns in a consistent order
state_year = state_year[
    [
        "state_code",
        "state_name",
        "year",
        *metric_columns
    ]
].sort_values(
    [
        "state_code",
        "year"
    ]
).reset_index(drop=True)

print("Wide dataset shape:", state_year.shape)
print("Number of states:", state_year["state_code"].nunique())
print("Year range:", state_year["year"].min(), "to", state_year["year"].max())

display(state_year.head(20))

Wide dataset shape: (480, 15)
Number of states: 16
Year range: 1995 to 2024

,state_code,state_name,year,population,unemployment_rate,asking_rent,employment_rate,expert_level_employment,knowledge_intensive_industry,it_science_service_employment,population_change_10_years,total_migration_balance,median_income_academic,broadband_100mbit,gdp_per_capita
0,01,Schleswig-Holstein,1995,2725461.0,NaN,NaN,NaN,NaN,NaN,NaN,4.26,7.68,NaN,NaN,21.18
1,01,Schleswig-Holstein,1996,2742293.0,NaN,NaN,NaN,NaN,NaN,NaN,4.96,7.07,NaN,NaN,21.42
2,01,Schleswig-Holstein,1997,2756473.0,NaN,NaN,47.20,NaN,NaN,NaN,5.49,5.58,NaN,NaN,21.80
3,01,Schleswig-Holstein,1998,2766057.0,9.97,NaN,46.76,NaN,NaN,NaN,7.86,4.30,NaN,NaN,22.03
4,01,Schleswig-Holstein,1999,2777275.0,9.39,NaN,47.51,NaN,NaN,NaN,7.04,5.03,NaN,NaN,22.18
5,01,Schleswig-Holstein,2000,2789761.0,8.51,NaN,48.03,NaN,NaN,NaN,6.23,5.52,NaN,NaN,22.85
6,01,Schleswig-Holstein,2001,2804249.0,8.45,NaN,47.91,NaN,NaN,NaN,5.88,6.59,NaN,NaN,23.41
7,01,Schleswig-Holstein,2002,2816507.0,8.71,NaN,47.63,NaN,NaN,NaN,5.11,6.12,NaN,NaN,23.00
8,01,Schleswig-Holstein,2003,2823171.0,9.71,NaN,46.63,NaN,NaN,NaN,4.76,4.60,NaN,NaN,23.19
9,01,Schleswig-Holstein,2004,2828760.0,9.84,NaN,46.06,NaN,NaN,NaN,4.44,3.94,NaN,NaN,23.65
10,01,Schleswig-Holstein,2005,2832950.0,11.56,NaN,45.83,NaN,NaN,NaN,3.94,3.79,NaN,NaN,23.75
11,01,Schleswig-Holstein,2006,2834254.0,9.97,NaN,46.62,NaN,NaN,NaN,3.35,2.96,NaN,NaN,24.47
12,01,Schleswig-Holstein,2007,2837373.0,8.45,NaN,47.53,NaN,NaN,NaN,2.93,3.61,NaN,NaN,25.04
13,01,Schleswig-Holstein,2008,2834260.0,7.59,NaN,48.73,NaN,NaN,NaN,2.47,1.78,NaN,NaN,25.86
14,01,Schleswig-Holstein,2009,2832027.0,7.79,NaN,49.23,NaN,7.40,NaN,1.97,2.43,NaN,NaN,25.17
15,01,Schleswig-Holstein,2010,2834259.0,7.51,6.0,49.70,NaN,7.28,NaN,1.60,3.82,NaN,NaN,25.73
16,01,Schleswig-Holstein,2011,2802266.0,7.24,6.0,51.41,NaN,7.06,NaN,-0.07,4.64,NaN,NaN,27.10
17,01,Schleswig-Holstein,2012,2806531.0,6.92,6.0,52.38,NaN,7.07,NaN,-0.35,4.68,NaN,NaN,28.07
18,01,Schleswig-Holstein,2013,2815955.0,6.92,6.0,53.67,9.58,6.10,2.53,-0.26,6.42,NaN,NaN,28.41
19,01,Schleswig-Holstein,2014,2830864.0,6.78,7.0,54.47,9.66,6.05,2.58,0.07,8.05,4642.69,NaN,29.27

In [44]:
print("Number of columns:", len(state_year.columns))

print("\nColumns:")
for column in state_year.columns:
    print("-", column)

Number of columns: 15

Columns:
- state_code
- state_name
- year
- population
- unemployment_rate
- asking_rent
- employment_rate
- expert_level_employment
- knowledge_intensive_industry
- it_science_service_employment
- population_change_10_years
- total_migration_balance
- median_income_academic
- broadband_100mbit
- gdp_per_capita

In [45]:
coverage_rows = []

for metric in metric_columns:
    available = state_year[state_year[metric].notna()]

    coverage_rows.append(
        {
            "metric": metric,
            "non_missing_rows": state_year[metric].notna().sum(),
            "missing_rows": state_year[metric].isna().sum(),
            "first_year": available["year"].min(),
            "latest_year": available["year"].max(),
            "states_in_latest_year": (
                available[
                    available["year"] == available["year"].max()
                ]["state_code"].nunique()
            )
        }
    )

metric_coverage = pd.DataFrame(coverage_rows)

display(metric_coverage)

,metric,non_missing_rows,missing_rows,first_year,latest_year,states_in_latest_year
0,population,464,16,1995,2023,16
1,unemployment_rate,416,64,1998,2023,16
2,asking_rent,240,240,2010,2024,16
3,employment_rate,432,48,1997,2023,16
4,expert_level_employment,176,304,2013,2023,16
5,knowledge_intensive_industry,240,240,2009,2023,16
6,it_science_service_employment,176,304,2013,2023,16
7,population_change_10_years,464,16,1995,2023,16
8,total_migration_balance,464,16,1995,2023,16
9,median_income_academic,160,320,2014,2023,16
10,broadband_100mbit,80,400,2017,2023,16
11,gdp_per_capita,448,32,1995,2022,16

In [47]:
CLEAN_LONG_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inkar_bundeslaender_clean_long.parquet"
)

STATE_YEAR_CSV_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "germany_state_year.csv"
)

STATE_YEAR_PARQUET_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "germany_state_year.parquet"
)

state_clean.to_parquet(
    CLEAN_LONG_PATH,
    index=False
)

state_year.to_csv(
    STATE_YEAR_CSV_PATH,
    index=False,
    encoding="utf-8-sig"
)

state_year.to_parquet(
    STATE_YEAR_PARQUET_PATH,
    index=False
)

print("Clean long file:", CLEAN_LONG_PATH.exists())
print("State-year CSV:", STATE_YEAR_CSV_PATH.exists())
print("State-year Parquet:", STATE_YEAR_PARQUET_PATH.exists())

Clean long file: True
State-year CSV: True
State-year Parquet: True

In [48]:
COMMON_START_YEAR = 2017
COMMON_END_YEAR = 2022
SNAPSHOT_YEAR = 2022

state_year_common = state_year[
    state_year["year"].between(
        COMMON_START_YEAR,
        COMMON_END_YEAR
    )
].copy()

print(
    "Common analysis period:",
    state_year_common["year"].min(),
    "to",
    state_year_common["year"].max()
)

print("Rows:", len(state_year_common))
print("States:", state_year_common["state_code"].nunique())
print("Years:", state_year_common["year"].nunique())

Common analysis period: 2017 to 2022
Rows: 96
States: 16
Years: 6

In [52]:
common_period_missing = (
    state_year_common[
        metric_columns
    ]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print("Missing observations during the common period:")
print(common_period_missing)

Missing observations during the common period:
broadband_100mbit                32
population                        0
asking_rent                       0
unemployment_rate                 0
employment_rate                   0
expert_level_employment           0
it_science_service_employment     0
knowledge_intensive_industry      0
population_change_10_years        0
total_migration_balance           0
median_income_academic            0
gdp_per_capita                    0
dtype: int64

In [55]:
print(common_period_missing[common_period_missing > 0])

broadband_100mbit    32
dtype: int64

In [56]:
broadband_year_coverage = (
    state_year
    .groupby("year")["broadband_100mbit"]
    .agg(
        available_states="count",
        missing_states=lambda series: series.isna().sum()
    )
    .reset_index()
)

broadband_year_coverage = broadband_year_coverage[
    broadband_year_coverage["available_states"] > 0
]

display(broadband_year_coverage)

    year  available_states  missing_states
22  2017                16               0
25  2020                16               0
26  2021                16               0
27  2022                16               0
28  2023                16               0

In [57]:
print(
    "Broadband years:",
    sorted(
        state_year.loc[
            state_year["broadband_100mbit"].notna(),
            "year"
        ].unique().tolist()
    )
)

Broadband years: [2017, 2020, 2021, 2022, 2023]

In [58]:
snapshot_2022_check = state_year[
    state_year["year"] == 2022
].copy()

snapshot_2022_missing = (
    snapshot_2022_check[metric_columns]
    .isna()
    .sum()
)

print(snapshot_2022_missing[snapshot_2022_missing > 0])

Series([], dtype: int64)

In [59]:
required_snapshot_year = 2022

snapshot_missing = (
    state_year.loc[
        state_year["year"] == required_snapshot_year,
        metric_columns
    ]
    .isna()
    .sum()
)

if snapshot_missing.sum() != 0:
    raise ValueError(
        f"The {required_snapshot_year} snapshot has missing values:\n"
        f"{snapshot_missing[snapshot_missing > 0]}"
    )

print(f"{required_snapshot_year} snapshot completeness validation passed.")

2022 snapshot completeness validation passed.

In [60]:
SNAPSHOT_YEAR = 2022

state_snapshot_2022 = (
    state_year[
        state_year["year"] == SNAPSHOT_YEAR
    ]
    .copy()
    .sort_values("state_name")
    .reset_index(drop=True)
)

print("Snapshot year:", SNAPSHOT_YEAR)
print("Rows:", len(state_snapshot_2022))
print("Unique states:", state_snapshot_2022["state_code"].nunique())

display(state_snapshot_2022.head())

Snapshot year: 2022
Rows: 16
Unique states: 16

,state_code,state_name,year,population,unemployment_rate,asking_rent,employment_rate,expert_level_employment,knowledge_intensive_industry,it_science_service_employment,population_change_10_years,total_migration_balance,median_income_academic,broadband_100mbit,gdp_per_capita
0,08,Baden-Württemberg,2022,11167721.0,3.54,11.0,65.65,14.30,16.26,4.99,5.66,15.96,5908.81,88.86,51.59
1,09,Bayern,2022,13105221.0,3.13,12.0,67.90,15.19,11.80,4.73,4.68,16.98,5721.57,91.03,54.70
2,11,Berlin,2022,3632853.0,8.84,12.0,60.91,20.89,3.09,5.26,7.63,23.28,5177.82,98.49,49.25
3,12,Brandenburg,2022,2545159.0,5.58,8.0,65.74,11.05,3.61,2.29,3.90,21.81,4743.54,86.76,34.86
4,04,Bremen,2022,695758.0,10.18,9.0,57.77,14.84,7.61,4.36,6.26,15.10,5364.98,96.45,53.32

In [61]:
snapshot_missing = (
    state_snapshot_2022[metric_columns]
    .isna()
    .sum()
)

print("Missing values in the snapshot:")
print(snapshot_missing[snapshot_missing > 0])

assert len(state_snapshot_2022) == 16, (
    "The snapshot should contain exactly 16 states."
)

assert state_snapshot_2022["state_code"].nunique() == 16, (
    "Each state should appear exactly once."
)

assert snapshot_missing.sum() == 0, (
    "The 2022 snapshot still contains missing metric values."
)

print("2022 snapshot validation passed.")

Missing values in the snapshot:
Series([], dtype: int64)
2022 snapshot validation passed.

In [62]:
snapshot_summary = (
    state_snapshot_2022[metric_columns]
    .agg(["min", "median", "mean", "max"])
    .T
    .round(2)
)

snapshot_summary = snapshot_summary.reset_index(
    names="metric"
)

display(snapshot_summary)

,metric,min,median,mean,max
0,population,695758.00,3286068.00,5194906.31,17964420.00
1,unemployment_rate,3.13,5.59,6.02,10.18
2,asking_rent,6.00,8.50,9.00,13.00
3,employment_rate,57.77,64.67,64.06,68.14
4,expert_level_employment,10.62,12.54,13.50,20.89
5,knowledge_intensive_industry,2.84,7.44,7.28,16.26
6,it_science_service_employment,2.01,3.66,3.89,6.03
7,population_change_10_years,-4.83,3.31,2.70,7.63
8,total_migration_balance,15.10,17.98,18.40,23.28
9,median_income_academic,4550.60,5199.22,5184.00,5908.81
10,broadband_100mbit,79.58,88.22,89.35,99.09
11,gdp_per_capita,33.54,42.20,45.10,80.92

In [63]:
pd.set_option("display.max_columns", None)

display(
    state_snapshot_2022[
        [
            "state_code",
            "state_name",
            *metric_columns
        ]
    ].round(2)
)

,state_code,state_name,population,unemployment_rate,asking_rent,employment_rate,expert_level_employment,knowledge_intensive_industry,it_science_service_employment,population_change_10_years,total_migration_balance,median_income_academic,broadband_100mbit,gdp_per_capita
0,08,Baden-Württemberg,11167721.0,3.54,11.0,65.65,14.30,16.26,4.99,5.66,15.96,5908.81,88.86,51.59
1,09,Bayern,13105221.0,3.13,12.0,67.90,15.19,11.80,4.73,4.68,16.98,5721.57,91.03,54.70
2,11,Berlin,3632853.0,8.84,12.0,60.91,20.89,3.09,5.26,7.63,23.28,5177.82,98.49,49.25
3,12,Brandenburg,2545159.0,5.58,8.0,65.74,11.05,3.61,2.29,3.90,21.81,4743.54,86.76,34.86
4,04,Bremen,695758.0,10.18,9.0,57.77,14.84,7.61,4.36,6.26,15.10,5364.98,96.45,53.32
5,02,Hamburg,1832675.0,6.84,13.0,64.88,19.55,3.44,6.03,5.67,21.51,5549.06,99.09,80.92
6,06,Hessen,6236933.0,4.77,11.0,63.91,15.65,7.92,5.49,3.66,18.31,5894.60,89.98,52.24
7,13,Mecklenburg-Vorpommern,1576049.0,7.31,7.0,65.89,11.08,2.84,2.01,-1.52,20.49,4642.55,79.58,34.77
8,03,Niedersachsen,7982947.0,5.26,8.0,64.46,11.74,6.32,3.36,2.62,19.07,4722.05,87.57,42.60
9,05,Nordrhein-Westfalen,17964420.0,6.84,8.0,61.83,13.33,7.39,4.37,2.34,15.77,5474.45,93.84,44.20
10,07,Rheinland-Pfalz,4108555.0,4.56,9.0,62.32,11.01,7.48,3.80,2.96,17.16,5450.30,83.36,41.80
11,10,Saarland,1011891.0,6.26,8.0,58.61,10.62,10.64,3.52,1.77,17.66,5211.64,87.06,38.37
12,14,Sachsen,4049967.0,5.60,6.0,68.14,13.81,8.18,3.15,-0.01,18.41,4671.99,85.94,36.11
13,15,Sachsen-Anhalt,2150239.0,7.08,6.0,67.39,10.85,5.62,3.19,-4.83,18.77,4673.17,83.55,34.65
14,01,Schleswig-Holstein,2939283.0,5.17,9.0,62.20,11.13,5.72,3.09,4.73,16.61,5186.79,92.83,38.68
15,16,Thüringen,2118830.0,5.30,7.0,67.29,10.89,8.61,2.53,-2.38,17.50,4550.60,85.14,33.54

In [64]:
SNAPSHOT_CSV_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "germany_state_snapshot_2022.csv"
)

SNAPSHOT_PARQUET_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "germany_state_snapshot_2022.parquet"
)

state_snapshot_2022.to_csv(
    SNAPSHOT_CSV_PATH,
    index=False,
    encoding="utf-8-sig"
)

state_snapshot_2022.to_parquet(
    SNAPSHOT_PARQUET_PATH,
    index=False
)

print("Snapshot CSV saved:", SNAPSHOT_CSV_PATH.exists())
print("Snapshot Parquet saved:", SNAPSHOT_PARQUET_PATH.exists())

Snapshot CSV saved: True
Snapshot Parquet saved: True

In [65]:
selected_metric_metadata = (
    indicator_df[
        indicator_df["Kürzel"].isin(SELECTED_CODES.keys())
    ]
    [
        [
            "Kurzname",
            "Name",
            "Algorithmus",
            "M_ID",
            "Kürzel",
            "Anmerkungen",
            "Statistische Grundlagen",
            "Gemeinden",
            "Kreise"
        ]
    ]
    .copy()
)

selected_metric_metadata["project_metric"] = (
    selected_metric_metadata["Kürzel"]
    .map(SELECTED_CODES)
)

selected_metric_metadata = selected_metric_metadata[
    [
        "project_metric",
        "Kurzname",
        "Name",
        "Algorithmus",
        "M_ID",
        "Kürzel",
        "Anmerkungen",
        "Statistische Grundlagen",
        "Gemeinden",
        "Kreise"
    ]
].sort_values("project_metric").reset_index(drop=True)

display(selected_metric_metadata)

,project_metric,Kurzname,Name,Algorithmus,M_ID,Kürzel,Anmerkungen,Statistische Grundlagen,Gemeinden,Kreise
0,asking_rent,Angebotsmietpreise,Wiedervermietungsmieten inserierter Wohnungen ...,duchschnittliche Angebotsmiete je m²,2113.0,m_mietpr,Die ausgewerteten Angebotsmieten basieren auf ...,Laufende Raumbeobachtung des BBSR; BBSR-Wohnun...,NaN,2010-2024
1,broadband_100mbit,Bandbreitenverfügbarkeit mindestens 100 Mbit/s,Anteil der Haushalte mit einer Bandbreitenverf...,Anzahl der Haushalte mit einem Breitbandanschl...,13117.0,a_bb_100Mbits,Als häufige Grundvoraussetzung für unternehmer...,Laufende Raumbeobachtung des BBSR; Gigabit-Gru...,2017-2023,2017-2023
2,employment_rate,Beschäftigtenquote,SV Beschäftigte am Wohnort je 100 Einwohner im...,SV Beschäftigte WO <Zeitpunkt> / E 15 bis < 65...,3101.0,q_svw,Der Indikator bildet das Ausmaß der Beschäftig...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,2001-2023,1997-2023
3,expert_level_employment,Beschäftigte mit Anforderungsniveau Experte,Anteil der SV Beschäftigten am Arbeitsort mit ...,SV Beschäftigte AO Anforderungsniveau Experte ...,3207.0,a_sva_exp,Anteil der SV Beschäftigten am Arbeitsort mit ...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,NaN,2013-2023
4,gdp_per_capita,Bruttoinlandsprodukt je Einwohner,Bruttoinlandsprodukt in 1.000 € je Einwohner,Bruttoinlandsprodukt <Zeitpunkt> / E <Zeitpunk...,14205.0,q_bip_ew,Bei Bezug auf die Bevölkerung als Wohlstandsma...,Laufende Raumbeobachtung des BBSR; Volkswirtsc...,NaN,1992-2022
5,it_science_service_employment,Beschäftigte in IT- und naturwissenschaftliche...,Anteil der sozialversicherungspfichtig Beschäf...,SV Beschäftigte AO in IT- und naturwissenschaf...,3409.0,a_svb_IT,Der Anteil der in IT- und naturwissenschaftlic...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,NaN,2013-2023
6,knowledge_intensive_industry,Beschäftigte in wissensintensiven Industrien,Anteil der SV Beschäftigten am Arbeitsort in w...,"SV Beschäftigte AO in den WZ 20, 21, 26-30 <Ze...",3408.0,a_svb_wissen,Der Anteil der in wissens- bzw. forschungsinte...,Laufende Raumbeobachtung des BBSR; Beschäftigt...,NaN,2009-2023
7,median_income_academic,Medianeinkommen akademischer Berufsabschluss,Medianeinkommen der sozialversicherungspflicht...,Medianeinkommen der sozialversicherungspflicht...,6009.0,m_ek_akad,Median der monatlichen Bruttoarbeitsentgelte v...,Laufende Raumbeobachtung des BBSR; Statistik d...,NaN,2014-2023
8,population,Bevölkerung gesamt,Zahl der Einwohner insgesamt,NaN,2.0,xbev,Es handelt sich um die Zahl der Einwohner zum ...,Laufende Raumbeobachtung des BBSR; Fortschreib...,1995-2023,1995-2023
9,population_change_10_years,Bevölkerungsentwicklung (10 Jahre),Entwicklung der Zahl der Einwohner über die le...,(E <aktueller Zeitpunkt> - E <Ausgangszeitpunk...,4217.0,e10_bev,Berechnet ist die Veränderung der Bevölkerung ...,Laufende Raumbeobachtung des BBSR; Fortschreib...,NaN,2005-2023
10,total_migration_balance,Gesamtwanderungssaldo,Gesamtwanderungssaldo je 1.000 Einwohner,(Zuzüge - Fortzüge <Zeitraum>) / E <Zeitpunkt>...,4301.0,i_wans,Die Wanderungsstatistik erstreckt sich auf Wan...,Laufende Raumbeobachtung des BBSR; Wanderungss...,1995-2023,1995-2023
11,unemployment_rate,Arbeitslosenquote,Anteil der Arbeitslosen an den zivilen Erwerbs...,Arbeitslose <Zeitpunkt> / alle zivile Erwerbsp...,1101.0,q_alo,Die Arbeitslosenquote zeigt die relative Unter...,Laufende Raumbeobachtung des BBSR; Arbeitsmark...,NaN,1998-2023

In [66]:
for _, row in selected_metric_metadata.iterrows():
    print("=" * 100)
    print("Project metric:", row["project_metric"])
    print("German short name:", row["Kurzname"])
    print("Full definition:", row["Name"])
    print("Algorithm:", row["Algorithmus"])
    print("Code:", row["Kürzel"])
    print("Notes:", row["Anmerkungen"])
    print("Source:", row["Statistische Grundlagen"])
    print()

====================================================================================================
Project metric: asking_rent
German short name: Angebotsmietpreise
Full definition: Wiedervermietungsmieten inserierter Wohnungen (Angebotsmieten)
Algorithm: duchschnittliche Angebotsmiete je m²
Code: m_mietpr
Notes: Die ausgewerteten Angebotsmieten basieren auf Inseraten aus Immobilienplattformen und von Zeitungen für Wiedervermietungen von Wohnungen im Gebäudebestand (ohne Neubau). Sie spiegeln das Angebot wider, auf das Wohnungssuchende treffen, wenn sie im Internet nach einer Mietwohnung suchen. Zur Standardaufbereitung bis auf die Ebene der Kreise erfolgte eine Eingrenzung der betrachteten Wohnungen auf Wohnflächen von 40 bis 100 m² mit mittlerer Wohnungsausstattung in mittlerer bis guter Wohnlage. Die verwendeten Daten umfassen nettokalte Angebotsmieten, also ohne kalte und warme Nebenkosten. Als Quelle werden die Datenbanken der IDN ImmoDaten GmbH mit Inseraten aus über 120 Immobilienportalen und Zeitungen verwendet, die das BBSR aufbereitet und daraus durchschnittliche Angebotsmieten berechnet. Mit dieser Quelle werden nicht alle Wohnungsangebote erfasst. Inserate aus lokalen Zeitungen, Mieter- oder Unternehmenspublikationen oder von Aushängen können nicht mit einfließen. Wohnungsvermittlungen über Kunden- und Wartelisten von Wohnungsunternehmen oder Maklern können ebenfalls nicht berücksichtigt werden. Daher können gerade Wohnungen im günstigen Mietsegment mit dieser Datenquelle unterrepräsentiert sein. Mieten aus bestehenden Mietverhältnissen lassen sich mit dieser Datengrundlage ebenfalls nicht darstellen.
Source: Laufende Raumbeobachtung des BBSR; BBSR-Wohnungsmarktbeobachtung, IDN ImmoDaten GmbH

====================================================================================================
Project metric: broadband_100mbit
German short name: Bandbreitenverfügbarkeit mindestens 100 Mbit/s
Full definition: Anteil der Haushalte mit einer Bandbreitenverfügbarkeit (leitungsgebunden) mit mindestens 100 Mbit/s in %
Algorithm: Anzahl der Haushalte mit einem Breitbandanschluss von mindestens 100 Mbit/s <Zeitpunkt> / Anzahl der Haushalte <Zeitpunkt> x 100
Code: a_bb_100Mbits
Notes: Als häufige Grundvoraussetzung für unternehmerisches Handeln wird die Breitbandversorgung verstärkt zum zentralen Standortfaktor. Auch private Haushalte profitieren von der Versorgung mit dem Breitbandinternet, z. B. durch die Ermöglichung der Arbeit im „Home-Office“. Dies kann die Vereinbarkeit von Beruf und Familie erleichtern. Die Breitbandversorgung ist zu einem Bestandteil der Daseinsvorsorge geworden und wird von staatlicher Seite mit zum Teil erheblichen Mitteln gefördert. Die Daten beinhalten lediglich Informationen zur Breitbandversorgung von privaten Haushalten, wobei diese Informationen auch Rückschlüsse zur Breitbandversorgung von Unternehmen zulassen. Im Auftrag des BMVI wird der Breitbandatlas von unterschiedlichen Unternehmen erstellt. Die Daten bis 2017 stammen vom TÜV Rheinland, 2020 von atene KOM und 2021 von der Mobilfunkinfrastrukturgesellschaft mbH (mig). Seit 2022 werden die Daten im Gigabit-Grundbuch veröffentlicht. Aufgrund der Änderung des Erhebungsbeauftragten gibt es Diskrepanzen in der Merkmalsverfügbarkeit. Außerdem gibt es aufgrund methodisch unterschiedlicher Erhebungsinstrumente Brüche in der Zeitreihe.

Stichtage unterscheiden sich in den jeweiligen Jahresveröffentlichungen:
Ende 2017, 2020, 2023
Mitte 2021, 2022
Source: Laufende Raumbeobachtung des BBSR; Gigabit-Grundbuch des Bundesministeriums für Verkehr und digitale Infrastruktur sowie der Bundesnetzagentur

====================================================================================================
Project metric: employment_rate
German short name: Beschäftigtenquote
Full definition: SV Beschäftigte am Wohnort je 100 Einwohner im erwerbsfähigen Alter in %
Algorithm: SV Beschäftigte WO <Zeitpunkt> / E 15 bis < 65 Jahre <Zeitpunkt> x 100
Code: q_svw
Notes: Der Indikator bildet das Ausmaß der Beschäftigung bezogen auf alle Erwerbsfähigen ab. Konkret beschreibt er die Zahl sozialversicherungspflichtig Beschäftigter am Wohnort je 100 Einwohner im erwerbsfähigen Alter (15 bis unter 65 Jahre). Sozialversicherungspflichtig Beschäftigte sind Arbeiter, Angestellte und Personen in beruflicher Ausbildung, die in der gesetzlicher Renten-, Kranken- und/oder Arbeitslosenversicherung pflichtversichert sind. Keine Berücksichtigung finden hier also Beamte, Selbständige, mithelfende Familienangehörige oder geringfügig Beschäftigte. Insgesamt werden so nur rund 75% aller Erwerbstätigen erfasst. Trotz dieser Einschränkung werden die sozialversicherungspflichtig Beschäftigten als Maß der dem Arbeitsmarkt zur Verfügung stehenden Arbeitsplätze verwendet. Bei den Bevölkerungszahlen handelt es sich um die Fortschreibung des Bevölkerungsstandes des Bundes und der Länder zum Stichtag 31.12. des Jahres. Die Fortschreibung basiert auf der Volkszählung 1987 (BRD) bzw. 1981 (DDR), dem Zensus 2011 sowie dem Zensus 2022. Bei den Beschäftigten handelt es sich um Zahlen zum Stichtag 30.06.. Ab 2013 handelt es sich um revidierte Daten (Revision 2014). Die Anzahl der sozialversicherungspflichtig Beschäftigten erhöhte sich dabei bundesweit um rund 350.000 Personen, das sind rund 1,2%.
Source: Laufende Raumbeobachtung des BBSR; Beschäftigtenstatistik der Bundesagentur für Arbeit

====================================================================================================
Project metric: expert_level_employment
German short name: Beschäftigte mit Anforderungsniveau Experte
Full definition: Anteil der SV Beschäftigten am Arbeitsort mit Anforderungsniveau Experte an den SV Beschäftigten in %
Algorithm: SV Beschäftigte AO Anforderungsniveau Experte <Zeitpunkt> / SV Beschäftigte <Zeitpunkt> x 100
Code: a_sva_exp
Notes: Anteil der SV Beschäftigten am Arbeitsort mit Anforderungsniveau Experte nach Klassifikation der Berufe 2010 (KldB 2010). Zum Anforderungsniveau Experte zählen hoch komplexe Tätigkeiten mit einem sehr hohen Kenntnis- und Fertigkeitsniveau sowie Leitungs- und Führungsaufgaben und mindestens einer vierjährigen Hochschulausbildung bzw. einer entsprechenden Berufserfahrung. Die Summe der Anteile ergibt weniger als 100 Prozent, weil die Kategorie "keine Angabe" nicht in die Berechnung einbezogen ist. Sozialversicherungspflichtig Beschäftigte sind Arbeiter, Angestellte und Personen in beruflicher Ausbildung, die in der gesetzlicher Renten-, Kranken- und/oder Arbeitslosenversicherung pflichtversichert sind. Keine Berücksichtigung finden hier also Beamte, Selbständige, mithelfende Familienangehörige oder geringfügig Beschäftigte. Insgesamt werden so nur rund 75% aller Erwerbstätigen erfasst. Trotz dieser Einschränkung werden die sozialversicherungspflichtig Beschäftigten als Maß der dem Arbeitsmarkt zur Verfügung stehenden Arbeitsplätze verwendet. Bei den Beschäftigten handelt es sich um Zahlen zum Stichtag 30.06..
Source: Laufende Raumbeobachtung des BBSR; Beschäftigtenstatistik der Bundesagentur für Arbeit

====================================================================================================
Project metric: gdp_per_capita
German short name: Bruttoinlandsprodukt je Einwohner
Full definition: Bruttoinlandsprodukt in 1.000 € je Einwohner
Algorithm: Bruttoinlandsprodukt <Zeitpunkt> / E <Zeitpunkt> / 1.000
Code: q_bip_ew
Notes: Bei Bezug auf die Bevölkerung als Wohlstandsmaß zu interpretieren. Das BIP bzw. die BWS ist ein Maß für die ein einer Region erbrachte wirtschaftliche Leistung. Die BWS je Wirtschaftsbereich wird berechnet, indem vom Wert aller produzierten Waren und Dienstleistungen die bei der Produktion verbrauchten Vorleistungen (Roh-, Hilfs- und Betriebsstoffe, Mieten und Pachten, Kosten für durch andere Unternehmen durchgeführte Lohnarbeiten etc.) abgezogen werden. Die Bewertung der BWS erfolgt zu Herstellungspreisen. Dieses Bewertungskonzept bedeutet, dass die auf die produzierten oder verkauften Waren und Dienstleistungen gewährten Gütersubventionen einbezogen sind, nicht aber die auf die produzierten Waren und Dienstleistungen zu zahlenden Gütersteuern (Mehrwertsteuer, Importabgaben, Mineralöl- und Tabaksteuer etc.). Das BIP wird zu Marktpreisen bewertet. Es wird berechnet, indem zur gesamten BWS zu Herstellungspreisen der auf die Kreise pauschal verteilte Saldo aus Gütersteuern – Gütersubventionen hinzu addiert wird. Die Finanzserviceleistung indirekte Messung (FISIM) ist implizit in den Wirtschaftsbereichen bereits berücksichtigt. Bei den Bevölkerungszahlen handelt es sich um die Fortschreibung des Bevölkerungsstandes des Bundes und der Länder zum Stichtag 31.12. des Jahres. Die Fortschreibung basiert auf der Volkszählung 1987 (BRD) bzw. 1981 (DDR), dem Zensus 2011 sowie dem Zensus 2022.

Source: Laufende Raumbeobachtung des BBSR; Volkswirtschaftliche Gesamtrechnung der Länder

====================================================================================================
Project metric: it_science_service_employment
German short name: Beschäftigte in IT- und naturwissenschaftlichen Dienstleistungsberufen
Full definition: Anteil der sozialversicherungspfichtig Beschäftigten in IT- und naturwissenschaftlichen Dienstleistungsberufen an den SV Beschäftigten in %
Algorithm: SV Beschäftigte AO in IT- und naturwissenschaftlichen Dienstleistungsberufen <Zeitpunkt> / SV Beschäftigte AO <Zeitpunkt> * 100
Code: a_svb_IT
Notes: Der Anteil der in IT- und naturwissenschaftlichen Dienstleistungsberufen tätigen sozialversicherungspflichtig Beschäftigten. Er ist ein Hinweis auf technologische Leistungsfähigkeit und hat einen hohen Akademikeranteil unter den Beschäftigten. Sozialversicherungspflichtig Beschäftigte sind Arbeiter, Angestellte und Personen in beruflicher Ausbildung, die in der gesetzlicher Renten-, Kranken- und/oder Arbeitslosenversicherung pflichtversichert sind. Keine Berücksichtigung finden hier also Beamte, Selbständige, mithelfende Familienangehörige oder geringfügig Beschäftigte. Insgesamt werden so nur rund 75% aller Erwerbstätigen erfasst. Trotz dieser Einschränkung werden die sozialversicherungspflichtig Beschäftigten als Maß der dem Arbeitsmarkt zur Verfügung stehenden Arbeitsplätze verwendet. Es handelt sich um SV Beschäftigte am Arbeitsort.
Source: Laufende Raumbeobachtung des BBSR; Beschäftigtenstatistik der Bundesagentur für Arbeit

====================================================================================================
Project metric: knowledge_intensive_industry
German short name: Beschäftigte in wissensintensiven Industrien
Full definition: Anteil der SV Beschäftigten am Arbeitsort in wissens- u. forschungsintensiven Industrien an den SV Beschäftigten in %
Algorithm: SV Beschäftigte AO in den WZ 20, 21, 26-30 <Zeitpunkt> / SV Beschäftigte AO <Zeitpunkt> x 100
Code: a_svb_wissen
Notes: Der Anteil der in wissens- bzw. forschungsintensiven Industrien tätigen sozialversicherungspflichtig Beschäftigten. Er ist ein Hinweis auf technologische Leistungsfähigkeit und hat einen hohen Akademikeranteil unter den Beschäftigten. Wissens- bzw. forschungsintensive Industrien (nach WZ 2008, NIW/ISI/ZEW-Liste 2010) sind folgende Abteilungen: 20 (Herst. v. chem. Erzeugnissen), 21 (Herst. v. pharmazeut. Erzeugnissen), 26 (Herst. v. Datenverarbeitungsgeräten, elektron. u. optischen Erzeugnissen), 27 (Herst. v. elektrischen Ausrüstungen), 28 (Maschinenbau), 29 (Herst. v. Kraftwagen u. Teilen), 30 (sonst. Fahrzeugbau). Sozialversicherungspflichtig Beschäftigte sind Arbeiter, Angestellte und Personen in beruflicher Ausbildung, die in der gesetzlicher Renten-, Kranken- und/oder Arbeitslosenversicherung pflichtversichert sind. Keine Berücksichtigung finden hier also Beamte, Selbständige, mithelfende Familienangehörige oder geringfügig Beschäftigte. Insgesamt werden so nur rund 75% aller Erwerbstätigen erfasst. Trotz dieser Einschränkung werden die sozialversicherungspflichtig Beschäftigten als Maß der dem Arbeitsmarkt zur Verfügung stehenden Arbeitsplätze verwendet. Es handelt sich um SV Beschäftigte am Arbeitsort.
Source: Laufende Raumbeobachtung des BBSR; Beschäftigtenstatistik der Bundesagentur für Arbeit

====================================================================================================
Project metric: median_income_academic
German short name: Medianeinkommen akademischer Berufsabschluss
Full definition: Medianeinkommen der sozialversicherungspflichtig Vollzeitbeschäftigten mit akademischem Berufsabschluss in Euro
Algorithm: Medianeinkommen der sozialversicherungspflichtig Vollzeitbeschäftigten mit akademischem Berufsabschluss in €
Code: m_ek_akad
Notes: Median der monatlichen Bruttoarbeitsentgelte von sozialversicherungspflichtig Vollzeitbeschäftigten (der Kerngruppe) am Arbeitsort. Der Median (auch Zentralwert) gibt den mittleren Wert einer der Göße nach sortierten Verteilung von Messwerten an und teilt damit den Datensatz in zwei gleich große Hälften. Somit ist er im Vergleich zum arithmetischen Mittel robuster gegenüber Ausreißern. Vergleiche zu den Vorjahren sind nicht oder nur eingeschränkt  möglich wegen eines 2011 eingeführten neuen Verfahrens, mit dem die Arbeitgeber ihre Meldungen über Voll- und Teilzeitbeschäftigung an die BA weitergeben. Die Informationen über die Inhalte des neuen Erhebungsverfahrens lagen nicht gleichzeitig zu einem bestimmten Stichtag vor, stattdessen gab es eine zweijährige Übergangsphase.
Die Berechnung der Werte für die Raumeinheiten (nicht Kreiswerte) sind mit Hilfe der Kreiswerte geschätzt.

Source: Laufende Raumbeobachtung des BBSR; Statistik der Bundesagentur für Arbeit

====================================================================================================
Project metric: population
German short name: Bevölkerung gesamt
Full definition: Zahl der Einwohner insgesamt
Algorithm: nan
Code: xbev
Notes: Es handelt sich um die Zahl der Einwohner zum Stichtag 31.12. des jeweiligen Jahres. Als Bevölkerung (Einwohnerinnen und Einwohner) wird die Anzahl der Personen bezeichnet, die in einer Regionaleinheit (Gemeinde, Kreis usw.) ihren ständigen Wohnsitz (Hauptwohnsitz) haben, einschließlich der dort für längere Zeit als wohnhaft gemeldeten Ausländer. Das BBSR verwendet die Bevölkerung zum Stichtag 31. Dezember für alle einwohnerbezogenen Indikatoren, so auch bei Fließgrößen über das Jahr (wie Geburten, Sterbefälle, Wanderungen, Finanzströmen und – anders als die Statistischen Ämter des Bundes und der Länder - auch bei den Größen der Volkswirtschaftlichen Gesamtrechnung. Bei den Bevölkerungszahlen handelt es sich um die Fortschreibung des Bevölkerungsstandes des Bundes und der Länder zum Stichtag 31.12. des Jahres. Die Fortschreibung basiert auf der Volkszählung 1987 (BRD) bzw. 1981 (DDR), dem Zensus 2011 sowie dem Zensus 2022.
Source: Laufende Raumbeobachtung des BBSR; Fortschreibung des Bevölkerungsstandes des Bundes und der Länder

====================================================================================================
Project metric: population_change_10_years
German short name: Bevölkerungsentwicklung (10 Jahre)
Full definition: Entwicklung der Zahl der Einwohner über die letzten 10 Jahre in %
Algorithm: (E <aktueller Zeitpunkt> - E <Ausgangszeitpunkt>) / E <Ausgangszeitpunkt> x 100
Code: e10_bev
Notes: Berechnet ist die Veränderung der Bevölkerung über die jeweils letzten 10 Jahre. Bei den Bevölkerungszahlen handelt es sich um die Fortschreibung des Bevölkerungsstandes des Bundes und der Länder zum Stichtag 31.12. des Jahres. Die Fortschreibung basiert auf der Volkszählung 1987 (BRD) bzw. 1981 (DDR), dem Zensus 2011 sowie dem Zensus 2022.
Source: Laufende Raumbeobachtung des BBSR; Fortschreibung des Bevölkerungsstandes des Bundes und der Länder

====================================================================================================
Project metric: total_migration_balance
German short name: Gesamtwanderungssaldo
Full definition: Gesamtwanderungssaldo je 1.000 Einwohner
Algorithm: (Zuzüge - Fortzüge <Zeitraum>) / E <Zeitpunkt> x 1.000
Code: i_wans
Notes: Die Wanderungsstatistik erstreckt sich auf Wanderungen über Gemeinde- und Kreisgrenzen innerhalb des Bundesgebiets sowie über die Grenzen des Bundesgebiets. Unberücksichtigt bleiben Umzüge innerhalb der Gemeinden (Ortsumzüge). Als Wanderung im vorstehenden Sinne gelten nur Änderungen der Hauptwohnung. Zu- und Fortzüge werden überwiegend mittels Anmeldescheinen festgestellt. Die Salden werden aus den Zu- und Abgängen während des angegebenen Zeitraums gebildet und auf die Endbevölkerung dieses Zeitraums bezogen. Die Zuverlässigkeit der Wanderungssalden kann durch die Untererfassung bei den An- und Abmeldungen beeinträchtigt sein. Bei den Bevölkerungszahlen handelt es sich um die Fortschreibung des Bevölkerungsstandes des Bundes und der Länder zum Stichtag 31.12. des Jahres. Die Fortschreibung basiert auf der Volkszählung 1987 (BRD) bzw. 1981 (DDR), dem Zensus 2011 sowie dem Zensus 2022.
Source: Laufende Raumbeobachtung des BBSR; Wanderungsstatistik des Bundes und der Länder

====================================================================================================
Project metric: unemployment_rate
German short name: Arbeitslosenquote
Full definition: Anteil der Arbeitslosen an den zivilen Erwerbspersonen in %
Algorithm: Arbeitslose <Zeitpunkt> / alle zivile Erwerbspersonen <Zeitpunkt> x 100
Code: q_alo
Notes: Die Arbeitslosenquote zeigt die relative Unterauslastung des Arbeitskräfteangebots an. Sie ist ein zentrales Maß für einen unausgeglichenen regionalen Arbeitsmarkt. Die Arbeitslosenquote in ihrer zeitlichen Entwicklung zeigt allerdings nur bedingt Strukturprobleme auf dem regionalen Arbeitsmarkt an; hierzu sind weitere Informationen des Arbeitsmarktes erforderlich. Die Zusammenlegung von Arbeitslosen- und Sozialhilfeleistung im Zuge der Arbeitsmarkreformen 2005 hat zunächst zum Anstieg der Arbeitslosenquote beigetragen. Der anschließende Rückgang ist dann eher auf eine verlangsamte Produktivitätsentwicklung, die Zunahme atypischer Beschäftigungsverhältnisse, die Verteilung des Arbeitsvolumens auf mehr Köpfe sowie auf sinkende Arbeitskraftreserven zurückzuführen. Für die Bezugsgröße (Nenner) gibt es unterschiedliche Varianten; hier werden alle zivilen Erwerbspersonen als Bezugsgröße gewählt. Zivile Erwerbspersonen umfassen die zivilen Erwerbstätigen und Arbeitslose. Regional werden zivile Erwerbspersonen bei kleinen Einheiten unter 1.000 Personen gar nicht und bei Einheiten zwischen 1.000 und 15.000 Personen nach Ermessen ausgewiesen. Daher berechnet die BA für die Ebene der Gemeinden keine Arbeitslosenquote. Auf Ebene der Gemeinden schätzt das BBSR die zivilen Erwerbspersonen anhand der kreisweisen Erwerbsbeteiligung und der gemeindlichen Angaben zur Bevölkerung im Alter von 15 bis unter 65 Jahren und berechnet auf dieser Basis eine Arbeitslosenquote für die Gemeindeverbände. Letztere stellen daher nur eine grobe Schätzung dar und spiegeln nicht zwangsläufig die echte Arbeitslosenquote für den Gemeindeverband wider.
Source: Laufende Raumbeobachtung des BBSR; Arbeitsmarktstatistik  der Bundesagentur für Arbeit (BA)

In [67]:
METRIC_DICTIONARY_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "metric_dictionary.csv"
)

selected_metric_metadata.to_csv(
    METRIC_DICTIONARY_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Metric dictionary saved:", METRIC_DICTIONARY_PATH.exists())
print("Path:", METRIC_DICTIONARY_PATH)

Metric dictionary saved: True
Path: c:\Users\maazm\Desktop\Projects\datacareer-germany\data\processed\metric_dictionary.csv

In [68]:
METRIC_CONFIG = {
    "population": {
        "label": "Population",
        "higher_is_better": None,
        "include_in_score": False
    },
    "unemployment_rate": {
        "label": "Unemployment rate",
        "higher_is_better": False,
        "include_in_score": True
    },
    "asking_rent": {
        "label": "Asking rent",
        "higher_is_better": False,
        "include_in_score": True
    },
    "employment_rate": {
        "label": "Employment rate",
        "higher_is_better": True,
        "include_in_score": True
    },
    "expert_level_employment": {
        "label": "Expert-level employment",
        "higher_is_better": True,
        "include_in_score": True
    },
    "knowledge_intensive_industry": {
        "label": "Knowledge-intensive industry employment",
        "higher_is_better": True,
        "include_in_score": True
    },
    "it_science_service_employment": {
        "label": "IT and science service employment",
        "higher_is_better": True,
        "include_in_score": True
    },
    "population_change_10_years": {
        "label": "10-year population change",
        "higher_is_better": True,
        "include_in_score": True
    },
    "total_migration_balance": {
        "label": "Total migration balance",
        "higher_is_better": True,
        "include_in_score": True
    },
    "median_income_academic": {
        "label": "Median income for academic qualifications",
        "higher_is_better": True,
        "include_in_score": True
    },
    "broadband_100mbit": {
        "label": "100 Mbit/s broadband availability",
        "higher_is_better": True,
        "include_in_score": True
    },
    "gdp_per_capita": {
        "label": "GDP per capita",
        "higher_is_better": True,
        "include_in_score": True
    }
}

config_check = pd.DataFrame(METRIC_CONFIG).T.reset_index(
    names="metric"
)

display(config_check)

,metric,label,higher_is_better,include_in_score
0,population,Population,None,False
1,unemployment_rate,Unemployment rate,False,True
2,asking_rent,Asking rent,False,True
3,employment_rate,Employment rate,True,True
4,expert_level_employment,Expert-level employment,True,True
5,knowledge_intensive_industry,Knowledge-intensive industry employment,True,True
6,it_science_service_employment,IT and science service employment,True,True
7,population_change_10_years,10-year population change,True,True
8,total_migration_balance,Total migration balance,True,True
9,median_income_academic,Median income for academic qualifications,True,True
10,broadband_100mbit,100 Mbit/s broadband availability,True,True
11,gdp_per_capita,GDP per capita,True,True

In [69]:
analysis_snapshot = state_snapshot_2022.copy()

# Convert GDP from thousand euros into euros
analysis_snapshot["gdp_per_capita_eur"] = (
    analysis_snapshot["gdp_per_capita"] * 1_000
)

# Illustrative monthly asking rent for a 50 m² apartment
ASSUMED_APARTMENT_SIZE_SQM = 50

analysis_snapshot["estimated_rent_50sqm"] = (
    analysis_snapshot["asking_rent"]
    * ASSUMED_APARTMENT_SIZE_SQM
)

# Illustrative share of academic gross monthly income required for rent
analysis_snapshot["rent_burden_50sqm_pct"] = (
    analysis_snapshot["estimated_rent_50sqm"]
    / analysis_snapshot["median_income_academic"]
    * 100
)

# Remaining gross monthly income after illustrative rent
analysis_snapshot["income_after_rent_50sqm"] = (
    analysis_snapshot["median_income_academic"]
    - analysis_snapshot["estimated_rent_50sqm"]
)

# Income relative to asking rent per square metre
analysis_snapshot["income_to_rent_index"] = (
    analysis_snapshot["median_income_academic"]
    / analysis_snapshot["asking_rent"]
)

display(
    analysis_snapshot[
        [
            "state_name",
            "median_income_academic",
            "asking_rent",
            "estimated_rent_50sqm",
            "rent_burden_50sqm_pct",
            "income_after_rent_50sqm",
            "income_to_rent_index"
        ]
    ]
    .sort_values(
        "rent_burden_50sqm_pct"
    )
    .round(2)
)

,state_name,median_income_academic,asking_rent,estimated_rent_50sqm,rent_burden_50sqm_pct,income_after_rent_50sqm,income_to_rent_index
13,Sachsen-Anhalt,4673.17,6.0,300.0,6.42,4373.17,778.86
12,Sachsen,4671.99,6.0,300.0,6.42,4371.99,778.66
9,Nordrhein-Westfalen,5474.45,8.0,400.0,7.31,5074.45,684.31
7,Mecklenburg-Vorpommern,4642.55,7.0,350.0,7.54,4292.55,663.22
11,Saarland,5211.64,8.0,400.0,7.68,4811.64,651.46
15,Thüringen,4550.60,7.0,350.0,7.69,4200.60,650.09
10,Rheinland-Pfalz,5450.30,9.0,450.0,8.26,5000.30,605.59
4,Bremen,5364.98,9.0,450.0,8.39,4914.98,596.11
3,Brandenburg,4743.54,8.0,400.0,8.43,4343.54,592.94
8,Niedersachsen,4722.05,8.0,400.0,8.47,4322.05,590.26
14,Schleswig-Holstein,5186.79,9.0,450.0,8.68,4736.79,576.31
0,Baden-Württemberg,5908.81,11.0,550.0,9.31,5358.81,537.16
6,Hessen,5894.60,11.0,550.0,9.33,5344.60,535.87
1,Bayern,5721.57,12.0,600.0,10.49,5121.57,476.80
2,Berlin,5177.82,12.0,600.0,11.59,4577.82,431.48
5,Hamburg,5549.06,13.0,650.0,11.71,4899.06,426.85

In [70]:
derived_columns = [
    "gdp_per_capita_eur",
    "estimated_rent_50sqm",
    "rent_burden_50sqm_pct",
    "income_after_rent_50sqm",
    "income_to_rent_index"
]

print("Missing derived values:")
print(
    analysis_snapshot[
        derived_columns
    ].isna().sum()
)

print("\nInvalid or negative values:")
for column in derived_columns:
    invalid_count = (
        analysis_snapshot[column] < 0
    ).sum()

    print(f"{column}: {invalid_count}")

Missing derived values:
gdp_per_capita_eur         0
estimated_rent_50sqm       0
rent_burden_50sqm_pct      0
income_after_rent_50sqm    0
income_to_rent_index       0
dtype: int64

Invalid or negative values:
gdp_per_capita_eur: 0
estimated_rent_50sqm: 0
rent_burden_50sqm_pct: 0
income_after_rent_50sqm: 0
income_to_rent_index: 0

In [71]:
def percentile_score(
    series: pd.Series,
    higher_is_better: bool = True
) -> pd.Series:
    """
    Convert a numeric series into relative percentile scores.

    Parameters
    ----------
    series:
        Numeric values to score.
    higher_is_better:
        True when larger values represent better performance.
        False when smaller values represent better performance.

    Returns
    -------
    pd.Series
        Scores between approximately 0 and 100.
    """

    numeric_series = pd.to_numeric(
        series,
        errors="coerce"
    )

    if numeric_series.isna().any():
        raise ValueError(
            f"Cannot score a metric containing "
            f"{numeric_series.isna().sum()} missing values."
        )

    scores = numeric_series.rank(
        method="average",
        pct=True,
        ascending=higher_is_better
    ) * 100

    return scores

In [72]:
test_values = pd.Series(
    [10, 20, 30],
    name="test"
)

print(
    "Higher is better:",
    percentile_score(
        test_values,
        higher_is_better=True
    ).tolist()
)

print(
    "Lower is better:",
    percentile_score(
        test_values,
        higher_is_better=False
    ).tolist()
)

Higher is better: [33.33333333333333, 66.66666666666666, 100.0]
Lower is better: [100.0, 66.66666666666666, 33.33333333333333]

In [73]:
SCORING_DIRECTIONS = {
    "unemployment_rate": False,
    "employment_rate": True,
    "expert_level_employment": True,
    "knowledge_intensive_industry": True,
    "it_science_service_employment": True,

    "asking_rent": False,
    "rent_burden_50sqm_pct": False,
    "income_to_rent_index": True,

    "median_income_academic": True,
    "gdp_per_capita_eur": True,

    "broadband_100mbit": True,

    "population_change_10_years": True,
    "total_migration_balance": True
}

for metric, higher_is_better in SCORING_DIRECTIONS.items():
    score_column = f"{metric}_score"

    analysis_snapshot[score_column] = percentile_score(
        analysis_snapshot[metric],
        higher_is_better=higher_is_better
    )

print(
    "Individual metric scores created:",
    len(SCORING_DIRECTIONS)
)

Individual metric scores created: 13

In [74]:
score_columns = [
    f"{metric}_score"
    for metric in SCORING_DIRECTIONS
]

score_validation = analysis_snapshot[
    score_columns
].agg(
    ["min", "max"]
).T

display(score_validation)

                                      min      max
unemployment_rate_score              6.25  100.000
employment_rate_score                6.25  100.000
expert_level_employment_score        6.25  100.000
knowledge_intensive_industry_score   6.25  100.000
it_science_service_employment_score  6.25  100.000
asking_rent_score                    6.25   96.875
rent_burden_50sqm_pct_score          6.25  100.000
income_to_rent_index_score           6.25  100.000
median_income_academic_score         6.25  100.000
gdp_per_capita_eur_score             6.25  100.000
broadband_100mbit_score              6.25  100.000
population_change_10_years_score     6.25  100.000
total_migration_balance_score        6.25  100.000

In [75]:
analysis_snapshot["career_strength_score"] = (
    analysis_snapshot[
        "unemployment_rate_score"
    ] * 0.25

    + analysis_snapshot[
        "employment_rate_score"
    ] * 0.15

    + analysis_snapshot[
        "expert_level_employment_score"
    ] * 0.20

    + analysis_snapshot[
        "it_science_service_employment_score"
    ] * 0.30

    + analysis_snapshot[
        "knowledge_intensive_industry_score"
    ] * 0.10
)

In [76]:
analysis_snapshot["affordability_score"] = (
    analysis_snapshot[
        "income_to_rent_index_score"
    ] * 0.60

    + analysis_snapshot[
        "asking_rent_score"
    ] * 0.20

    + analysis_snapshot[
        "rent_burden_50sqm_pct_score"
    ] * 0.20
)

In [77]:
analysis_snapshot["income_economic_score"] = (
    analysis_snapshot[
        "median_income_academic_score"
    ] * 0.65

    + analysis_snapshot[
        "gdp_per_capita_eur_score"
    ] * 0.35
)

In [78]:
analysis_snapshot["digital_readiness_score"] = (
    analysis_snapshot[
        "broadband_100mbit_score"
    ]
)

In [79]:
analysis_snapshot["regional_momentum_score"] = (
    analysis_snapshot[
        "population_change_10_years_score"
    ] * 0.50

    + analysis_snapshot[
        "total_migration_balance_score"
    ] * 0.50
)

In [80]:
DEFAULT_CATEGORY_WEIGHTS = {
    "career_strength_score": 0.35,
    "affordability_score": 0.25,
    "income_economic_score": 0.20,
    "digital_readiness_score": 0.10,
    "regional_momentum_score": 0.10
}

assert round(
    sum(DEFAULT_CATEGORY_WEIGHTS.values()),
    10
) == 1.0, "Category weights must total 1.0"

analysis_snapshot["opportunity_score"] = sum(
    analysis_snapshot[column] * weight
    for column, weight
    in DEFAULT_CATEGORY_WEIGHTS.items()
)

analysis_snapshot["overall_rank"] = (
    analysis_snapshot["opportunity_score"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)

In [81]:
ranking_columns = [
    "overall_rank",
    "state_name",
    "opportunity_score",
    "career_strength_score",
    "affordability_score",
    "income_economic_score",
    "digital_readiness_score",
    "regional_momentum_score"
]

state_ranking_2022 = (
    analysis_snapshot[
        ranking_columns
    ]
    .sort_values("overall_rank")
    .reset_index(drop=True)
)

display(
    state_ranking_2022.round(2)
)

,overall_rank,state_name,opportunity_score,career_strength_score,affordability_score,income_economic_score,digital_readiness_score,regional_momentum_score
0,1,Baden-Württemberg,64.86,80.94,30.62,91.25,56.25,50.00
1,1,Bayern,64.86,87.19,18.12,89.69,68.75,50.00
2,3,Hessen,63.94,79.38,25.62,89.38,62.50,56.25
3,4,Nordrhein-Westfalen,62.76,49.22,83.12,70.62,81.25,25.00
4,5,Hamburg,61.55,67.66,6.25,87.81,100.00,87.50
5,6,Bremen,56.31,42.50,53.75,71.25,87.50,50.00
6,7,Sachsen,55.62,56.88,94.38,23.12,31.25,43.75
7,8,Rheinland-Pfalz,52.00,55.00,58.75,62.19,12.50,43.75
8,9,Berlin,51.86,53.44,13.12,52.50,93.75,100.00
9,10,Saarland,49.89,37.81,73.12,49.69,43.75,40.62
10,11,Niedersachsen,49.23,52.19,48.12,40.00,50.00,59.38
11,12,Sachsen-Anhalt,47.28,36.25,99.38,20.62,18.75,37.50
12,13,Schleswig-Holstein,46.95,43.44,38.75,47.81,75.00,50.00
13,14,Brandenburg,44.38,36.88,53.12,33.12,37.50,78.12
14,15,Thüringen,40.39,45.31,71.88,6.25,25.00,28.12
15,16,Mecklenburg-Vorpommern,38.11,25.94,81.88,14.69,6.25,50.00

In [82]:
print(
    state_ranking_2022[
        [
            "overall_rank",
            "state_name",
            "opportunity_score"
        ]
    ]
    .round(2)
    .to_string(index=False)
)

 overall_rank             state_name  opportunity_score
            1      Baden-Württemberg              64.86
            1                 Bayern              64.86
            3                 Hessen              63.94
            4    Nordrhein-Westfalen              62.76
            5                Hamburg              61.55
            6                 Bremen              56.31
            7                Sachsen              55.62
            8        Rheinland-Pfalz              52.00
            9                 Berlin              51.86
           10               Saarland              49.89
           11          Niedersachsen              49.23
           12         Sachsen-Anhalt              47.28
           13     Schleswig-Holstein              46.95
           14            Brandenburg              44.38
           15              Thüringen              40.39
           16 Mecklenburg-Vorpommern              38.11

In [83]:
top_two_check = (
    analysis_snapshot.loc[
        analysis_snapshot["state_name"].isin(
            ["Baden-Württemberg", "Bayern"]
        ),
        [
            "state_name",
            "opportunity_score",
            "career_strength_score",
            "affordability_score",
            "income_economic_score",
            "digital_readiness_score",
            "regional_momentum_score"
        ]
    ]
    .sort_values(
        "opportunity_score",
        ascending=False
    )
)

print(
    top_two_check.to_string(
        index=False,
        float_format=lambda value: f"{value:.10f}"
    )
)

       state_name  opportunity_score  career_strength_score  affordability_score  income_economic_score  digital_readiness_score  regional_momentum_score
Baden-Württemberg      64.8593750000          80.9375000000        30.6250000000          91.2500000000            56.2500000000            50.0000000000
           Bayern      64.8593750000          87.1875000000        18.1250000000          89.6875000000            68.7500000000            50.0000000000

In [84]:
top_two_values = (
    top_two_check["opportunity_score"]
    .sort_values(ascending=False)
    .to_numpy()
)

score_difference = abs(
    top_two_values[0] - top_two_values[1]
)

print(
    "Difference between first-place scores:",
    f"{score_difference:.12f}"
)

Difference between first-place scores: 0.000000000000

In [85]:
CATEGORY_LABELS = {
    "career_strength_score": "Career strength",
    "affordability_score": "Affordability",
    "income_economic_score": "Income and economy",
    "digital_readiness_score": "Digital readiness",
    "regional_momentum_score": "Regional momentum"
}

for category, weight in DEFAULT_CATEGORY_WEIGHTS.items():
    contribution_column = category.replace(
        "_score",
        "_contribution"
    )

    analysis_snapshot[contribution_column] = (
        analysis_snapshot[category] * weight
    )

In [86]:
contribution_columns = [
    column.replace("_score", "_contribution")
    for column in DEFAULT_CATEGORY_WEIGHTS
]

analysis_snapshot["recalculated_opportunity_score"] = (
    analysis_snapshot[contribution_columns]
    .sum(axis=1)
)

analysis_snapshot["score_difference"] = (
    analysis_snapshot["opportunity_score"]
    - analysis_snapshot["recalculated_opportunity_score"]
).abs()

print(
    "Largest score-calculation difference:",
    analysis_snapshot["score_difference"].max()
)

assert analysis_snapshot["score_difference"].max() < 1e-10, (
    "Opportunity score does not match category contributions."
)

print("Opportunity-score validation passed.")

Largest score-calculation difference: 0.0
Opportunity-score validation passed.

In [88]:
ranking_contributions = (
    analysis_snapshot[
        [
            "overall_rank",
            "state_name",
            "opportunity_score",
            "career_strength_score",
            *contribution_columns
        ]
    ]
    .sort_values(
        by=[
            "opportunity_score",
            "career_strength_score"
        ],
        ascending=[
            False,
            False
        ]
    )
    .reset_index(drop=True)
)

display(
    ranking_contributions.round(2)
)

,overall_rank,state_name,opportunity_score,career_strength_score,career_strength_contribution,affordability_contribution,income_economic_contribution,digital_readiness_contribution,regional_momentum_contribution
0,1,Bayern,64.86,87.19,30.52,4.53,17.94,6.88,5.00
1,1,Baden-Württemberg,64.86,80.94,28.33,7.66,18.25,5.62,5.00
2,3,Hessen,63.94,79.38,27.78,6.41,17.88,6.25,5.62
3,4,Nordrhein-Westfalen,62.76,49.22,17.23,20.78,14.12,8.12,2.50
4,5,Hamburg,61.55,67.66,23.68,1.56,17.56,10.00,8.75
5,6,Bremen,56.31,42.50,14.87,13.44,14.25,8.75,5.00
6,7,Sachsen,55.62,56.88,19.91,23.59,4.62,3.12,4.38
7,8,Rheinland-Pfalz,52.00,55.00,19.25,14.69,12.44,1.25,4.38
8,9,Berlin,51.86,53.44,18.70,3.28,10.50,9.38,10.00
9,10,Saarland,49.89,37.81,13.23,18.28,9.94,4.38,4.06
10,11,Niedersachsen,49.23,52.19,18.27,12.03,8.00,5.00,5.94
11,12,Sachsen-Anhalt,47.28,36.25,12.69,24.84,4.12,1.88,3.75
12,13,Schleswig-Holstein,46.95,43.44,15.20,9.69,9.56,7.50,5.00
13,14,Brandenburg,44.38,36.88,12.91,13.28,6.62,3.75,7.81
14,15,Thüringen,40.39,45.31,15.86,17.97,1.25,2.50,2.81
15,16,Mecklenburg-Vorpommern,38.11,25.94,9.08,20.47,2.94,0.62,5.00

In [89]:
berlin_contributions = ranking_contributions[
    ranking_contributions["state_name"] == "Berlin"
]

display(berlin_contributions.round(2))

,overall_rank,state_name,opportunity_score,career_strength_score,career_strength_contribution,affordability_contribution,income_economic_contribution,digital_readiness_contribution,regional_momentum_contribution
8,9,Berlin,51.86,53.44,18.7,3.28,10.5,9.38,10.0

In [90]:
category_columns = list(DEFAULT_CATEGORY_WEIGHTS.keys())

ranking_explanation = (
    analysis_snapshot[
        [
            "overall_rank",
            "state_name",
            "opportunity_score",
            *category_columns,
            *contribution_columns
        ]
    ]
    .sort_values(
        by=[
            "opportunity_score",
            "career_strength_score"
        ],
        ascending=[
            False,
            False
        ]
    )
    .reset_index(drop=True)
)

display(ranking_explanation.round(2))

,overall_rank,state_name,opportunity_score,career_strength_score,affordability_score,income_economic_score,digital_readiness_score,regional_momentum_score,career_strength_contribution,affordability_contribution,income_economic_contribution,digital_readiness_contribution,regional_momentum_contribution
0,1,Bayern,64.86,87.19,18.12,89.69,68.75,50.00,30.52,4.53,17.94,6.88,5.00
1,1,Baden-Württemberg,64.86,80.94,30.62,91.25,56.25,50.00,28.33,7.66,18.25,5.62,5.00
2,3,Hessen,63.94,79.38,25.62,89.38,62.50,56.25,27.78,6.41,17.88,6.25,5.62
3,4,Nordrhein-Westfalen,62.76,49.22,83.12,70.62,81.25,25.00,17.23,20.78,14.12,8.12,2.50
4,5,Hamburg,61.55,67.66,6.25,87.81,100.00,87.50,23.68,1.56,17.56,10.00,8.75
5,6,Bremen,56.31,42.50,53.75,71.25,87.50,50.00,14.87,13.44,14.25,8.75,5.00
6,7,Sachsen,55.62,56.88,94.38,23.12,31.25,43.75,19.91,23.59,4.62,3.12,4.38
7,8,Rheinland-Pfalz,52.00,55.00,58.75,62.19,12.50,43.75,19.25,14.69,12.44,1.25,4.38
8,9,Berlin,51.86,53.44,13.12,52.50,93.75,100.00,18.70,3.28,10.50,9.38,10.00
9,10,Saarland,49.89,37.81,73.12,49.69,43.75,40.62,13.23,18.28,9.94,4.38,4.06
10,11,Niedersachsen,49.23,52.19,48.12,40.00,50.00,59.38,18.27,12.03,8.00,5.00,5.94
11,12,Sachsen-Anhalt,47.28,36.25,99.38,20.62,18.75,37.50,12.69,24.84,4.12,1.88,3.75
12,13,Schleswig-Holstein,46.95,43.44,38.75,47.81,75.00,50.00,15.20,9.69,9.56,7.50,5.00
13,14,Brandenburg,44.38,36.88,53.12,33.12,37.50,78.12,12.91,13.28,6.62,3.75,7.81
14,15,Thüringen,40.39,45.31,71.88,6.25,25.00,28.12,15.86,17.97,1.25,2.50,2.81
15,16,Mecklenburg-Vorpommern,38.11,25.94,81.88,14.69,6.25,50.00,9.08,20.47,2.94,0.62,5.00

In [91]:
import plotly.graph_objects as go


def apply_publication_style(
    fig: go.Figure,
    title: str,
    subtitle: str = "",
    x_title: str = "",
    y_title: str = "",
    height: int = 650
) -> go.Figure:
    """
    Apply a consistent publication-ready design to Plotly figures.
    """

    full_title = (
        f"<b>{title}</b>"
        f"<br><span style='font-size:14px;color:#5F6B7A'>"
        f"{subtitle}</span>"
    )

    fig.update_layout(
        title={
            "text": full_title,
            "x": 0,
            "xanchor": "left",
            "y": 0.97,
            "yanchor": "top"
        },
        font={
            "family": "Arial, sans-serif",
            "size": 14,
            "color": "#1F2933"
        },
        paper_bgcolor="white",
        plot_bgcolor="white",
        height=height,
        margin={
            "l": 165,
            "r": 50,
            "t": 110,
            "b": 70
        },
        showlegend=False,
        hoverlabel={
            "bgcolor": "white",
            "font_size": 13
        }
    )

    fig.update_xaxes(
        title=x_title,
        showgrid=False,
        zeroline=False,
        showline=True,
        linecolor="#D7DCE2",
        ticks="outside"
    )

    fig.update_yaxes(
        title=y_title,
        showgrid=False,
        zeroline=False,
        showline=False,
        ticks=""
    )

    return fig


print("Publication-ready Plotly style created.")

Publication-ready Plotly style created.

## Analytical Question 1

### Which German states offer the strongest overall balance of career prospects, affordability, income, digital readiness, and regional momentum?

This visual compares the 16 German states using the transparent composite opportunity score developed from the five analytical dimensions.

In [92]:
ranking_chart_data = (
    analysis_snapshot[
        [
            "state_name",
            "opportunity_score",
            "overall_rank",
            "career_strength_score",
            "affordability_score",
            "income_economic_score",
            "digital_readiness_score",
            "regional_momentum_score"
        ]
    ]
    .sort_values(
        [
            "opportunity_score",
            "career_strength_score"
        ],
        ascending=[
            True,
            True
        ]
    )
    .reset_index(drop=True)
)

# Highlight only the joint first-place states
ranking_chart_data["bar_colour"] = ranking_chart_data[
    "overall_rank"
].apply(
    lambda rank: "#0072B2" if rank == 1 else "#C4CBD4"
)

ranking_chart_data["score_label"] = (
    ranking_chart_data["opportunity_score"]
    .map(lambda value: f"{value:.1f}")
)

fig_1 = go.Figure()

fig_1.add_trace(
    go.Bar(
        x=ranking_chart_data["opportunity_score"],
        y=ranking_chart_data["state_name"],
        orientation="h",
        marker={
            "color": ranking_chart_data["bar_colour"]
        },
        text=ranking_chart_data["score_label"],
        textposition="outside",
        cliponaxis=False,
        customdata=ranking_chart_data[
            [
                "overall_rank",
                "career_strength_score",
                "affordability_score",
                "income_economic_score",
                "digital_readiness_score",
                "regional_momentum_score"
            ]
        ],
        hovertemplate=(
            "<b>%{y}</b><br>"
            "Overall score: %{x:.2f}<br>"
            "Rank: %{customdata[0]}<br>"
            "Career strength: %{customdata[1]:.1f}<br>"
            "Affordability: %{customdata[2]:.1f}<br>"
            "Income and economy: %{customdata[3]:.1f}<br>"
            "Digital readiness: %{customdata[4]:.1f}<br>"
            "Regional momentum: %{customdata[5]:.1f}"
            "<extra></extra>"
        )
    )
)

fig_1 = apply_publication_style(
    fig_1,
    title=(
        "Baden-Württemberg and Bayern jointly lead Germany’s "
        "career-opportunity ranking"
    ),
    subtitle=(
        "Composite 2022 score across career strength, affordability, "
        "income, digital readiness and regional momentum"
    ),
    x_title="Opportunity score (0–100)",
    y_title="",
    height=700
)

fig_1.update_xaxes(
    range=[
        0,
        ranking_chart_data["opportunity_score"].max() + 9
    ]
)

fig_1.add_annotation(
    x=0,
    y=-0.12,
    xref="paper",
    yref="paper",
    text=(
        "Source: INKAR 2025. Scores are relative comparisons between "
        "Germany’s 16 states, not absolute measures of quality."
    ),
    showarrow=False,
    xanchor="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_1.show()

In [93]:
FIGURE_FOLDER = (
    PROJECT_ROOT
    / "assets"
    / "figures"
)

FIGURE_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)

FIGURE_1_HTML = (
    FIGURE_FOLDER
    / "01_overall_opportunity_ranking.html"
)

FIGURE_1_PNG = (
    FIGURE_FOLDER
    / "01_overall_opportunity_ranking.png"
)

fig_1.write_html(
    FIGURE_1_HTML,
    include_plotlyjs="cdn"
)

print("Interactive HTML saved:", FIGURE_1_HTML.exists())

try:
    fig_1.write_image(
        FIGURE_1_PNG,
        width=1400,
        height=900,
        scale=2
    )

    print("PNG saved:", FIGURE_1_PNG.exists())

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

## Analytical Question 2

### Do German states with higher academic incomes also face higher asking rents?

This analysis compares median monthly income for employees with an academic qualification against asking rent per square metre. Population is used as contextual point size, while the highlighted quadrant identifies states with above-median income and below-median rent.

In [94]:
scatter_data = analysis_snapshot[
    [
        "state_name",
        "population",
        "asking_rent",
        "median_income_academic",
        "estimated_rent_50sqm",
        "rent_burden_50sqm_pct",
        "income_after_rent_50sqm",
        "income_to_rent_index",
        "opportunity_score"
    ]
].copy()

rent_median = scatter_data["asking_rent"].median()
income_median = scatter_data["median_income_academic"].median()

income_rent_correlation = scatter_data[
    [
        "asking_rent",
        "median_income_academic"
    ]
].corr().iloc[0, 1]

scatter_data["favourable_balance"] = (
    (scatter_data["asking_rent"] <= rent_median)
    & (
        scatter_data["median_income_academic"]
        >= income_median
    )
)

scatter_data["point_colour"] = np.where(
    scatter_data["favourable_balance"],
    "#0072B2",
    "#BFC7D1"
)

# Scale population into reasonable bubble sizes
scatter_data["point_size"] = (
    14
    + 28
    * np.sqrt(
        scatter_data["population"]
        / scatter_data["population"].max()
    )
)

print("Median asking rent:", rent_median)
print("Median academic income:", round(income_median, 2))
print(
    "Income-rent correlation:",
    round(income_rent_correlation, 2)
)

print("\nAbove-median income and below-median rent:")
print(
    scatter_data.loc[
        scatter_data["favourable_balance"],
        "state_name"
    ].to_list()
)

Median asking rent: 8.5
Median academic income: 5199.22
Income-rent correlation: 0.78

Above-median income and below-median rent:
['Nordrhein-Westfalen', 'Saarland']

In [95]:
trend_slope, trend_intercept = np.polyfit(
    scatter_data["asking_rent"],
    scatter_data["median_income_academic"],
    1
)

trend_x = np.linspace(
    scatter_data["asking_rent"].min(),
    scatter_data["asking_rent"].max(),
    100
)

trend_y = (
    trend_slope * trend_x
    + trend_intercept
)

label_states = {
    "Nordrhein-Westfalen": "top center",
    "Saarland": "bottom center",
    "Hamburg": "top left",
    "Berlin": "bottom right",
    "Bayern": "top right",
    "Baden-Württemberg": "bottom left"
}

scatter_data["display_label"] = (
    scatter_data["state_name"]
    .where(
        scatter_data["state_name"].isin(
            label_states.keys()
        ),
        ""
    )
)

scatter_data["text_position"] = (
    scatter_data["state_name"]
    .map(label_states)
    .fillna("top center")
)

fig_2 = go.Figure()

# Contextual trend line
fig_2.add_trace(
    go.Scatter(
        x=trend_x,
        y=trend_y,
        mode="lines",
        line={
            "color": "#929CAA",
            "width": 2,
            "dash": "dash"
        },
        hoverinfo="skip",
        showlegend=False
    )
)

# State observations
fig_2.add_trace(
    go.Scatter(
        x=scatter_data["asking_rent"],
        y=scatter_data["median_income_academic"],
        mode="markers+text",
        text=scatter_data["display_label"],
        textposition=scatter_data["text_position"],
        textfont={
            "size": 11,
            "color": "#374151"
        },
        marker={
            "size": scatter_data["point_size"],
            "color": scatter_data["point_colour"],
            "opacity": 0.9,
            "line": {
                "color": "white",
                "width": 1.5
            }
        },
        customdata=scatter_data[
            [
                "state_name",
                "population",
                "estimated_rent_50sqm",
                "rent_burden_50sqm_pct",
                "income_after_rent_50sqm",
                "income_to_rent_index",
                "opportunity_score"
            ]
        ],
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "Asking rent: €%{x:.0f} per m²<br>"
            "Academic median income: €%{y:,.0f} per month<br>"
            "Population: %{customdata[1]:,.0f}<br>"
            "Illustrative 50 m² rent: €%{customdata[2]:,.0f}<br>"
            "Illustrative rent burden: %{customdata[3]:.1f}%<br>"
            "Gross income after rent: €%{customdata[4]:,.0f}<br>"
            "Income-to-rent index: %{customdata[5]:.1f}<br>"
            "Opportunity score: %{customdata[6]:.1f}"
            "<extra></extra>"
        ),
        showlegend=False
    )
)

fig_2 = apply_publication_style(
    fig_2,
    title=(
        "Higher-income German states generally face higher rents, "
        "but value differs considerably"
    ),
    subtitle=(
        "Academic median monthly income versus asking rent per m² "
        "across Germany’s 16 states, 2022"
    ),
    x_title="Asking rent (€ per m²)",
    y_title="Median monthly gross income (€)",
    height=700
)

fig_2.update_layout(
    margin={
        "l": 90,
        "r": 60,
        "t": 115,
        "b": 90
    }
)

fig_2.update_xaxes(
    range=[
        scatter_data["asking_rent"].min() - 0.7,
        scatter_data["asking_rent"].max() + 0.7
    ],
    dtick=1
)

fig_2.update_yaxes(
    tickprefix="€",
    tickformat=",.0f",
    range=[
        scatter_data["median_income_academic"].min() - 180,
        scatter_data["median_income_academic"].max() + 180
    ]
)

# Median reference lines
fig_2.add_vline(
    x=rent_median,
    line_width=1,
    line_dash="dot",
    line_color="#C4CBD4"
)

fig_2.add_hline(
    y=income_median,
    line_width=1,
    line_dash="dot",
    line_color="#C4CBD4"
)

# Explain the highlighted quadrant
fig_2.add_annotation(
    x=0.02,
    y=0.97,
    xref="paper",
    yref="paper",
    text=(
        "<b>Favourable balance</b><br>"
        "Above-median income<br>"
        "and below-median rent"
    ),
    showarrow=False,
    xanchor="left",
    yanchor="top",
    align="left",
    font={
        "size": 12,
        "color": "#0072B2"
    },
    bgcolor="rgba(255,255,255,0.85)",
    borderpad=5
)

fig_2.add_annotation(
    x=0.99,
    y=0.02,
    xref="paper",
    yref="paper",
    text=(
        f"Pearson correlation: "
        f"{income_rent_correlation:.2f}"
    ),
    showarrow=False,
    xanchor="right",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_2.add_annotation(
    x=0,
    y=-0.16,
    xref="paper",
    yref="paper",
    text=(
        "Bubble size represents population. Highlighting identifies "
        "states above the median income and at or below median rent. "
        "Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_2.show()

In [96]:
FIGURE_2_HTML = (
    FIGURE_FOLDER
    / "02_income_vs_rent.html"
)

FIGURE_2_PNG = (
    FIGURE_FOLDER
    / "02_income_vs_rent.png"
)

fig_2.write_html(
    FIGURE_2_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_2_HTML.exists()
)

try:
    fig_2.write_image(
        FIGURE_2_PNG,
        width=1400,
        height=900,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_2_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

### Finding

Academic income and asking rent have a strong positive relationship across German states, with a Pearson correlation of approximately **0.78**. This means that states offering higher academic incomes also tend to have more expensive rental markets.

However, the relationship is not uniform. **North Rhine-Westphalia and Saarland** combine above-median academic income with below-median asking rent. By contrast, Hamburg provides strong income and economic performance but has the highest asking rent in the comparison.

This demonstrates why salary alone is insufficient for evaluating regional career opportunity: housing costs can materially change the attractiveness of a location.

## Analytical Question 3

### Which German states provide the strongest salary-to-rent opportunity for academically qualified workers?

This comparison estimates the share of median monthly gross academic income required to cover the asking rent for an illustrative 50 m² apartment. A lower percentage indicates a more favourable income-to-rent balance.

The measure is a standardised comparison rather than an estimate of an individual's actual housing costs.

In [97]:
affordability_chart_data = (
    analysis_snapshot[
        [
            "state_name",
            "median_income_academic",
            "asking_rent",
            "estimated_rent_50sqm",
            "rent_burden_50sqm_pct",
            "income_after_rent_50sqm",
            "income_to_rent_index",
            "affordability_score"
        ]
    ]
    .sort_values(
        "rent_burden_50sqm_pct",
        ascending=False
    )
    .reset_index(drop=True)
)

median_rent_burden = affordability_chart_data[
    "rent_burden_50sqm_pct"
].median()

# Identify the three strongest income-to-rent balances
top_affordable_states = set(
    affordability_chart_data
    .nsmallest(
        3,
        "rent_burden_50sqm_pct"
    )["state_name"]
)

affordability_chart_data["bar_colour"] = (
    affordability_chart_data["state_name"]
    .apply(
        lambda state: (
            "#0072B2"
            if state in top_affordable_states
            else "#C4CBD4"
        )
    )
)

affordability_chart_data["burden_label"] = (
    affordability_chart_data[
        "rent_burden_50sqm_pct"
    ]
    .map(lambda value: f"{value:.1f}%")
)

print(
    "Median illustrative rent burden:",
    f"{median_rent_burden:.2f}%"
)

print(
    "Strongest salary-to-rent states:",
    sorted(top_affordable_states)
)

Median illustrative rent burden: 8.41%
Strongest salary-to-rent states: ['Nordrhein-Westfalen', 'Sachsen', 'Sachsen-Anhalt']

In [98]:
fig_3 = go.Figure()

fig_3.add_trace(
    go.Bar(
        x=affordability_chart_data[
            "rent_burden_50sqm_pct"
        ],
        y=affordability_chart_data[
            "state_name"
        ],
        orientation="h",
        marker={
            "color": affordability_chart_data[
                "bar_colour"
            ]
        },
        text=affordability_chart_data[
            "burden_label"
        ],
        textposition="outside",
        cliponaxis=False,
        customdata=affordability_chart_data[
            [
                "median_income_academic",
                "asking_rent",
                "estimated_rent_50sqm",
                "income_after_rent_50sqm",
                "income_to_rent_index",
                "affordability_score"
            ]
        ],
        hovertemplate=(
            "<b>%{y}</b><br>"
            "Illustrative rent burden: %{x:.2f}%<br>"
            "Academic median income: €%{customdata[0]:,.0f} per month<br>"
            "Asking rent: €%{customdata[1]:.0f} per m²<br>"
            "Illustrative 50 m² rent: €%{customdata[2]:,.0f}<br>"
            "Gross income after rent: €%{customdata[3]:,.0f}<br>"
            "Income-to-rent index: %{customdata[4]:.1f}<br>"
            "Affordability score: %{customdata[5]:.1f}"
            "<extra></extra>"
        )
    )
)

fig_3 = apply_publication_style(
    fig_3,
    title=(
        "Saxony, Saxony-Anhalt and North Rhine-Westphalia "
        "offer the strongest income-to-rent balance"
    ),
    subtitle=(
        "Illustrative share of median gross academic income required "
        "for the asking rent of a 50 m² apartment, 2022"
    ),
    x_title="Illustrative rent burden (% of gross monthly income)",
    y_title="",
    height=720
)

fig_3.update_layout(
    margin={
        "l": 180,
        "r": 65,
        "t": 115,
        "b": 95
    }
)

fig_3.update_xaxes(
    ticksuffix="%",
    range=[
        0,
        affordability_chart_data[
            "rent_burden_50sqm_pct"
        ].max() + 2
    ]
)

# Median reference line
fig_3.add_vline(
    x=median_rent_burden,
    line_width=1.5,
    line_dash="dot",
    line_color="#7B8794"
)

fig_3.add_annotation(
    x=median_rent_burden,
    y=1.01,
    xref="x",
    yref="paper",
    text=(
        f"State median: "
        f"{median_rent_burden:.1f}%"
    ),
    showarrow=False,
    xanchor="center",
    yanchor="bottom",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_3.add_annotation(
    x=0,
    y=-0.15,
    xref="paper",
    yref="paper",
    text=(
        "Calculation: asking rent per m² × 50 m² ÷ median monthly "
        "gross income for academically qualified employees. "
        "Actual rent burdens vary by household, city, taxes and apartment size. "
        "Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_3.show()

In [99]:
FIGURE_3_HTML = (
    FIGURE_FOLDER
    / "03_salary_to_rent_opportunity.html"
)

FIGURE_3_PNG = (
    FIGURE_FOLDER
    / "03_salary_to_rent_opportunity.png"
)

fig_3.write_html(
    FIGURE_3_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_3_HTML.exists()
)

try:
    fig_3.write_image(
        FIGURE_3_PNG,
        width=1400,
        height=950,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_3_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

### Finding

The strongest salary-to-rent balances are found in **Saxony-Anhalt, Saxony and North Rhine-Westphalia**. In the two eastern states, the asking rent for an illustrative 50 m² apartment represents approximately **6.4% of median monthly gross academic income**.

Hamburg and Berlin show the highest illustrative burdens, at approximately **11.7% and 11.6%**, respectively. Their stronger digital ecosystems and regional momentum therefore come with a material housing-cost trade-off.

North Rhine-Westphalia is particularly notable because it combines relatively affordable housing with stronger academic income than most other low-rent states. This helps explain its fourth-place position in the overall opportunity ranking.

## Analytical Question 4

### Which German states combine low unemployment with a strong concentration of IT and science-service employment?

This analysis identifies states that simultaneously maintain a below-median unemployment rate and an above-median share of employment in IT and natural-science service occupations. Expert-level employment provides additional context for the depth of each regional labour market.

In [101]:
career_market_data = analysis_snapshot[
    [
        "state_name",
        "population",
        "unemployment_rate",
        "employment_rate",
        "expert_level_employment",
        "it_science_service_employment",
        "knowledge_intensive_industry",
        "career_strength_score",
        "opportunity_score"
    ]
].copy()

median_unemployment = career_market_data[
    "unemployment_rate"
].median()

median_it_employment = career_market_data[
    "it_science_service_employment"
].median()

career_market_data["strong_career_market"] = (
    career_market_data["unemployment_rate"]
    <= median_unemployment
) & (
    career_market_data["it_science_service_employment"]
    >= median_it_employment
)

career_market_data["market_category"] = np.select(
    [
        (
            career_market_data["unemployment_rate"]
            <= median_unemployment
        )
        & (
            career_market_data[
                "it_science_service_employment"
            ]
            >= median_it_employment
        ),
        (
            career_market_data["unemployment_rate"]
            > median_unemployment
        )
        & (
            career_market_data[
                "it_science_service_employment"
            ]
            >= median_it_employment
        ),
        (
            career_market_data["unemployment_rate"]
            <= median_unemployment
        )
        & (
            career_market_data[
                "it_science_service_employment"
            ]
            < median_it_employment
        )
    ],
    [
        "Strong career market",
        "Specialised but higher unemployment",
        "Low unemployment, smaller IT base"
    ],
    default="Currently constrained"
)

career_market_data["point_colour"] = np.where(
    career_market_data["strong_career_market"],
    "#0072B2",
    "#C4CBD4"
)

# Use expert-level employment for bubble sizing
career_market_data["point_size"] = (
    15
    + 25
    * (
        career_market_data["expert_level_employment"]
        - career_market_data["expert_level_employment"].min()
    )
    / (
        career_market_data["expert_level_employment"].max()
        - career_market_data["expert_level_employment"].min()
    )
)

print(
    "Median unemployment rate:",
    round(median_unemployment, 2)
)

print(
    "Median IT and science-service employment:",
    round(median_it_employment, 2)
)

print("\nStates in the strong-career-market quadrant:")

strong_career_markets = (
    career_market_data.loc[
        career_market_data["strong_career_market"],
        [
            "state_name",
            "unemployment_rate",
            "it_science_service_employment",
            "expert_level_employment",
            "career_strength_score"
        ]
    ]
    .sort_values(
        "career_strength_score",
        ascending=False
    )
    .reset_index(drop=True)
)

print(
    strong_career_markets[
        [
            "state_name",
            "unemployment_rate",
            "it_science_service_employment",
            "expert_level_employment",
            "career_strength_score"
        ]
    ]
    .round(2)
    .to_string(index=False)
)

Median unemployment rate: 5.59
Median IT and science-service employment: 3.66

States in the strong-career-market quadrant:
       state_name  unemployment_rate  it_science_service_employment  expert_level_employment  career_strength_score
           Bayern               3.13                           4.73                    15.19                  87.19
Baden-Württemberg               3.54                           4.99                    14.30                  80.94
           Hessen               4.77                           5.49                    15.65                  79.38
  Rheinland-Pfalz               4.56                           3.80                    11.01                  55.00

In [102]:
label_states = {
    "Bayern": "top left",
    "Baden-Württemberg": "top right",
    "Hessen": "bottom right",
    "Hamburg": "top left",
    "Berlin": "top right",
    "Nordrhein-Westfalen": "bottom right",
    "Mecklenburg-Vorpommern": "bottom left"
}

career_market_data["display_label"] = (
    career_market_data["state_name"]
    .where(
        career_market_data["state_name"].isin(
            label_states
        ),
        ""
    )
)

career_market_data["text_position"] = (
    career_market_data["state_name"]
    .map(label_states)
    .fillna("top center")
)

fig_4 = go.Figure()

fig_4.add_trace(
    go.Scatter(
        x=career_market_data["unemployment_rate"],
        y=career_market_data[
            "it_science_service_employment"
        ],
        mode="markers+text",
        text=career_market_data["display_label"],
        textposition=career_market_data["text_position"],
        textfont={
            "size": 11,
            "color": "#374151"
        },
        marker={
            "size": career_market_data["point_size"],
            "color": career_market_data["point_colour"],
            "opacity": 0.9,
            "line": {
                "color": "white",
                "width": 1.5
            }
        },
        customdata=career_market_data[
            [
                "state_name",
                "employment_rate",
                "expert_level_employment",
                "knowledge_intensive_industry",
                "career_strength_score",
                "opportunity_score",
                "market_category"
            ]
        ],
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "Unemployment rate: %{x:.2f}%<br>"
            "IT and science-service employment: %{y:.2f}%<br>"
            "Employment rate: %{customdata[1]:.2f}%<br>"
            "Expert-level employment: %{customdata[2]:.2f}%<br>"
            "Knowledge-intensive industry: %{customdata[3]:.2f}%<br>"
            "Career-strength score: %{customdata[4]:.1f}<br>"
            "Overall opportunity score: %{customdata[5]:.1f}<br>"
            "Category: %{customdata[6]}"
            "<extra></extra>"
        ),
        showlegend=False
    )
)

fig_4 = apply_publication_style(
    fig_4,
    title=(
        "Southern states combine low unemployment with "
        "stronger specialist labour markets"
    ),
    subtitle=(
        "Unemployment versus employment in IT and "
        "natural-science service occupations, 2022"
    ),
    x_title="Unemployment rate (%)",
    y_title="IT and science-service employment (%)",
    height=700
)

fig_4.update_layout(
    margin={
        "l": 95,
        "r": 65,
        "t": 115,
        "b": 95
    }
)

fig_4.update_xaxes(
    ticksuffix="%",
    range=[
        career_market_data["unemployment_rate"].min() - 0.6,
        career_market_data["unemployment_rate"].max() + 0.6
    ]
)

fig_4.update_yaxes(
    ticksuffix="%",
    range=[
        career_market_data[
            "it_science_service_employment"
        ].min() - 0.5,
        career_market_data[
            "it_science_service_employment"
        ].max() + 0.7
    ]
)

# Median quadrant lines
fig_4.add_vline(
    x=median_unemployment,
    line_width=1.2,
    line_dash="dot",
    line_color="#A5ADB8"
)

fig_4.add_hline(
    y=median_it_employment,
    line_width=1.2,
    line_dash="dot",
    line_color="#A5ADB8"
)

# Highlight the preferred quadrant
fig_4.add_annotation(
    x=0.02,
    y=0.98,
    xref="paper",
    yref="paper",
    text=(
        "<b>Strong career market</b><br>"
        "Lower unemployment and<br>"
        "higher specialist employment"
    ),
    showarrow=False,
    xanchor="left",
    yanchor="top",
    align="left",
    font={
        "size": 12,
        "color": "#0072B2"
    },
    bgcolor="rgba(255,255,255,0.88)",
    borderpad=5
)

fig_4.add_annotation(
    x=0,
    y=-0.16,
    xref="paper",
    yref="paper",
    text=(
        "Bubble size represents the share of expert-level employment. "
        "Quadrants are defined using the median values of Germany’s "
        "16 states. Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_4.show()

In [103]:
FIGURE_4_HTML = (
    FIGURE_FOLDER
    / "04_career_market_quadrant.html"
)

FIGURE_4_PNG = (
    FIGURE_FOLDER
    / "04_career_market_quadrant.png"
)

fig_4.write_html(
    FIGURE_4_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_4_HTML.exists()
)

try:
    fig_4.write_image(
        FIGURE_4_PNG,
        width=1400,
        height=900,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_4_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

## Analytical Question 5

### Which German states strengthened both their employment rate and population between 2017 and 2022?

This analysis compares changes in employment participation with population growth over a consistent five-year period. States performing strongly on both dimensions may represent expanding labour markets, while states losing population or employment participation may face longer-term structural challenges.

In [104]:
START_YEAR = 2017
END_YEAR = 2022

progress_start = (
    state_year.loc[
        state_year["year"] == START_YEAR,
        [
            "state_code",
            "state_name",
            "population",
            "employment_rate"
        ]
    ]
    .rename(
        columns={
            "population": "population_2017",
            "employment_rate": "employment_rate_2017"
        }
    )
)

progress_end = (
    state_year.loc[
        state_year["year"] == END_YEAR,
        [
            "state_code",
            "state_name",
            "population",
            "employment_rate"
        ]
    ]
    .rename(
        columns={
            "population": "population_2022",
            "employment_rate": "employment_rate_2022"
        }
    )
)

regional_progress = progress_start.merge(
    progress_end,
    on=[
        "state_code",
        "state_name"
    ],
    how="inner",
    validate="one_to_one"
)

regional_progress["population_growth_pct"] = (
    (
        regional_progress["population_2022"]
        / regional_progress["population_2017"]
    )
    - 1
) * 100

regional_progress["employment_rate_change_pp"] = (
    regional_progress["employment_rate_2022"]
    - regional_progress["employment_rate_2017"]
)

print("Rows:", len(regional_progress))
print(
    "States:",
    regional_progress["state_code"].nunique()
)

display(
    regional_progress[
        [
            "state_name",
            "population_2017",
            "population_2022",
            "population_growth_pct",
            "employment_rate_2017",
            "employment_rate_2022",
            "employment_rate_change_pp"
        ]
    ]
    .sort_values(
        "population_growth_pct",
        ascending=False
    )
    .round(2)
)

Rows: 16
States: 16

,state_name,population_2017,population_2022,population_growth_pct,employment_rate_2017,employment_rate_2022,employment_rate_change_pp
3,Bremen,681032.0,695758.0,2.16,53.78,57.77,3.99
9,Saarland,994187.0,1011891.0,1.78,55.94,58.61,2.67
0,Schleswig-Holstein,2889821.0,2939283.0,1.71,57.37,62.20,4.83
11,Brandenburg,2504040.0,2545159.0,1.64,61.68,65.74,4.06
7,Baden-Württemberg,11023425.0,11167721.0,1.31,60.91,65.65,4.74
6,Rheinland-Pfalz,4073679.0,4108555.0,0.86,57.42,62.32,4.90
8,Bayern,12997204.0,13105221.0,0.83,62.33,67.90,5.57
10,Berlin,3613495.0,3632853.0,0.54,53.66,60.91,7.25
4,Nordrhein-Westfalen,17912134.0,17964420.0,0.29,56.40,61.83,5.43
2,Niedersachsen,7962775.0,7982947.0,0.25,58.79,64.46,5.67
1,Hamburg,1830584.0,1832675.0,0.11,59.06,64.88,5.82
5,Hessen,6243262.0,6236933.0,-0.10,58.50,63.91,5.41
13,Sachsen,4081308.0,4049967.0,-0.77,64.17,68.14,3.97
15,Thüringen,2151205.0,2118830.0,-1.50,64.06,67.29,3.23
12,Mecklenburg-Vorpommern,1611119.0,1576049.0,-2.18,59.96,65.89,5.93
14,Sachsen-Anhalt,2223081.0,2150239.0,-3.28,62.69,67.39,4.70

In [105]:
regional_progress["population_progress_score"] = (
    percentile_score(
        regional_progress["population_growth_pct"],
        higher_is_better=True
    )
)

regional_progress["employment_progress_score"] = (
    percentile_score(
        regional_progress["employment_rate_change_pp"],
        higher_is_better=True
    )
)

regional_progress["balanced_progress_score"] = (
    regional_progress["population_progress_score"] * 0.50
    + regional_progress["employment_progress_score"] * 0.50
)

regional_progress["progress_rank"] = (
    regional_progress["balanced_progress_score"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)

regional_progress["improved_both"] = (
    regional_progress["population_growth_pct"] > 0
) & (
    regional_progress["employment_rate_change_pp"] > 0
)

regional_progress["declined_both"] = (
    regional_progress["population_growth_pct"] < 0
) & (
    regional_progress["employment_rate_change_pp"] < 0
)

progress_ranking = (
    regional_progress[
        [
            "progress_rank",
            "state_name",
            "population_growth_pct",
            "employment_rate_change_pp",
            "balanced_progress_score",
            "improved_both"
        ]
    ]
    .sort_values(
        [
            "balanced_progress_score",
            "population_growth_pct"
        ],
        ascending=[
            False,
            False
        ]
    )
    .reset_index(drop=True)
)

print("Top five states by balanced progress:")

print(
    progress_ranking
    .head(5)
    .round(2)
    .to_string(index=False)
)

print("\nStates where both measures declined:")

print(
    regional_progress.loc[
        regional_progress["declined_both"],
        [
            "state_name",
            "population_growth_pct",
            "employment_rate_change_pp"
        ]
    ]
    .round(2)
    .to_string(index=False)
)

Top five states by balanced progress:
 progress_rank         state_name  population_growth_pct  employment_rate_change_pp  balanced_progress_score  improved_both
             1             Berlin                   0.54                       7.25                    78.12           True
             2 Schleswig-Holstein                   1.71                       4.83                    68.75           True
             2             Bayern                   0.83                       5.57                    68.75           True
             4             Bremen                   2.16                       3.99                    62.50           True
             4    Rheinland-Pfalz                   0.86                       4.90                    62.50           True

States where both measures declined:
Empty DataFrame
Columns: [state_name, population_growth_pct, employment_rate_change_pp]
Index: []

In [106]:
top_progress_states = set(
    regional_progress
    .nlargest(
        4,
        "balanced_progress_score"
    )["state_name"]
)

regional_progress["point_colour"] = np.where(
    regional_progress["state_name"].isin(
        top_progress_states
    ),
    "#0072B2",
    "#C4CBD4"
)

regional_progress["point_size"] = (
    14
    + 28
    * np.sqrt(
        regional_progress["population_2022"]
        / regional_progress["population_2022"].max()
    )
)

# Label the strongest states and any state declining on both measures
regional_progress["show_label"] = (
    regional_progress["state_name"].isin(
        top_progress_states
    )
    | regional_progress["declined_both"]
)

regional_progress["display_label"] = (
    regional_progress["state_name"]
    .where(
        regional_progress["show_label"],
        ""
    )
)

label_positions = {
    "Berlin": "top right",
    "Hamburg": "top left",
    "Bayern": "bottom right",
    "Baden-Württemberg": "bottom left",
    "Brandenburg": "top right",
    "Mecklenburg-Vorpommern": "bottom left",
    "Sachsen-Anhalt": "bottom right",
    "Thüringen": "top left"
}

regional_progress["text_position"] = (
    regional_progress["state_name"]
    .map(label_positions)
    .fillna("top center")
)

top_progress_name = (
    regional_progress
    .sort_values(
        "balanced_progress_score",
        ascending=False
    )
    .iloc[0]["state_name"]
)

fig_5 = go.Figure()

fig_5.add_trace(
    go.Scatter(
        x=regional_progress[
            "population_growth_pct"
        ],
        y=regional_progress[
            "employment_rate_change_pp"
        ],
        mode="markers+text",
        text=regional_progress["display_label"],
        textposition=regional_progress[
            "text_position"
        ],
        textfont={
            "size": 11,
            "color": "#374151"
        },
        marker={
            "size": regional_progress["point_size"],
            "color": regional_progress[
                "point_colour"
            ],
            "opacity": 0.9,
            "line": {
                "color": "white",
                "width": 1.5
            }
        },
        customdata=regional_progress[
            [
                "state_name",
                "population_2017",
                "population_2022",
                "employment_rate_2017",
                "employment_rate_2022",
                "balanced_progress_score",
                "progress_rank"
            ]
        ],
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "Population growth: %{x:.2f}%<br>"
            "Employment-rate change: %{y:+.2f} percentage points<br>"
            "Population in 2017: %{customdata[1]:,.0f}<br>"
            "Population in 2022: %{customdata[2]:,.0f}<br>"
            "Employment rate in 2017: %{customdata[3]:.2f}%<br>"
            "Employment rate in 2022: %{customdata[4]:.2f}%<br>"
            "Balanced progress score: %{customdata[5]:.1f}<br>"
            "Progress rank: %{customdata[6]}"
            "<extra></extra>"
        ),
        showlegend=False
    )
)

fig_5 = apply_publication_style(
    fig_5,
    title=(
        f"{top_progress_name} leads the strongest combination "
        "of population and employment progress"
    ),
    subtitle=(
        "Change in population and employment rate across "
        "Germany’s 16 states, 2017–2022"
    ),
    x_title="Population change, 2017–2022 (%)",
    y_title="Employment-rate change (percentage points)",
    height=700
)

fig_5.update_layout(
    margin={
        "l": 100,
        "r": 70,
        "t": 115,
        "b": 100
    }
)

fig_5.update_xaxes(
    ticksuffix="%",
    zeroline=False
)

fig_5.update_yaxes(
    ticksuffix=" pp",
    zeroline=False
)

# Zero reference lines separate growth from decline
fig_5.add_vline(
    x=0,
    line_width=1.3,
    line_dash="dot",
    line_color="#919AA6"
)

fig_5.add_hline(
    y=0,
    line_width=1.3,
    line_dash="dot",
    line_color="#919AA6"
)

fig_5.add_annotation(
    x=0.98,
    y=0.97,
    xref="paper",
    yref="paper",
    text=(
        "<b>Dual progress</b><br>"
        "Population and employment<br>"
        "both increased"
    ),
    showarrow=False,
    xanchor="right",
    yanchor="top",
    align="right",
    font={
        "size": 12,
        "color": "#0072B2"
    },
    bgcolor="rgba(255,255,255,0.88)",
    borderpad=5
)

fig_5.add_annotation(
    x=0,
    y=-0.17,
    xref="paper",
    yref="paper",
    text=(
        "Bubble size represents 2022 population. Highlighted states "
        "have the four strongest combined percentile scores across "
        "population growth and employment-rate improvement. "
        "Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_5.show()

In [107]:
FIGURE_5_HTML = (
    FIGURE_FOLDER
    / "05_population_employment_progress.html"
)

FIGURE_5_PNG = (
    FIGURE_FOLDER
    / "05_population_employment_progress.png"
)

fig_5.write_html(
    FIGURE_5_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_5_HTML.exists()
)

try:
    fig_5.write_image(
        FIGURE_5_PNG,
        width=1400,
        height=900,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_5_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

### Finding

Berlin achieved the strongest balanced progress between 2017 and 2022. Its population increased modestly by **0.54%**, but its employment rate rose by **7.25 percentage points**, the strongest labour-market improvement among the leading states.

Schleswig-Holstein and Bavaria share second place, although their progress followed different patterns. Schleswig-Holstein recorded stronger population growth, while Bavaria delivered a larger employment-rate increase.

Bremen had the highest population increase among the top five states, at **2.16%**, but its smaller improvement in employment participation prevented it from taking the top position.

These results show that regional progress is multidimensional: population expansion alone does not necessarily indicate a strengthening labour market.

## Analytical Question 6

### Is stronger broadband infrastructure associated with a larger IT and science-service workforce?

This analysis compares the availability of broadband speeds of at least 100 Mbit/s with the share of employees working in IT and natural-science service occupations. It tests whether digitally connected states also tend to support deeper specialist labour markets.

In [108]:
digital_labour_data = analysis_snapshot[
    [
        "state_name",
        "population",
        "broadband_100mbit",
        "it_science_service_employment",
        "expert_level_employment",
        "career_strength_score",
        "digital_readiness_score",
        "opportunity_score"
    ]
].copy()

median_broadband = digital_labour_data[
    "broadband_100mbit"
].median()

median_it_employment = digital_labour_data[
    "it_science_service_employment"
].median()

broadband_it_correlation = digital_labour_data[
    [
        "broadband_100mbit",
        "it_science_service_employment"
    ]
].corr().iloc[0, 1]

digital_labour_data["strong_digital_labour_market"] = (
    digital_labour_data["broadband_100mbit"]
    >= median_broadband
) & (
    digital_labour_data["it_science_service_employment"]
    >= median_it_employment
)

digital_labour_data["point_colour"] = np.where(
    digital_labour_data[
        "strong_digital_labour_market"
    ],
    "#0072B2",
    "#C4CBD4"
)

digital_labour_data["point_size"] = (
    15
    + 25
    * (
        digital_labour_data["expert_level_employment"]
        - digital_labour_data[
            "expert_level_employment"
        ].min()
    )
    / (
        digital_labour_data[
            "expert_level_employment"
        ].max()
        - digital_labour_data[
            "expert_level_employment"
        ].min()
    )
)

print(
    "Median broadband availability:",
    round(median_broadband, 2)
)

print(
    "Median IT and science-service employment:",
    round(median_it_employment, 2)
)

print(
    "Broadband–IT employment correlation:",
    round(broadband_it_correlation, 2)
)

print("\nStates above both medians:")

print(
    digital_labour_data.loc[
        digital_labour_data[
            "strong_digital_labour_market"
        ],
        [
            "state_name",
            "broadband_100mbit",
            "it_science_service_employment",
            "expert_level_employment"
        ]
    ]
    .sort_values(
        "it_science_service_employment",
        ascending=False
    )
    .round(2)
    .to_string(index=False)
)

Median broadband availability: 88.22
Median IT and science-service employment: 3.66
Broadband–IT employment correlation: 0.75

States above both medians:
         state_name  broadband_100mbit  it_science_service_employment  expert_level_employment
            Hamburg              99.09                           6.03                    19.55
             Hessen              89.98                           5.49                    15.65
             Berlin              98.49                           5.26                    20.89
  Baden-Württemberg              88.86                           4.99                    14.30
             Bayern              91.03                           4.73                    15.19
Nordrhein-Westfalen              93.84                           4.37                    13.33
             Bremen              96.45                           4.36                    14.84

In [109]:
trend_slope, trend_intercept = np.polyfit(
    digital_labour_data["broadband_100mbit"],
    digital_labour_data[
        "it_science_service_employment"
    ],
    1
)

trend_x = np.linspace(
    digital_labour_data["broadband_100mbit"].min(),
    digital_labour_data["broadband_100mbit"].max(),
    100
)

trend_y = (
    trend_slope * trend_x
    + trend_intercept
)

label_positions = {
    "Hamburg": "top left",
    "Berlin": "bottom right",
    "Hessen": "top right",
    "Baden-Württemberg": "bottom left",
    "Bayern": "top left",
    "Mecklenburg-Vorpommern": "bottom right",
    "Schleswig-Holstein": "bottom left"
}

digital_labour_data["display_label"] = (
    digital_labour_data["state_name"]
    .where(
        digital_labour_data["state_name"].isin(
            label_positions
        ),
        ""
    )
)

digital_labour_data["text_position"] = (
    digital_labour_data["state_name"]
    .map(label_positions)
    .fillna("top center")
)

fig_6 = go.Figure()

fig_6.add_trace(
    go.Scatter(
        x=trend_x,
        y=trend_y,
        mode="lines",
        line={
            "color": "#929CAA",
            "width": 2,
            "dash": "dash"
        },
        hoverinfo="skip",
        showlegend=False
    )
)

fig_6.add_trace(
    go.Scatter(
        x=digital_labour_data[
            "broadband_100mbit"
        ],
        y=digital_labour_data[
            "it_science_service_employment"
        ],
        mode="markers+text",
        text=digital_labour_data[
            "display_label"
        ],
        textposition=digital_labour_data[
            "text_position"
        ],
        textfont={
            "size": 11,
            "color": "#374151"
        },
        marker={
            "size": digital_labour_data[
                "point_size"
            ],
            "color": digital_labour_data[
                "point_colour"
            ],
            "opacity": 0.9,
            "line": {
                "color": "white",
                "width": 1.5
            }
        },
        customdata=digital_labour_data[
            [
                "state_name",
                "expert_level_employment",
                "career_strength_score",
                "digital_readiness_score",
                "opportunity_score"
            ]
        ],
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "100 Mbit/s broadband: %{x:.2f}%<br>"
            "IT and science-service employment: %{y:.2f}%<br>"
            "Expert-level employment: %{customdata[1]:.2f}%<br>"
            "Career-strength score: %{customdata[2]:.1f}<br>"
            "Digital-readiness score: %{customdata[3]:.1f}<br>"
            "Overall opportunity score: %{customdata[4]:.1f}"
            "<extra></extra>"
        ),
        showlegend=False
    )
)

fig_6 = apply_publication_style(
    fig_6,
    title=(
        "Digitally connected states generally support "
        "larger specialist workforces"
    ),
    subtitle=(
        "Broadband availability versus employment in IT and "
        "natural-science service occupations, 2022"
    ),
    x_title="Households with at least 100 Mbit/s broadband (%)",
    y_title="IT and science-service employment (%)",
    height=700
)

fig_6.update_layout(
    margin={
        "l": 100,
        "r": 65,
        "t": 115,
        "b": 100
    }
)

fig_6.update_xaxes(
    ticksuffix="%",
    range=[
        digital_labour_data[
            "broadband_100mbit"
        ].min() - 2,
        digital_labour_data[
            "broadband_100mbit"
        ].max() + 2
    ]
)

fig_6.update_yaxes(
    ticksuffix="%",
    range=[
        digital_labour_data[
            "it_science_service_employment"
        ].min() - 0.5,
        digital_labour_data[
            "it_science_service_employment"
        ].max() + 0.7
    ]
)

fig_6.add_vline(
    x=median_broadband,
    line_width=1.2,
    line_dash="dot",
    line_color="#A5ADB8"
)

fig_6.add_hline(
    y=median_it_employment,
    line_width=1.2,
    line_dash="dot",
    line_color="#A5ADB8"
)

fig_6.add_annotation(
    x=0.98,
    y=0.97,
    xref="paper",
    yref="paper",
    text=(
        "<b>Strong digital labour market</b><br>"
        "Above-median connectivity and<br>"
        "specialist employment"
    ),
    showarrow=False,
    xanchor="right",
    yanchor="top",
    align="right",
    font={
        "size": 12,
        "color": "#0072B2"
    },
    bgcolor="rgba(255,255,255,0.88)",
    borderpad=5
)

fig_6.add_annotation(
    x=0.02,
    y=0.03,
    xref="paper",
    yref="paper",
    text=(
        f"Pearson correlation: "
        f"{broadband_it_correlation:.2f}"
    ),
    showarrow=False,
    xanchor="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_6.add_annotation(
    x=0,
    y=-0.17,
    xref="paper",
    yref="paper",
    text=(
        "Bubble size represents expert-level employment. "
        "The relationship is associative and does not establish that "
        "broadband availability causes specialist employment. "
        "Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_6.show()

In [110]:
FIGURE_6_HTML = (
    FIGURE_FOLDER
    / "06_broadband_vs_specialist_employment.html"
)

FIGURE_6_PNG = (
    FIGURE_FOLDER
    / "06_broadband_vs_specialist_employment.png"
)

fig_6.write_html(
    FIGURE_6_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_6_HTML.exists()
)

try:
    fig_6.write_image(
        FIGURE_6_PNG,
        width=1400,
        height=900,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_6_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

### Finding

Broadband availability and employment in IT and natural-science service occupations show a strong positive association, with a Pearson correlation of approximately **0.75**.

Seven states exceed the national-state median on both measures: **Hamburg, Hesse, Berlin, Baden-Württemberg, Bavaria, North Rhine-Westphalia and Bremen**.

Hamburg has the largest IT and science-service workforce share at **6.03%**, alongside broadband availability of **99.09%**. Berlin has the highest share of expert-level employment, while also achieving near-universal high-speed broadband coverage.

However, this relationship should not be interpreted as causal. Strong digital infrastructure may support specialist employment, but both measures can also reflect urbanisation, industrial structure, investment and the presence of universities or technology firms.

## Analytical Question 7

### Do Germany’s most economically productive states remain attractive after housing costs are considered?

This analysis compares each state's GDP-per-capita ranking with its income-to-rent affordability ranking. The rank-change view shows which states lose attractiveness once housing costs are considered, and which lower-productivity states become more competitive because of affordability.

In [111]:
productivity_affordability = analysis_snapshot[
    [
        "state_name",
        "gdp_per_capita_eur",
        "median_income_academic",
        "asking_rent",
        "rent_burden_50sqm_pct",
        "income_after_rent_50sqm",
        "affordability_score",
        "opportunity_score"
    ]
].copy()

# Higher GDP per capita is better
productivity_affordability["productivity_rank"] = (
    productivity_affordability["gdp_per_capita_eur"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)

# Lower illustrative rent burden is better
productivity_affordability["affordability_rank"] = (
    productivity_affordability["rent_burden_50sqm_pct"]
    .rank(
        ascending=True,
        method="min"
    )
    .astype(int)
)

# Positive values mean the state improves after housing costs are considered
productivity_affordability["rank_shift_after_costs"] = (
    productivity_affordability["productivity_rank"]
    - productivity_affordability["affordability_rank"]
)

productivity_affordability["absolute_rank_shift"] = (
    productivity_affordability[
        "rank_shift_after_costs"
    ].abs()
)

largest_affordability_gains = (
    productivity_affordability
    .sort_values(
        "rank_shift_after_costs",
        ascending=False
    )
    .head(5)
)

largest_affordability_losses = (
    productivity_affordability
    .sort_values(
        "rank_shift_after_costs",
        ascending=True
    )
    .head(5)
)

print("Largest improvements after housing costs are considered:")

print(
    largest_affordability_gains[
        [
            "state_name",
            "productivity_rank",
            "affordability_rank",
            "rank_shift_after_costs"
        ]
    ]
    .to_string(index=False)
)

print("\nLargest declines after housing costs are considered:")

print(
    largest_affordability_losses[
        [
            "state_name",
            "productivity_rank",
            "affordability_rank",
            "rank_shift_after_costs"
        ]
    ]
    .to_string(index=False)
)

Largest improvements after housing costs are considered:
            state_name  productivity_rank  affordability_rank  rank_shift_after_costs
        Sachsen-Anhalt                 15                   1                      14
Mecklenburg-Vorpommern                 14                   4                      10
               Sachsen                 12                   2                      10
             Thüringen                 16                   6                      10
              Saarland                 11                   5                       6

Largest declines after housing costs are considered:
       state_name  productivity_rank  affordability_rank  rank_shift_after_costs
          Hamburg                  1                  16                     -15
           Bayern                  2                  14                     -12
           Hessen                  4                  13                      -9
           Berlin                  6                  15                      -9
Baden-Württemberg                  5                  12                      -7

In [112]:
# Highlight states with a very large rank shift
MAJOR_SHIFT_THRESHOLD = 9

productivity_affordability["major_shift"] = (
    productivity_affordability[
        "absolute_rank_shift"
    ] >= MAJOR_SHIFT_THRESHOLD
)

fig_7 = go.Figure()

for _, row in productivity_affordability.iterrows():

    line_colour = (
        "#0072B2"
        if row["major_shift"]
        else "#D1D6DC"
    )

    line_width = (
        3
        if row["major_shift"]
        else 1.5
    )

    marker_size = (
        9
        if row["major_shift"]
        else 6
    )

    fig_7.add_trace(
        go.Scatter(
            x=[0, 1],
            y=[
                row["productivity_rank"],
                row["affordability_rank"]
            ],
            mode="lines+markers+text",
            line={
                "color": line_colour,
                "width": line_width
            },
            marker={
                "size": marker_size,
                "color": line_colour,
                "line": {
                    "color": "white",
                    "width": 1
                }
            },
            text=[
                row["state_name"],
                row["state_name"]
            ],
            textposition=[
                "middle left",
                "middle right"
            ],
            textfont={
                "size": (
                    11
                    if row["major_shift"]
                    else 9
                ),
                "color": (
                    "#1F2933"
                    if row["major_shift"]
                    else "#7B8490"
                )
            },
            customdata=[
                [
                    row["state_name"],
                    row["gdp_per_capita_eur"],
                    row["rent_burden_50sqm_pct"],
                    row["rank_shift_after_costs"],
                    row["opportunity_score"]
                ],
                [
                    row["state_name"],
                    row["gdp_per_capita_eur"],
                    row["rent_burden_50sqm_pct"],
                    row["rank_shift_after_costs"],
                    row["opportunity_score"]
                ]
            ],
            hovertemplate=(
                "<b>%{customdata[0]}</b><br>"
                "Displayed rank: %{y}<br>"
                "GDP per capita: €%{customdata[1]:,.0f}<br>"
                "Illustrative rent burden: %{customdata[2]:.2f}%<br>"
                "Rank shift after housing costs: "
                "%{customdata[3]:+d}<br>"
                "Overall opportunity score: %{customdata[4]:.1f}"
                "<extra></extra>"
            ),
            showlegend=False
        )
    )

fig_7.update_layout(
    title={
        "text": (
            "<b>Housing costs reverse the economic ranking "
            "of several German states</b>"
            "<br><span style='font-size:14px;color:#5F6B7A'>"
            "GDP-per-capita rank compared with illustrative "
            "income-to-rent affordability rank, 2022"
            "</span>"
        ),
        "x": 0,
        "xanchor": "left",
        "y": 0.97,
        "yanchor": "top"
    },
    font={
        "family": "Arial, sans-serif",
        "size": 14,
        "color": "#1F2933"
    },
    paper_bgcolor="white",
    plot_bgcolor="white",
    height=760,
    margin={
        "l": 190,
        "r": 190,
        "t": 120,
        "b": 100
    },
    showlegend=False,
    hoverlabel={
        "bgcolor": "white",
        "font_size": 13
    }
)

fig_7.update_xaxes(
    range=[-0.16, 1.16],
    tickmode="array",
    tickvals=[0, 1],
    ticktext=[
        "<b>Economic productivity</b><br>GDP per capita rank",
        "<b>Housing affordability</b><br>Income-to-rent rank"
    ],
    tickfont={
        "size": 13
    },
    showgrid=False,
    zeroline=False,
    showline=False
)

fig_7.update_yaxes(
    title="Rank among Germany’s 16 states",
    range=[16.7, 0.3],
    tickmode="linear",
    tick0=1,
    dtick=1,
    showgrid=True,
    gridcolor="#EEF1F4",
    gridwidth=1,
    zeroline=False,
    showline=False
)

fig_7.add_annotation(
    x=0.5,
    y=-0.15,
    xref="paper",
    yref="paper",
    text=(
        "Blue lines highlight states moving at least nine positions. "
        "An upward line indicates improved attractiveness after housing "
        "costs are considered; a downward line indicates deterioration. "
        "Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="center",
    align="center",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_7.show()

### Finding

Housing costs substantially reshape Germany’s regional economic ranking.

**Hamburg** falls from first place in GDP per capita to last place in the illustrative affordability ranking, a decline of **15 positions**. **Bavaria** loses 12 positions, while Hesse and Berlin each lose nine. Strong economic productivity therefore does not automatically translate into stronger financial value for workers.

The reverse pattern appears in eastern Germany. **Saxony-Anhalt** rises from 15th in productivity to first in affordability, gaining **14 positions**. Mecklenburg-Vorpommern, Saxony and Thuringia each improve by ten positions once housing costs are considered.

These results do not mean that lower-productivity states provide better career markets overall. They demonstrate that the preferred location can change considerably depending on whether the decision prioritises economic output or housing affordability.

In [113]:
FIGURE_7_HTML = (
    FIGURE_FOLDER
    / "07_productivity_vs_affordability_rank.html"
)

FIGURE_7_PNG = (
    FIGURE_FOLDER
    / "07_productivity_vs_affordability_rank.png"
)

fig_7.write_html(
    FIGURE_7_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_7_HTML.exists()
)

try:
    fig_7.write_image(
        FIGURE_7_PNG,
        width=1500,
        height=950,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_7_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

## Analytical Question 8

### Which German states are established career hubs, and which are emerging challengers?

This analysis compares current career-market strength with regional momentum. States scoring highly on both dimensions represent established and expanding hubs, while states with weaker current labour markets but strong momentum may represent emerging challengers.

In [114]:
market_position_data = analysis_snapshot[
    [
        "state_name",
        "population",
        "career_strength_score",
        "regional_momentum_score",
        "opportunity_score",
        "unemployment_rate",
        "it_science_service_employment",
        "population_change_10_years",
        "total_migration_balance"
    ]
].copy()

median_career_strength = market_position_data[
    "career_strength_score"
].median()

median_regional_momentum = market_position_data[
    "regional_momentum_score"
].median()

market_position_data["market_position"] = np.select(
    [
        (
            market_position_data["career_strength_score"]
            >= median_career_strength
        )
        & (
            market_position_data["regional_momentum_score"]
            >= median_regional_momentum
        ),
        (
            market_position_data["career_strength_score"]
            < median_career_strength
        )
        & (
            market_position_data["regional_momentum_score"]
            >= median_regional_momentum
        ),
        (
            market_position_data["career_strength_score"]
            >= median_career_strength
        )
        & (
            market_position_data["regional_momentum_score"]
            < median_regional_momentum
        )
    ],
    [
        "Established leader",
        "Emerging challenger",
        "Strong but slower-moving"
    ],
    default="Currently constrained"
)

print(
    "Median career-strength score:",
    round(median_career_strength, 2)
)

print(
    "Median regional-momentum score:",
    round(median_regional_momentum, 2)
)

position_summary = (
    market_position_data[
        [
            "state_name",
            "career_strength_score",
            "regional_momentum_score",
            "market_position"
        ]
    ]
    .sort_values(
        [
            "market_position",
            "career_strength_score"
        ],
        ascending=[
            True,
            False
        ]
    )
    .reset_index(drop=True)
)

print(position_summary.round(2).to_string(index=False))

Median career-strength score: 50.7
Median regional-momentum score: 50.0
            state_name  career_strength_score  regional_momentum_score          market_position
   Nordrhein-Westfalen                  49.22                    25.00    Currently constrained
             Thüringen                  45.31                    28.12    Currently constrained
              Saarland                  37.81                    40.62    Currently constrained
        Sachsen-Anhalt                  36.25                    37.50    Currently constrained
    Schleswig-Holstein                  43.44                    50.00      Emerging challenger
                Bremen                  42.50                    50.00      Emerging challenger
           Brandenburg                  36.88                    78.12      Emerging challenger
Mecklenburg-Vorpommern                  25.94                    50.00      Emerging challenger
                Bayern                  87.19                    50.00       Established leader
     Baden-Württemberg                  80.94                    50.00       Established leader
                Hessen                  79.38                    56.25       Established leader
               Hamburg                  67.66                    87.50       Established leader
                Berlin                  53.44                   100.00       Established leader
         Niedersachsen                  52.19                    59.38       Established leader
               Sachsen                  56.88                    43.75 Strong but slower-moving
       Rheinland-Pfalz                  55.00                    43.75 Strong but slower-moving

In [115]:
for position in [
    "Established leader",
    "Emerging challenger",
    "Strong but slower-moving",
    "Currently constrained"
]:
    states = (
        market_position_data.loc[
            market_position_data["market_position"] == position,
            "state_name"
        ]
        .sort_values()
        .tolist()
    )

    print(f"\n{position}:")
    print(states)

Established leader:
['Baden-Württemberg', 'Bayern', 'Berlin', 'Hamburg', 'Hessen', 'Niedersachsen']

Emerging challenger:
['Brandenburg', 'Bremen', 'Mecklenburg-Vorpommern', 'Schleswig-Holstein']

Strong but slower-moving:
['Rheinland-Pfalz', 'Sachsen']

Currently constrained:
['Nordrhein-Westfalen', 'Saarland', 'Sachsen-Anhalt', 'Thüringen']

In [116]:
highlight_positions = {
    "Established leader",
    "Emerging challenger"
}

market_position_data["point_colour"] = np.where(
    market_position_data["market_position"].isin(
        highlight_positions
    ),
    "#0072B2",
    "#C4CBD4"
)

symbol_mapping = {
    "Established leader": "circle",
    "Emerging challenger": "diamond",
    "Strong but slower-moving": "circle",
    "Currently constrained": "circle"
}

market_position_data["point_symbol"] = (
    market_position_data["market_position"]
    .map(symbol_mapping)
)

market_position_data["point_size"] = (
    14
    + 28
    * np.sqrt(
        market_position_data["population"]
        / market_position_data["population"].max()
    )
)

# Label established leaders, emerging challengers,
# and a few strategically important states
market_position_data["show_label"] = (
    market_position_data["market_position"].isin(
        highlight_positions
    )
    | market_position_data["state_name"].isin(
        [
            "Bayern",
            "Baden-Württemberg",
            "Nordrhein-Westfalen",
            "Sachsen"
        ]
    )
)

market_position_data["display_label"] = (
    market_position_data["state_name"]
    .where(
        market_position_data["show_label"],
        ""
    )
)

label_positions = {
    "Berlin": "top right",
    "Hamburg": "top left",
    "Hessen": "bottom right",
    "Bayern": "bottom left",
    "Baden-Württemberg": "top left",
    "Brandenburg": "top right",
    "Bremen": "bottom right",
    "Schleswig-Holstein": "top left",
    "Nordrhein-Westfalen": "bottom left",
    "Sachsen": "top right"
}

market_position_data["text_position"] = (
    market_position_data["state_name"]
    .map(label_positions)
    .fillna("top center")
)

In [117]:
fig_8 = go.Figure()

fig_8.add_trace(
    go.Scatter(
        x=market_position_data[
            "career_strength_score"
        ],
        y=market_position_data[
            "regional_momentum_score"
        ],
        mode="markers+text",
        text=market_position_data["display_label"],
        textposition=market_position_data[
            "text_position"
        ],
        textfont={
            "size": 11,
            "color": "#374151"
        },
        marker={
            "size": market_position_data["point_size"],
            "color": market_position_data[
                "point_colour"
            ],
            "symbol": market_position_data[
                "point_symbol"
            ],
            "opacity": 0.9,
            "line": {
                "color": "white",
                "width": 1.5
            }
        },
        customdata=market_position_data[
            [
                "state_name",
                "market_position",
                "opportunity_score",
                "unemployment_rate",
                "it_science_service_employment",
                "population_change_10_years",
                "total_migration_balance"
            ]
        ],
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "Position: %{customdata[1]}<br>"
            "Career-strength score: %{x:.1f}<br>"
            "Regional-momentum score: %{y:.1f}<br>"
            "Overall opportunity score: %{customdata[2]:.1f}<br>"
            "Unemployment rate: %{customdata[3]:.2f}%<br>"
            "IT and science employment: %{customdata[4]:.2f}%<br>"
            "10-year population change: %{customdata[5]:+.2f}%<br>"
            "Migration balance: %{customdata[6]:.2f}"
            "<extra></extra>"
        ),
        showlegend=False
    )
)

fig_8 = apply_publication_style(
    fig_8,
    title=(
        "Current career strength and future momentum "
        "identify different regional opportunities"
    ),
    subtitle=(
        "Career-market strength versus demographic and migration "
        "momentum across Germany’s 16 states, 2022"
    ),
    x_title="Career-strength score (0–100)",
    y_title="Regional-momentum score (0–100)",
    height=720
)

fig_8.update_layout(
    margin={
        "l": 100,
        "r": 70,
        "t": 115,
        "b": 105
    }
)

fig_8.update_xaxes(
    range=[15, 100]
)

fig_8.update_yaxes(
    range=[0, 108]
)

fig_8.add_vline(
    x=median_career_strength,
    line_width=1.2,
    line_dash="dot",
    line_color="#A5ADB8"
)

fig_8.add_hline(
    y=median_regional_momentum,
    line_width=1.2,
    line_dash="dot",
    line_color="#A5ADB8"
)

# Quadrant labels
fig_8.add_annotation(
    x=0.98,
    y=0.97,
    xref="paper",
    yref="paper",
    text="<b>Established leaders</b>",
    showarrow=False,
    xanchor="right",
    font={
        "size": 12,
        "color": "#0072B2"
    }
)

fig_8.add_annotation(
    x=0.02,
    y=0.97,
    xref="paper",
    yref="paper",
    text="<b>Emerging challengers</b>",
    showarrow=False,
    xanchor="left",
    font={
        "size": 12,
        "color": "#0072B2"
    }
)

fig_8.add_annotation(
    x=0.98,
    y=0.04,
    xref="paper",
    yref="paper",
    text="Strong but slower-moving",
    showarrow=False,
    xanchor="right",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_8.add_annotation(
    x=0.02,
    y=0.04,
    xref="paper",
    yref="paper",
    text="Currently constrained",
    showarrow=False,
    xanchor="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_8.add_annotation(
    x=0,
    y=-0.17,
    xref="paper",
    yref="paper",
    text=(
        "Circle size represents population. Diamonds identify emerging "
        "challengers; blue circles identify established leaders. "
        "Quadrants use the median career and momentum scores. "
        "Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_8.show()

### Finding

Six states qualify as **established leaders** by combining above-median career strength with above-median regional momentum: **Baden-Württemberg, Bavaria, Berlin, Hamburg, Hesse and Lower Saxony**.

The composition of this group is not uniform. Baden-Württemberg and Bavaria lead primarily through strong labour-market fundamentals, while Berlin and Hamburg benefit more heavily from digital specialisation and regional momentum.

**Brandenburg, Bremen, Mecklenburg-Vorpommern and Schleswig-Holstein** are classified as emerging challengers. Their current specialist labour markets remain below the state median, but stronger demographic or migration momentum suggests potential for future development.

North Rhine-Westphalia provides an especially important contrast. Although it ranks fourth in the overall opportunity index, it falls into the currently constrained career-and-momentum quadrant. Its strong overall result is therefore driven mainly by affordability and income rather than specialist labour-market depth.

These categories are relative to the median of Germany’s 16 states and should not be interpreted as absolute assessments of regional quality.

In [118]:
FIGURE_8_HTML = (
    FIGURE_FOLDER
    / "08_established_vs_emerging_hubs.html"
)

FIGURE_8_PNG = (
    FIGURE_FOLDER
    / "08_established_vs_emerging_hubs.png"
)

fig_8.write_html(
    FIGURE_8_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_8_HTML.exists()
)

try:
    fig_8.write_image(
        FIGURE_8_PNG,
        width=1400,
        height=900,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_8_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

## Analytical Question 9

### How does Berlin compare with Germany’s other major career centres?

This profile compares Berlin with six major regional competitors across career strength, affordability, income and economic performance, digital readiness, and regional momentum.

Rather than comparing raw indicators with different units, the analysis uses the standardised category scores developed for the opportunity model.

In [119]:
BERLIN_PEER_STATES = [
    "Hamburg",
    "Bayern",
    "Baden-Württemberg",
    "Hessen",
    "Nordrhein-Westfalen",
    "Sachsen"
]

PROFILE_METRICS = {
    "career_strength_score": "Career strength",
    "affordability_score": "Affordability",
    "income_economic_score": "Income and economy",
    "digital_readiness_score": "Digital readiness",
    "regional_momentum_score": "Regional momentum"
}

berlin_row = (
    analysis_snapshot.loc[
        analysis_snapshot["state_name"] == "Berlin"
    ]
    .iloc[0]
)

peer_rows = analysis_snapshot[
    analysis_snapshot["state_name"].isin(
        BERLIN_PEER_STATES
    )
].copy()

berlin_peer_records = []

for metric, label in PROFILE_METRICS.items():

    peer_metric_values = peer_rows[
        [
            "state_name",
            metric
        ]
    ].copy()

    best_peer_row = peer_metric_values.loc[
        peer_metric_values[metric].idxmax()
    ]

    weakest_peer_row = peer_metric_values.loc[
        peer_metric_values[metric].idxmin()
    ]

    berlin_score = berlin_row[metric]
    peer_median = peer_metric_values[metric].median()

    berlin_peer_records.append(
        {
            "metric": metric,
            "metric_label": label,
            "berlin_score": berlin_score,
            "peer_median": peer_median,
            "peer_min": peer_metric_values[metric].min(),
            "peer_max": peer_metric_values[metric].max(),
            "difference_from_peer_median": (
                berlin_score - peer_median
            ),
            "best_peer": best_peer_row["state_name"],
            "best_peer_score": best_peer_row[metric],
            "weakest_peer": weakest_peer_row["state_name"],
            "weakest_peer_score": weakest_peer_row[metric]
        }
    )

berlin_peer_profile = pd.DataFrame(
    berlin_peer_records
)

display(
    berlin_peer_profile[
        [
            "metric_label",
            "berlin_score",
            "peer_median",
            "difference_from_peer_median",
            "best_peer",
            "best_peer_score"
        ]
    ].round(2)
)

,metric_label,berlin_score,peer_median,difference_from_peer_median,best_peer,best_peer_score
0,Career strength,53.44,73.52,-20.08,Bayern,87.19
1,Affordability,13.12,28.12,-15.00,Sachsen,94.38
2,Income and economy,52.50,88.59,-36.09,Baden-Württemberg,91.25
3,Digital readiness,93.75,65.62,28.12,Hamburg,100.00
4,Regional momentum,100.00,50.00,50.00,Hamburg,87.50

In [120]:
# Keep the most strategically important dimensions at the top
profile_order = [
    "Career strength",
    "Income and economy",
    "Affordability",
    "Digital readiness",
    "Regional momentum"
]

berlin_peer_profile["metric_label"] = pd.Categorical(
    berlin_peer_profile["metric_label"],
    categories=profile_order,
    ordered=True
)

berlin_peer_profile = (
    berlin_peer_profile
    .sort_values("metric_label", ascending=False)
    .reset_index(drop=True)
)

fig_9 = go.Figure()

# Peer ranges
for _, row in berlin_peer_profile.iterrows():

    fig_9.add_trace(
        go.Scatter(
            x=[
                row["peer_min"],
                row["peer_max"]
            ],
            y=[
                row["metric_label"],
                row["metric_label"]
            ],
            mode="lines",
            line={
                "color": "#D1D6DC",
                "width": 7
            },
            hoverinfo="skip",
            showlegend=False
        )
    )

# Peer median
fig_9.add_trace(
    go.Scatter(
        x=berlin_peer_profile["peer_median"],
        y=berlin_peer_profile["metric_label"],
        mode="markers",
        marker={
            "size": 12,
            "color": "white",
            "line": {
                "color": "#7B8490",
                "width": 2
            },
            "symbol": "circle"
        },
        customdata=berlin_peer_profile[
            [
                "best_peer",
                "best_peer_score",
                "weakest_peer",
                "weakest_peer_score"
            ]
        ],
        hovertemplate=(
            "<b>Peer median</b><br>"
            "%{y}: %{x:.1f}<br>"
            "Best peer: %{customdata[0]} "
            "(%{customdata[1]:.1f})<br>"
            "Lowest peer: %{customdata[2]} "
            "(%{customdata[3]:.1f})"
            "<extra></extra>"
        ),
        name="Peer median"
    )
)

# Berlin
fig_9.add_trace(
    go.Scatter(
        x=berlin_peer_profile["berlin_score"],
        y=berlin_peer_profile["metric_label"],
        mode="markers+text",
        marker={
            "size": 15,
            "color": "#0072B2",
            "line": {
                "color": "white",
                "width": 1.5
            }
        },
        text=berlin_peer_profile[
            "berlin_score"
        ].map(
            lambda value: f"{value:.1f}"
        ),
        textposition="middle right",
        textfont={
            "size": 11,
            "color": "#0072B2"
        },
        customdata=berlin_peer_profile[
            [
                "peer_median",
                "difference_from_peer_median",
                "best_peer",
                "best_peer_score"
            ]
        ],
        hovertemplate=(
            "<b>Berlin</b><br>"
            "%{y}: %{x:.1f}<br>"
            "Peer median: %{customdata[0]:.1f}<br>"
            "Difference: %{customdata[1]:+.1f} points<br>"
            "Best peer: %{customdata[2]} "
            "(%{customdata[3]:.1f})"
            "<extra></extra>"
        ),
        name="Berlin"
    )
)

fig_9.update_layout(
    title={
        "text": (
            "<b>Berlin’s digital strength and momentum are offset "
            "by weaker affordability and economic performance</b>"
            "<br><span style='font-size:14px;color:#5F6B7A'>"
            "Berlin compared with Hamburg, Bavaria, "
            "Baden-Württemberg, Hesse, North Rhine-Westphalia "
            "and Saxony, 2022"
            "</span>"
        ),
        "x": 0,
        "xanchor": "left",
        "y": 0.97,
        "yanchor": "top"
    },
    font={
        "family": "Arial, sans-serif",
        "size": 14,
        "color": "#1F2933"
    },
    paper_bgcolor="white",
    plot_bgcolor="white",
    height=620,
    margin={
        "l": 160,
        "r": 90,
        "t": 125,
        "b": 110
    },
    legend={
        "orientation": "h",
        "x": 0,
        "y": 1.04,
        "xanchor": "left",
        "yanchor": "bottom",
        "font": {
            "size": 12
        }
    },
    hoverlabel={
        "bgcolor": "white",
        "font_size": 13
    }
)

fig_9.update_xaxes(
    title="Relative category score (0–100)",
    range=[0, 108],
    showgrid=False,
    zeroline=False,
    showline=True,
    linecolor="#D7DCE2",
    ticks="outside"
)

fig_9.update_yaxes(
    title="",
    showgrid=False,
    zeroline=False,
    showline=False,
    ticks=""
)

fig_9.add_vline(
    x=50,
    line_width=1,
    line_dash="dot",
    line_color="#E0E4E8"
)

fig_9.add_annotation(
    x=0,
    y=-0.20,
    xref="paper",
    yref="paper",
    text=(
        "Grey ranges show the minimum and maximum scores among the "
        "six comparison states. Hollow markers represent their median; "
        "blue markers represent Berlin. Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_9.show()

### Finding

Berlin performs exceptionally well in **digital readiness** and **regional momentum**. Its digital-readiness score is **28.12 points above the comparison-group median**, while its regional-momentum score is **50 points higher**.

However, this strength does not extend evenly across all dimensions. Berlin scores approximately **20 points below the peer median in career strength**, **15 points below in affordability**, and **36 points below in income and economic performance**.

The largest economic gap is against Baden-Württemberg, while Bavaria leads the peer group in career strength. Hamburg slightly exceeds Berlin in digital readiness, but Berlin achieves the strongest regional momentum.

Berlin should therefore be interpreted as a dynamic and digitally specialised location rather than the strongest all-round destination. It may appeal most to professionals prioritising technology ecosystems, connectivity and future growth, while candidates prioritising income, affordability or labour-market stability may prefer other regions.

In [121]:
FIGURE_9_HTML = (
    FIGURE_FOLDER
    / "09_berlin_peer_profile.html"
)

FIGURE_9_PNG = (
    FIGURE_FOLDER
    / "09_berlin_peer_profile.png"
)

fig_9.write_html(
    FIGURE_9_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_9_HTML.exists()
)

try:
    fig_9.write_image(
        FIGURE_9_PNG,
        width=1400,
        height=850,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_9_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

## Analytical Question 10

### How does the preferred German state change when users prioritise career strength, affordability, income or regional growth?

A single fixed ranking cannot represent every professional's preferences. This scenario analysis recalculates the regional opportunity ranking under five different decision profiles: balanced, career-first, affordability-first, income-first and growth-first.

In [122]:
SCENARIO_WEIGHTS = {
    "Balanced": {
        "career_strength_score": 0.35,
        "affordability_score": 0.25,
        "income_economic_score": 0.20,
        "digital_readiness_score": 0.10,
        "regional_momentum_score": 0.10
    },

    "Career first": {
        "career_strength_score": 0.55,
        "affordability_score": 0.10,
        "income_economic_score": 0.15,
        "digital_readiness_score": 0.10,
        "regional_momentum_score": 0.10
    },

    "Affordability first": {
        "career_strength_score": 0.15,
        "affordability_score": 0.55,
        "income_economic_score": 0.10,
        "digital_readiness_score": 0.10,
        "regional_momentum_score": 0.10
    },

    "Income first": {
        "career_strength_score": 0.15,
        "affordability_score": 0.10,
        "income_economic_score": 0.55,
        "digital_readiness_score": 0.10,
        "regional_momentum_score": 0.10
    },

    "Growth first": {
        "career_strength_score": 0.15,
        "affordability_score": 0.10,
        "income_economic_score": 0.10,
        "digital_readiness_score": 0.10,
        "regional_momentum_score": 0.55
    }
}

SCENARIO_ORDER = list(SCENARIO_WEIGHTS.keys())

for scenario, weights in SCENARIO_WEIGHTS.items():

    total_weight = sum(weights.values())

    print(
        scenario,
        "total weight:",
        round(total_weight, 2)
    )

    assert round(total_weight, 10) == 1.0, (
        f"{scenario} weights must total 1.0"
    )

Balanced total weight: 1.0
Career first total weight: 1.0
Affordability first total weight: 1.0
Income first total weight: 1.0
Growth first total weight: 1.0

In [123]:
scenario_records = []

for _, state_row in analysis_snapshot.iterrows():

    for scenario in SCENARIO_ORDER:

        weights = SCENARIO_WEIGHTS[scenario]

        scenario_score = sum(
            state_row[category] * weight
            for category, weight in weights.items()
        )

        scenario_records.append(
            {
                "state_name": state_row["state_name"],
                "scenario": scenario,
                "scenario_score": scenario_score
            }
        )

scenario_rankings = pd.DataFrame(
    scenario_records
)

scenario_rankings["rank"] = (
    scenario_rankings
    .groupby("scenario")["scenario_score"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)

scenario_rankings["scenario"] = pd.Categorical(
    scenario_rankings["scenario"],
    categories=SCENARIO_ORDER,
    ordered=True
)

scenario_rankings = scenario_rankings.sort_values(
    [
        "scenario",
        "rank",
        "state_name"
    ]
).reset_index(drop=True)

display(scenario_rankings.head(20))

                state_name      scenario  scenario_score  rank
0        Baden-Württemberg      Balanced       64.859375     1
1                   Bayern      Balanced       64.859375     1
2                   Hessen      Balanced       63.937500     3
3      Nordrhein-Westfalen      Balanced       62.757812     4
4                  Hamburg      Balanced       61.554688     5
5                   Bremen      Balanced       56.312500     6
6                  Sachsen      Balanced       55.625000     7
7          Rheinland-Pfalz      Balanced       52.000000     8
8                   Berlin      Balanced       51.859375     9
9                 Saarland      Balanced       49.890625    10
10           Niedersachsen      Balanced       49.234375    11
11          Sachsen-Anhalt      Balanced       47.281250    12
12      Schleswig-Holstein      Balanced       46.953125    13
13             Brandenburg      Balanced       44.375000    14
14               Thüringen      Balanced       40.390625    15
15  Mecklenburg-Vorpommern      Balanced       38.109375    16
16                  Bayern  Career first       75.093750     1
17       Baden-Württemberg  Career first       71.890625     2
18                  Hessen  Career first       71.500000     3
19                 Hamburg  Career first       69.757812     4

In [124]:
for scenario in SCENARIO_ORDER:

    scenario_top_five = (
        scenario_rankings[
            scenario_rankings["scenario"] == scenario
        ]
        .sort_values(
            [
                "rank",
                "scenario_score"
            ],
            ascending=[
                True,
                False
            ]
        )
        .head(5)
    )

    print("\n" + "=" * 70)
    print(scenario)
    print("=" * 70)

    print(
        scenario_top_five[
            [
                "rank",
                "state_name",
                "scenario_score"
            ]
        ]
        .round(2)
        .to_string(index=False)
    )

======================================================================
Balanced
======================================================================
 rank          state_name  scenario_score
    1   Baden-Württemberg           64.86
    1              Bayern           64.86
    3              Hessen           63.94
    4 Nordrhein-Westfalen           62.76
    5             Hamburg           61.55

======================================================================
Career first
======================================================================
 rank        state_name  scenario_score
    1            Bayern           75.09
    2 Baden-Württemberg           71.89
    3            Hessen           71.50
    4           Hamburg           69.76
    5            Berlin           57.95

======================================================================
Affordability first
======================================================================
 rank          state_name  scenario_score
    1 Nordrhein-Westfalen           70.79
    2             Sachsen           70.25
    3      Sachsen-Anhalt           67.78
    4            Saarland           59.30
    5              Bremen           56.81

======================================================================
Income first
======================================================================
 rank          state_name  scenario_score
    1             Hamburg           77.82
    2              Bayern           76.09
    3   Baden-Württemberg           76.02
    4              Hessen           75.50
    5 Nordrhein-Westfalen           65.16

======================================================================
Growth first
======================================================================
 rank  state_name  scenario_score
    1      Berlin           78.95
    2     Hamburg           77.68
    3 Brandenburg           60.88
    4      Hessen           60.59
    5      Bayern           58.23

In [125]:
scenario_rank_matrix = (
    scenario_rankings
    .pivot(
        index="state_name",
        columns="scenario",
        values="rank"
    )
    [SCENARIO_ORDER]
    .reset_index()
)

scenario_rank_matrix["best_rank"] = (
    scenario_rank_matrix[
        SCENARIO_ORDER
    ].min(axis=1)
)

scenario_rank_matrix["worst_rank"] = (
    scenario_rank_matrix[
        SCENARIO_ORDER
    ].max(axis=1)
)

scenario_rank_matrix["rank_range"] = (
    scenario_rank_matrix["worst_rank"]
    - scenario_rank_matrix["best_rank"]
)

most_priority_sensitive = (
    scenario_rank_matrix
    .sort_values(
        [
            "rank_range",
            "best_rank"
        ],
        ascending=[
            False,
            True
        ]
    )
    .reset_index(drop=True)
)

print(
    most_priority_sensitive[
        [
            "state_name",
            *SCENARIO_ORDER,
            "best_rank",
            "worst_rank",
            "rank_range"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

            state_name  Balanced  Career first  Affordability first  Income first  Growth first  best_rank  worst_rank  rank_range
                Berlin         9             5                   16             7             1          1          16          15
               Hamburg         5             4                   15             1             2          1          15          14
                Bayern         1             1                   14             2             5          1          14          13
   Nordrhein-Westfalen         4             6                    1             5            13          1          13          12
        Sachsen-Anhalt        12            14                    3            14            15          3          15          12
               Sachsen         7             8                    2            13            10          2          13          11
           Brandenburg        14            13                    9            12             3          3          14          11
     Baden-Württemberg         1             2                   11             3             6          1          11          10
Mecklenburg-Vorpommern        16            16                    6            15            14          6          16          10
                Hessen         3             3                   12             4             4          3          12           9

In [126]:
# Add each state's ranking sensitivity to the plotting data
scenario_plot_data = scenario_rankings.merge(
    most_priority_sensitive[
        [
            "state_name",
            "best_rank",
            "worst_rank",
            "rank_range"
        ]
    ],
    on="state_name",
    how="left",
    validate="many_to_one"
)

# Highlight the six states whose rankings change the most
highlight_states = (
    most_priority_sensitive
    .head(6)["state_name"]
    .tolist()
)

# Colour-vision-deficiency-safe highlight colours
highlight_palette = [
    "#0072B2",
    "#D55E00",
    "#009E73",
    "#CC79A7",
    "#E69F00",
    "#56B4E9"
]

state_colour_map = dict(
    zip(
        highlight_states,
        highlight_palette
    )
)

print("Highlighted priority-sensitive states:")

for state in highlight_states:
    state_summary = most_priority_sensitive.loc[
        most_priority_sensitive["state_name"] == state
    ].iloc[0]

    print(
        f"{state}: "
        f"best rank {state_summary['best_rank']}, "
        f"worst rank {state_summary['worst_rank']}, "
        f"range {state_summary['rank_range']}"
    )

Highlighted priority-sensitive states:
Berlin: best rank 1, worst rank 16, range 15
Hamburg: best rank 1, worst rank 15, range 14
Bayern: best rank 1, worst rank 14, range 13
Nordrhein-Westfalen: best rank 1, worst rank 13, range 12
Sachsen-Anhalt: best rank 3, worst rank 15, range 12
Sachsen: best rank 2, worst rank 13, range 11

In [127]:
fig_10 = go.Figure()

background_states = [
    state
    for state in scenario_plot_data[
        "state_name"
    ].unique()
    if state not in highlight_states
]

# Draw muted background states first
for state in background_states:

    state_data = (
        scenario_plot_data.loc[
            scenario_plot_data["state_name"] == state
        ]
        .sort_values("scenario")
    )

    fig_10.add_trace(
        go.Scatter(
            x=state_data["scenario"].astype(str),
            y=state_data["rank"],
            mode="lines+markers",
            line={
                "color": "#D7DCE2",
                "width": 1.3
            },
            marker={
                "size": 5,
                "color": "#D7DCE2"
            },
            customdata=state_data[
                [
                    "scenario_score",
                    "best_rank",
                    "worst_rank",
                    "rank_range"
                ]
            ],
            hovertemplate=(
                f"<b>{state}</b><br>"
                "Scenario: %{x}<br>"
                "Rank: %{y}<br>"
                "Scenario score: %{customdata[0]:.1f}<br>"
                "Best rank: %{customdata[1]}<br>"
                "Worst rank: %{customdata[2]}<br>"
                "Total rank range: %{customdata[3]}"
                "<extra></extra>"
            ),
            showlegend=False
        )
    )

# Draw the most priority-sensitive states on top
for state in highlight_states:

    state_data = (
        scenario_plot_data.loc[
            scenario_plot_data["state_name"] == state
        ]
        .sort_values("scenario")
    )

    state_colour = state_colour_map[state]

    fig_10.add_trace(
        go.Scatter(
            x=state_data["scenario"].astype(str),
            y=state_data["rank"],
            mode="lines+markers",
            name=state,
            line={
                "color": state_colour,
                "width": 3
            },
            marker={
                "size": 9,
                "color": state_colour,
                "line": {
                    "color": "white",
                    "width": 1
                }
            },
            customdata=state_data[
                [
                    "scenario_score",
                    "best_rank",
                    "worst_rank",
                    "rank_range"
                ]
            ],
            hovertemplate=(
                f"<b>{state}</b><br>"
                "Scenario: %{x}<br>"
                "Rank: %{y}<br>"
                "Scenario score: %{customdata[0]:.1f}<br>"
                "Best rank: %{customdata[1]}<br>"
                "Worst rank: %{customdata[2]}<br>"
                "Total rank range: %{customdata[3]}"
                "<extra></extra>"
            ),
            showlegend=True
        )
    )

fig_10 = apply_publication_style(
    fig_10,
    title=(
        "Professional priorities completely reorder "
        "Germany’s regional opportunity ranking"
    ),
    subtitle=(
        "State rankings under balanced, career-first, affordability-first, "
        "income-first and growth-first decision profiles"
    ),
    x_title="Decision profile",
    y_title="Rank among Germany’s 16 states",
    height=760
)

fig_10.update_layout(
    margin={
        "l": 90,
        "r": 235,
        "t": 120,
        "b": 125
    },
    legend={
        "title": {
            "text": "Most priority-sensitive states"
        },
        "orientation": "v",
        "x": 1.02,
        "y": 0.98,
        "xanchor": "left",
        "yanchor": "top",
        "font": {
            "size": 11
        },
        "bgcolor": "rgba(255,255,255,0)"
    }
)

fig_10.update_xaxes(
    categoryorder="array",
    categoryarray=SCENARIO_ORDER,
    tickmode="array",
    tickvals=SCENARIO_ORDER,
    ticktext=[
        "Balanced",
        "Career<br>first",
        "Affordability<br>first",
        "Income<br>first",
        "Growth<br>first"
    ],
    showgrid=False
)

fig_10.update_yaxes(
    range=[16.6, 0.4],
    tickmode="linear",
    tick0=1,
    dtick=1,
    showgrid=True,
    gridcolor="#EEF1F4",
    gridwidth=1,
    zeroline=False
)

fig_10.add_annotation(
    x=0.01,
    y=0.02,
    xref="paper",
    yref="paper",
    text=(
        "<b>Berlin:</b> 16th under affordability-first, "
        "but 1st under growth-first"
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 12,
        "color": "#0072B2"
    },
    bgcolor="rgba(255,255,255,0.88)",
    borderpad=5
)

fig_10.add_annotation(
    x=0,
    y=-0.20,
    xref="paper",
    yref="paper",
    text=(
        "Grey lines show the remaining states. Scenario weights are "
        "illustrative decision profiles rather than universally optimal "
        "weightings. Rank 1 represents the strongest result. "
        "Source: INKAR 2025."
    ),
    showarrow=False,
    xanchor="left",
    align="left",
    font={
        "size": 11,
        "color": "#6B7280"
    }
)

fig_10.show()

In [128]:
scenario_winners = (
    scenario_plot_data.loc[
        scenario_plot_data["rank"] == 1,
        [
            "scenario",
            "state_name",
            "scenario_score"
        ]
    ]
    .sort_values(
        [
            "scenario",
            "state_name"
        ]
    )
    .reset_index(drop=True)
)

print("Scenario winners:")

print(
    scenario_winners
    .round(2)
    .to_string(index=False)
)

Scenario winners:
           scenario          state_name  scenario_score
           Balanced   Baden-Württemberg           64.86
           Balanced              Bayern           64.86
       Career first              Bayern           75.09
Affordability first Nordrhein-Westfalen           70.79
       Income first             Hamburg           77.82
       Growth first              Berlin           78.95

In [129]:
FIGURE_10_HTML = (
    FIGURE_FOLDER
    / "10_priority_scenario_rankings.html"
)

FIGURE_10_PNG = (
    FIGURE_FOLDER
    / "10_priority_scenario_rankings.png"
)

fig_10.write_html(
    FIGURE_10_HTML,
    include_plotlyjs="cdn"
)

print(
    "Interactive HTML saved:",
    FIGURE_10_HTML.exists()
)

try:
    fig_10.write_image(
        FIGURE_10_PNG,
        width=1600,
        height=950,
        scale=2
    )

    print(
        "PNG saved:",
        FIGURE_10_PNG.exists()
    )

except Exception as error:
    print("PNG export could not be completed.")
    print("Reason:", error)

Interactive HTML saved: True
PNG saved: True

### Finding

The preferred German state changes substantially according to the professional's priorities.

Under the balanced model, **Baden-Württemberg and Bavaria share first place**. Bavaria becomes the sole leader when career-market strength receives the greatest weight, while **Hamburg ranks first under the income-focused profile**.

**North Rhine-Westphalia rises to first place when affordability is prioritised**, demonstrating how its comparatively favourable income-to-rent position compensates for weaker regional momentum. Berlin shows the most dramatic reversal: it ranks **first under the growth-focused profile but last under the affordability-focused profile**.

Hamburg and Bavaria display similar trade-offs. Hamburg moves from first under income to 15th under affordability, while Bavaria moves from first under career strength to 14th under affordability.

The results demonstrate why a single composite ranking should not be presented as a universal answer. Regional attractiveness depends on whether a professional values established career opportunities, current income, housing affordability or future growth most strongly.